// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.evaluate(()=>{window.testInitial=clone(graph);});

await page.selectOption('#language','en');
const initialTypes=await page.evaluate(()=>current().nodes.map(n=>[n.id,n.params.type,n.ui.typeMode]));await page.evaluate(()=>render());assert.deepEqual(await page.evaluate(()=>current().nodes.map(n=>[n.id,n.params.type,n.ui.typeMode])),initialTypes);checks.push('Loading and rendering old graphs do not add Auto or change stored types');
await page.locator('[data-library-tab=nodes]').click();await page.locator('[data-node-category=math]').click();await page.locator('#nodes [data-entry=add]').click();
assert.equal(await page.locator('[data-math-type]').inputValue(),'auto');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).params.type),'float');checks.push('Creating Add from the left palette defaults to Auto and exposes the Type control');
await page.evaluate(()=>{
 window.makeNode=(key,id,x,y,type,auto=false)=>{const d=catalog.find(d=>d.key===key);return {id,definitionUuid:d.definitionUuid,revisionHash:d.revisionHash,params:{...clone(d.defaults),...(type?{type}:{})},ui:{x,y,...(auto?{typeMode:'auto'}:{})}};};
 window.resetAuto=()=>{graph=clone(testInitial);graph.functions=[];graph.stages.pixel={nodes:[makeNode('float','a',50,70),makeNode('float','b',50,300),makeNode('color','c',50,540),makeNode('multiply','m',450,160,'float',true),makeNode('pixel_out','out',850,160)],edges:[{from:['a','out'],to:['m','a']},{from:['b','out'],to:['m','b']},{from:['m','out'],to:['out','color']}]};stage='pixel';graphTrail=[];past=[];future=[];selected='m';selection=new Set(['m']);selectedEdge=null;linkStart=null;inspectorScope='node';inspectorTab='parameters';dirty=false;clearTimeout(autoTimer);applyGraph=async()=>{clearTimeout(autoTimer);};render();fit();};resetAuto();
});
const connect=async(from,port='a',to='m')=>page.evaluate(([source,port,target])=>connectPorts({kind:'outputs',node:source,port:'out',type:ports(current().nodes.find(n=>n.id===source),'outputs').out},{kind:'inputs',node:target,port,type:ports(current().nodes.find(n=>n.id===target),'inputs')[port]}),[from,port,to]);
assert.equal(await connect('c'),true);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'vec4');
assert.equal(await page.locator('[data-node=m] .node-output-type').innerText(),'vec4');assert.match(await page.locator('[data-node=m] .input').nth(1).innerText(),/float.*vec4/s);checks.push('A vec4 source can connect to an Auto float socket and the visible output and conversions update');
await page.evaluate(()=>undo());assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'float');await page.evaluate(()=>undo(true));assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'vec4');checks.push('Connection and all inferred changes share one Undo/Redo step');
await page.selectOption('[data-math-type]','vec4');assert.equal(await connect('a'),true);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'vec4');assert.equal(await page.locator('[data-math-type]').inputValue(),'vec4');
await page.selectOption('[data-math-type]','auto');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'float');checks.push('Manual type locks survive input changes; selecting Auto resumes inference');
await page.evaluate(()=>{resetAuto();current().nodes.push(makeNode('length','lock',730,430,'vec3'));current().edges.push({from:['m','out'],to:['lock','value']});render();fit();});
const before=await page.evaluate(()=>JSON.stringify({graph,past,future}));assert.equal(await connect('c'),false);assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future})),before);assert.match(await page.locator('#status').innerText(),/Auto|incompatible/);checks.push('An incompatible locked downstream rejects the whole connection without graph or Undo changes');
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='m'));render();});await page.selectOption('[data-math-type]','vec4');assert.equal(await page.locator('[data-math-type]').inputValue(),'auto');assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future})),before);checks.push('An unsafe manual type change rolls back the UI and graph too');
await page.evaluate(()=>{resetAuto();const rect=$('#canvas').getBoundingClientRect();openCreator(rect.left+100,rect.top+80,{kind:'outputs',node:'c',port:'out',type:'vec4'});});
await page.fill('#createsearch','Add');assert.match(await page.locator('#createresults [data-create-entry=add] small').innerText(),/vec4/);await page.click('#createresults [data-create-entry=add]');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).params.type),'vec4');assert.equal(await page.locator('[data-math-type]').inputValue(),'auto');checks.push('Drag-to-create uses the same Auto plan and produces a connected vec4 Add');
await page.evaluate(()=>{resetAuto();const rect=$('#canvas').getBoundingClientRect();openCreator(rect.left+100,rect.top+80,{kind:'inputs',node:'m',port:'a',type:'float'});});
await page.fill('#createsearch','Texture');assert.equal(await page.locator('#createresults [data-create-entry=texture]').count(),1);await page.click('#createresults [data-create-entry=texture]');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'vec4');checks.push('Reverse drag-to-create offers Texture 2D for an Auto input currently showing float');
await page.evaluate(()=>{resetAuto();const rect=$('#canvas').getBoundingClientRect();openCreator(rect.left+100,rect.top+80);});await page.selectOption('#createtype','vec3');await page.fill('#createsearch','Add');await page.click('#createresults [data-create-entry=add]');assert.equal(await page.locator('[data-math-type]').inputValue(),'vec3');checks.push('Explicit Create type filtering creates a manually locked node');
await page.evaluate(()=>{resetAuto();selectNode(current().nodes.find(n=>n.id==='m'));render();duplicateSelection();});assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).ui.typeMode),'auto');checks.push('Duplicated nodes preserve Auto policy and resolve for their copied connections');
await page.evaluate(()=>{resetAuto();selectNode(current().nodes.find(n=>n.id==='m'));render();window.savedClipboard=copyGraphSelection();});assert.equal(await page.evaluate(()=>pasteGraphSelection(savedClipboard,{x:500,y:550})),true);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).ui.typeMode),'auto');checks.push('Clipboard preserves Auto mode without requiring a new file format');
await page.evaluate(()=>{resetAuto();});const source=page.locator('[data-node=c] .output .port'),target=page.locator('[data-node=m] .input .port').first();const a=await source.boundingBox(),b=await target.boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12});assert.equal(await page.locator('.wire-target').count(),1);await page.mouse.up();assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='m').params.type),'vec4');checks.push('Real pointer dragging highlights and connects a legal Auto target');
await page.selectOption('#language','zh-Hant');await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='m'));render();});assert.match(await page.locator('[data-math-type]').locator('..').innerText(),/依輸入接線/);checks.push('Auto and locking explanations localize without translating GLSL type names');
await page.screenshot({path:path.join(folder,'auto-multiply.png')});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});
