/* Collapsed-node presentation and real canvas interaction; isolated fixture only. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const[source,stateFile,folder]=process.argv.slice(2);
(async()=>{
  const h=await harness(source,stateFile,folder),{page,checks,errors,settle,at,drag}=h;page.setDefaultTimeout(6000);
  const card=id=>`#cards [data-node="${id}"]`,port=(id,kind,name)=>`${card(id)} .port[data-kind="${kind}"][data-port="${name}"]`,toggle=id=>`${card(id)} .node-collapse-toggle`;
  const snapshot=()=>page.evaluate(()=>JSON.stringify({graph,past,future}));
  const graphOnly=()=>page.evaluate(()=>JSON.stringify(graph));
  const headerHeight=id=>page.locator(`${card(id)} .node-title`).evaluate(e=>e.offsetHeight);
  const reset=async()=>{await page.evaluate(()=>{
    cancelConnection();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;
    graph.functions=[];graph.declarations=[{id:'source_decl',kind:'uniform',name:'uScale',type:'float',value:.3}];graphTrail=[];stage='pixel';selected=selectedEdge=null;selection.clear();showCustomNodeNames=false;
    graph.stages.pixel={nodes:[testNode('scalar','float',20,35,{value:.3}),testNode('spare','float',20,220,{value:.7}),testNode('vector','vector',20,420,{type:'vec3',components:[.1,.2,.3,0]}),testNode('add','add',430,35,{type:'float'}),testNode('sum','add',800,35,{type:'float'}),testNode('split','vector_split',430,420,{type:'vec3'}),testNode('sink','length',800,260,{type:'float'}),testNode('output','pixel_out',800,500),testNode('uniform','uniform',430,720,{declarationId:'source_decl'})],edges:[{from:['scalar','out'],to:['add','a']},{from:['scalar','out'],to:['sum','a']},{from:['scalar','out'],to:['sum','b']},{from:['vector','out'],to:['split','value']},{from:['split','x'],to:['add','b']}]};
    current().nodes.forEach(n=>n.ui.typeMode='locked');current().nodes[0].ui.width=320;current().nodes[0].name='Gain';past=[];future=[];dirty=false;rememberSavedGraph(graph);render();fit();
  });await settle();};
  const collapse=async ids=>{await page.evaluate(ids=>setNodesCollapsed(ids,true),ids);await settle();};
  const clearHistory=()=>page.evaluate(()=>{past=[];future=[];dirty=false;rememberSavedGraph(graph);});
  const context=async id=>{await page.locator(`${card(id)} .node-title`).click({button:'right'});await page.locator('#grapheditmenu [data-edit="collapse"]').click();await settle();};
  const geometry=()=>page.evaluate(()=>{
    const issues=[],endpoints=[];
    for(const wire of document.querySelectorAll('#wires path[data-from]'))for(const[end,kind,atEnd]of[['from','outputs',false],['to','inputs',true]]){
      const[id,name]=wire.dataset[end].split(':'),node=document.querySelector(`#cards [data-node="${CSS.escape(id)}"]`),socket=node?.querySelector(`.port[data-kind="${kind}"][data-port="${CSS.escape(name)}"]`)||node?.querySelector(`.collapsed-port.aggregate[data-kind="${kind}"]`);
      if(!socket){issues.push('missing visible socket '+id+':'+name);continue;}
      const q=wire.getPointAtLength(atEnd?wire.getTotalLength():0),marker=document.createElementNS('http://www.w3.org/2000/svg','circle');marker.setAttribute('cx',q.x);marker.setAttribute('cy',q.y);marker.setAttribute('r',.01);wire.parentNode.append(marker);const r=marker.getBoundingClientRect(),s=socket.getBoundingClientRect();marker.remove();
      const error=Math.hypot(r.x+r.width/2-s.x-s.width/2,r.y+r.height/2-s.y-s.height/2);endpoints.push({id,name,kind,error});if(error>1)issues.push(id+':'+name+' endpoint offset '+error);
    }
    for(const anchor of document.querySelectorAll('.collapsed-wire-anchor')){const row=anchor.parentElement,dot=row.querySelector('.collapsed-port');if(!dot)continue;const a=anchor.getBoundingClientRect(),d=dot.getBoundingClientRect();if(Math.hypot(a.x+a.width/2-d.x-d.width/2,a.y+a.height/2-d.y-d.height/2)>1)issues.push('hidden anchor offset '+anchor.dataset.port);}
    return{issues,endpoints};
  });
  try{
    await reset();const baseline=await graphOnly(),expandedWidth=await page.locator(card('scalar')).evaluate(e=>e.offsetWidth),height=await headerHeight('scalar');
    await page.locator(toggle('scalar')).click();await settle();assert.equal(await page.locator(card('scalar')).evaluate(e=>e.classList.contains('collapsed')),true);assert.equal(await headerHeight('scalar'),height);assert.equal(await page.locator(`${card('scalar')} .node-resize-handle,${card('scalar')} input`).count(),0);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);assert.equal(await page.evaluate(()=>current().nodes[0].ui.width),320);
    let saved=await snapshot();await page.evaluate(()=>{render();render();});await settle();assert.equal(await snapshot(),saved,'rendering cannot initialize or mutate stored UI state');
    await page.locator('#undo').click();await settle();assert.equal(await graphOnly(),baseline);assert.equal(await page.locator(card('scalar')).evaluate(e=>e.offsetWidth),expandedWidth);await page.locator('#redo').click();await settle();assert.equal(await page.locator(card('scalar')).evaluate(e=>e.classList.contains('collapsed')),true);await page.locator(toggle('scalar')).click();await settle();assert.equal(await page.locator(card('scalar')).evaluate(e=>e.offsetWidth),expandedWidth);
    checks.push('collapse is a layout-only one-Undo action, render stays pure, title height stays fixed and expanding restores the saved width');


    await reset();await page.evaluate(()=>{delete current().nodes[0].ui;past=[];future=[];rememberSavedGraph(graph);});const missingUI=await graphOnly();await page.evaluate(()=>{render();render();fit();});await settle();assert.equal(await graphOnly(),missingUI,'render must preserve absent UI metadata');assert.equal(await page.evaluate(()=>Object.hasOwn(current().nodes[0],'ui')),false);
    await page.locator(toggle('scalar')).click();await settle();const collapsedMissingUI=await graphOnly();assert.deepEqual(await page.evaluate(()=>current().nodes[0].ui),{collapsed:true});const titlePoint=await at(`${card('scalar')} .node-function-title`);await drag(titlePoint,{x:titlePoint.x+55,y:titlePoint.y+40});const movedUI=await page.evaluate(()=>current().nodes[0].ui);assert.ok(Number.isFinite(movedUI.x)&&Number.isFinite(movedUI.y),JSON.stringify(movedUI));assert.ok(movedUI.x>0&&movedUI.y>0);assert.equal(movedUI.collapsed,true);assert.equal(await page.evaluate(()=>past.length),2);const movedGraph=await graphOnly();await page.evaluate(()=>{render();render();});await settle();assert.equal(await graphOnly(),movedGraph);await page.locator('#undo').click();await settle();assert.equal(await graphOnly(),collapsedMissingUI,'Undo drag removes newly created coordinates');await page.locator('#undo').click();await settle();assert.equal(await graphOnly(),missingUI,'Undo collapse restores originally absent UI metadata');assert.equal(await page.evaluate(()=>Object.hasOwn(current().nodes[0],'ui')),false);
    checks.push('nodes without UI metadata stay unchanged during render; a real collapsed-node drag creates finite coordinates and two Undo actions restore both exact prior states');

    await reset();await collapse(['scalar','spare','vector','add','sum','split','sink','output','uniform']);await clearHistory();
    assert.equal(await page.locator(`${card('scalar')} .collapsed-port[data-kind="inputs"]`).count(),0);assert.equal(await page.locator(`${card('scalar')} .collapsed-port.port[data-kind="outputs"]`).count(),1);assert.equal(await page.locator(`${card('scalar')} .collapsed-port.port`).getAttribute('data-type'),'float');assert.equal(await page.locator(`${card('output')} .collapsed-port[data-kind="outputs"]`).count(),0);
    assert.equal(await page.locator(`${card('split')} .collapsed-port.aggregate[data-kind="outputs"]`).count(),1);assert.equal(await page.locator(`${card('add')} .collapsed-port.aggregate[data-kind="inputs"]`).count(),1);assert.equal(await page.locator('.collapsed-port.aggregate.port,.collapsed-port.aggregate[data-port]').count(),0);assert.equal(await page.locator(`${card('split')} .collapsed-wire-anchor[data-kind="outputs"]`).count(),3);assert.equal(await page.locator('#wires path[data-from]').count(),5);
    let measured=await geometry();assert.deepEqual(measured.issues,[],JSON.stringify(measured));await page.screenshot({path:path.join(folder,'collapsed-ports.png')});
    checks.push('resolved port count controls zero/single/aggregate dots independently of fanout; existing wires meet the visible typed or aggregate socket');

    saved=await snapshot();let a=await at(`${card('split')} .aggregate`),b=await at(port('sink','inputs','value'));await drag(a,b);assert.equal(await snapshot(),saved,'aggregate output cannot start a connection');
    a=await at(port('spare','outputs','out'));b=await at(`${card('add')} .aggregate`);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await settle();assert.equal(await page.locator('#wires .wire-preview.ready').count(),0);await page.mouse.up();await settle();assert.equal(await snapshot(),saved,'aggregate input cannot accept a new connection');
    await drag(await at(port('scalar','outputs','out')),await at(port('sink','inputs','value')));assert.equal(await page.evaluate(()=>current().edges.length),6);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.locator(`${card('scalar')} .collapsed-port.port`).count(),1);assert.deepEqual((await geometry()).issues,[]);await page.locator('#undo').click();await settle();assert.equal(await graphOnly(),JSON.stringify(JSON.parse(saved).graph));assert.equal(await page.evaluate(()=>past.length),0);
    checks.push('aggregate sockets reject both drag directions while a single collapsed socket still creates ordinary fanout wiring in one Undo');

    await reset();await collapse(['scalar','split','add']);await clearHistory();const edgeBaseline=await graphOnly();
    const wirePoint=await page.locator('#wires path[data-from="split:x"]').evaluate(wire=>{for(const ratio of[.5,.35,.65,.2,.8]){const q=wire.getPointAtLength(wire.getTotalLength()*ratio),m=document.createElementNS('http://www.w3.org/2000/svg','circle');m.setAttribute('cx',q.x);m.setAttribute('cy',q.y);m.setAttribute('r',.01);m.style.pointerEvents='none';wire.parentNode.append(m);const r=m.getBoundingClientRect(),point={x:r.x+r.width/2,y:r.y+r.height/2};m.remove();if(document.elementFromPoint(point.x,point.y)===wire)return point;}return null;});assert.ok(wirePoint,'an existing aggregate wire must be hit-testable');await page.mouse.click(wirePoint.x,wirePoint.y);assert.notEqual(await page.evaluate(()=>selectedEdge),null);await page.locator('#graphdelete').click();await settle();assert.equal(await page.evaluate(()=>current().edges.length),4);assert.equal(await page.evaluate(()=>past.length),1);await page.locator('#undo').click();await settle();assert.equal(await graphOnly(),edgeBaseline);
    checks.push('existing aggregate wires remain selectable and removable, and Undo restores the exact connection');

    await reset();await collapse(['scalar']);await page.evaluate(()=>{selection=new Set(['scalar','spare']);selected='scalar';past=[];future=[];render();});await context('scalar');assert.deepEqual(await page.evaluate(()=>current().nodes.slice(0,2).map(n=>n.ui.collapsed)),[true,true]);assert.equal(await page.evaluate(()=>past.length),1);await context('scalar');assert.deepEqual(await page.evaluate(()=>current().nodes.slice(0,2).map(n=>n.ui.collapsed)),[false,false]);assert.equal(await page.evaluate(()=>past.length),2);await page.locator('#undo').click();await settle();assert.deepEqual(await page.evaluate(()=>current().nodes.slice(0,2).map(n=>n.ui.collapsed)),[true,true]);
    checks.push('context collapse handles mixed and fully collapsed selections as one batch per Undo');

    await reset();await collapse(['scalar']);const pasted=await page.evaluate(()=>{selectNode(current().nodes[0]);const copied=copyGraphSelection();pasteGraphSelection(copied,{x:440,y:200});return current().nodes.find(n=>selection.has(n.id));});await settle();assert.equal(pasted.ui.collapsed,true);assert.equal(pasted.ui.width,320);assert.equal(await page.locator(card(pasted.id)).evaluate(e=>e.classList.contains('collapsed')),true);await page.locator(toggle(pasted.id)).click();await settle();assert.equal(await page.locator(card(pasted.id)).evaluate(e=>e.offsetWidth),320);
    await collapse(['scalar','uniform']);await page.evaluate(()=>{showCustomNodeNames=true;render();});await settle();const namedHeight=await headerHeight('scalar'),sourceTitle=await page.locator(`${card('uniform')} .node-function-title`).innerText();await page.locator(`${card('scalar')} .node-function-title`).dblclick();assert.equal(await headerHeight('scalar'),namedHeight);const rename=page.locator(`${card('scalar')} [data-node-name]`);await rename.fill('Collapsed_Gain');await rename.press('Enter');await settle();assert.equal(await headerHeight('scalar'),namedHeight);assert.equal(await page.locator(`${card('scalar')} .node-function-title`).innerText(),'Collapsed_Gain');await page.locator(`${card('uniform')} .node-function-title`).dblclick();assert.equal(await page.locator(`${card('uniform')} [data-node-name]`).count(),0);assert.equal(await page.locator(`${card('uniform')} .node-function-title`).innerText(),sourceTitle);
    checks.push('copy/paste preserves collapse and expanded width; inline custom rename holds the header height and Uniform names remain source-owned');

    const samples=[];for(const percent of[75,125]){await reset();await collapse(['scalar','vector','add','sum','split','sink','output','uniform']);await page.evaluate(percent=>{setUIAppearance('scale',percent);fit();},percent);await settle();measured=await geometry();assert.deepEqual(measured.issues,[],JSON.stringify(measured));const bounds=await page.evaluate(()=>{const c=$('#canvas').getBoundingClientRect();return[...$('#cards').children].map(e=>{const r=e.getBoundingClientRect();return{id:e.dataset.node,inside:r.left>=c.left-1&&r.top>=c.top-1&&r.right<=c.right+1&&r.bottom<=c.bottom+1};});});assert.ok(bounds.every(v=>v.inside),JSON.stringify(bounds));samples.push({percent,...measured});await page.screenshot({path:path.join(folder,`collapsed-scale-${percent}.png`)});}
    const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});const p=await at(toggle('scalar'));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();assert.equal(await page.locator(card('scalar')).evaluate(e=>e.classList.contains('collapsed')),false);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await cdp.detach();fs.writeFileSync(path.join(folder,'geometry.json'),JSON.stringify(samples,null,2));
    checks.push('75% and 125% UI scale preserve collapsed wire alignment and fit bounds; a trusted touch tap expands the node');

    for(const expanded of[false,true])for(const collapsed of[false,true]){await page.route('**/graph_ui.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(source,'graph_ui.js'),'utf8').replace(/nodeCollapseExpandedHint:\s*(?:true|false)/,'nodeCollapseExpandedHint: '+expanded).replace(/nodeCollapseCollapsedHint:\s*(?:true|false)/,'nodeCollapseCollapsedHint: '+collapsed)}));await page.reload();await page.waitForSelector('.node');await page.evaluate(()=>{clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;stage='pixel';graphTrail=[];historyBusy=false;nativeMutationBusy=false;const n=current().nodes[0];n.ui||={};n.ui.collapsed=false;n.ui.x=20;n.ui.y=20;selection=new Set([n.id]);selected=n.id;past=[];future=[];render();fit();});await settle();const id=await page.evaluate(()=>selected);assert.equal(await page.locator(toggle(id)).count(),expanded?1:0);await context(id);assert.equal(await page.locator(card(id)).evaluate(e=>e.classList.contains('collapsed')),true,JSON.stringify(await page.evaluate(()=>({selected,selection:[...selection],status:$("#status")?.textContent,blocked:editorMutationBlocked(),nodes:current().nodes.map(n=>({id:n.id,ui:n.ui}))}))));assert.equal(await page.locator(toggle(id)).count(),collapsed?1:0);await context(id);assert.equal(await page.locator(card(id)).evaluate(e=>e.classList.contains('collapsed')),false);assert.equal(await page.locator(toggle(id)).count(),expanded?1:0);await page.unroute('**/graph_ui.js');}
    checks.push('expanded and collapsed hints can each be hidden independently; context actions always recover either state');
    assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);throw error;}
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
