// Read-only TD preview controls: node test_preview_controls.cjs SESSION_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const[sessionFile,folder,overlay]=process.argv.slice(2),session=JSON.parse(fs.readFileSync(sessionFile,'utf8'));fs.mkdirSync(folder,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[],writes=[];try{const page=await browser.newPage({viewport:{width:1500,height:1040}});let previews=0;page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async r=>{const q=r.request(),url=new URL(q.url()),name=q.resourceType()==='document'?'index.html':path.basename(url.pathname),file=overlay&&path.join(overlay,name);if(q.method()!=='GET'){writes.push(q.method());return r.abort();}if(url.pathname.endsWith('/preview')){previews++;await new Promise(resolve=>setTimeout(resolve,250));}return file&&fs.existsSync(file)?r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(name)]}):r.continue();});await page.goto(session.url);await page.waitForFunction(()=>graph&&document.querySelector('#preview').naturalWidth>0);const initial=await page.evaluate(()=>JSON.stringify({graph,revision}));assert.equal(await page.locator('#previewtitle').innerText(),'Output Preview');checks.push('TOP uses Output Preview and loads a real TD image');
await page.locator('#autopreview').uncheck();const count=previews,src=await page.locator('#preview').getAttribute('src');await page.evaluate(async()=>{await preview();await refreshUniforms();});await page.waitForTimeout(1200);assert.equal(previews,count);assert.equal(await page.locator('#preview').getAttribute('src'),src);checks.push('Auto off stops new automatic image requests while retaining the last image');
await page.locator('#refreshpreview').click();assert.equal(await page.locator('#livebody').getAttribute('aria-busy'),'true');assert.ok((await page.locator('#refreshpreview').getAttribute('class')).includes('is-loading'));await page.waitForFunction(()=>document.querySelector('#livebody').getAttribute('aria-busy')==='false');checks.push('pending request animates the Refresh icon and clears its busy state on completion');await page.waitForFunction(old=>document.querySelector('#preview').src!==old,src);assert.equal(previews,count+1);checks.push('manual Refresh requests one snapshot with Auto off');
let rect=await page.locator('#livebody .preview').boundingBox();assert.ok(rect.width>250);const beforeHeight=rect.height;await page.locator('#resize-live').focus();await page.keyboard.press('Home');rect=await page.locator('#livebody .preview').boundingBox();assert.ok(rect.height>beforeHeight+50);assert.equal(await page.locator('#preview').evaluate(e=>getComputedStyle(e).objectFit),'contain');checks.push('preview fills the pane beyond the former 180px cap and preserves source aspect ratio');
await page.screenshot({path:path.join(folder,'output-preview.png')});await page.reload();await page.waitForSelector('.node');assert.equal(await page.locator('#autopreview').isChecked(),false);const afterReload=previews;await page.waitForTimeout(1100);assert.equal(previews,afterReload);await page.locator('#refreshpreview').click();await page.waitForFunction(()=>document.querySelector('#preview').naturalWidth>0);checks.push('Auto preference persists and manual loading works after reload');
await page.locator('#autopreview').check();await page.waitForFunction(()=>document.querySelector('#preview').naturalWidth>0);await page.locator('#livetoggle').click();const collapsed=previews;await page.evaluate(()=>preview());await page.waitForTimeout(650);assert.equal(previews,collapsed);checks.push('collapsed preview skips image requests even with Auto enabled');
assert.equal(await page.evaluate(()=>JSON.stringify({graph,revision})),initial);assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);checks.push('preview controls leave TD graph and revision unchanged');fs.writeFileSync(path.join(folder,'preview-tests.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'preview-tests.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));throw e;}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
