/* Note appearance is UI metadata; fixture API never writes to TD.
 * node test_note_appearance.cjs SOURCE_DIR STATE_JSON REPORT_DIR */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
async function run(){
  const[source,stateFile,folder]=process.argv.slice(2),h=await harness(source,stateFile,folder,{touch:true}),{page,checks,errors,settle}=h;
  page.setDefaultTimeout(6000);
  const card=()=>page.locator('[data-node="note"]'),title=()=>card().locator('.node-title'),body=()=>card().locator('.comment-node-canvas-content'),preview=()=>card().locator('.comment-node-preview'),entry=()=>card().locator('[data-comment-node]');
  const control=key=>card().locator('[data-note-appearance="'+key+'"]');
  const transparent=async()=>{await card().locator('[data-note-color="note"]').click();await page.locator('[data-note-color-transparent]').click();await settle();};
  const preset=async color=>{await card().locator('[data-note-color="note"]').click();await page.locator('[data-frame-color-preset="'+color+'"]').click();await settle();};
  const graphJSON=()=>page.evaluate(()=>JSON.stringify(graph));
  const note=()=>page.evaluate(()=>clone(current().nodes.find(n=>n.id==='note')));
  const history=()=>page.evaluate(()=>past.length);
  const shape=async()=>page.evaluate(()=>{const card=document.querySelector('[data-node="note"]'),rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};};return{card:rect(card),body:rect(card.querySelector('.comment-node-canvas-content')),title:rect(card.querySelector('.node-title')),preview:rect(card.querySelector('.comment-node-preview'))};});
  const sameBody=(a,b)=>{for(const part of ['card','body','preview'])for(const axis of ['x','y','width','height'])assert.ok(Math.abs(a[part][axis]-b[part][axis])<.2,part+'.'+axis+' changed on selection');};
  const sameCard=(a,b)=>{for(const axis of ['x','y','width','height'])assert.ok(Math.abs(a.card[axis]-b.card[axis])<.2,'card '+axis+' stays fixed');};
  const select=async ids=>{await page.evaluate(ids=>{document.activeElement?.blur();selection=new Set(ids);selected=ids.at(-1)||null;selectedEdge=null;render();},ids);await settle();};
  const reset=async(ui={})=>{await page.setViewportSize({width:1600,height:1100});await page.evaluate(ui=>{
    document.activeElement?.blur();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;stage='pixel';graphTrail=[];graph=clone(window.noteAppearanceFixture);Object.assign(current().nodes.find(n=>n.id==='note').ui,ui);selected='note';selectedInputId=null;inspectorTab='parameters';selectedEdge=null;selection=new Set(['note']);past=[];future=[];dirty=false;rememberSavedGraph(graph);setUIAppearance('scale',100);setUIAppearance('theme','dark');setUIExperiments({selectionToolbar:'off',nodeBodyDrag:true,nodeCollapseExpandedHint:true});setGraphFocus(true);render();scale=1;pan={x:20,y:40};transform();
  },ui);await settle();};
  const drag=async(point,dx,dy)=>{await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+dx,point.y+dy,{steps:5});await page.mouse.up();await settle();};
  const titlePoint=async()=>{const r=await title().boundingBox();return{x:r.x+r.width*.56,y:r.y+r.height*.5};};
  try{
    await page.evaluate(()=>{stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];const note=testNode('note','comment',96,192),value=testNode('value','float',680,220),output=testNode('output','pixel_out',1040,220);Object.assign(note.ui,{width:420,height:300,comment:'# Note body\n\nSelect here, then drag its title.\n\n**Markdown** stays readable.'});note.name='Lighting_notes';graph.stages.pixel={nodes:[note,value,output],edges:[{from:['value','out'],to:['output','color']}]};window.noteAppearanceFixture=clone(graph);});
    await reset();const identity=await note();assert.equal(identity.definitionUuid,'sgrape.builtin.comment');assert.ok(identity.revisionHash);assert.equal(await page.evaluate(()=>nodeTypeLabel(definition(current().nodes.find(n=>n.id==='note')))),'Note');
    assert.equal(await control('noteTitleOnSelection').count(),1);assert.equal(await control('noteTransparent').count(),0);assert.equal(await control('noteTitleOnSelection').getAttribute('aria-pressed'),'false');assert.equal(await card().locator('[data-note-color="note"]').count(),1);
    assert.equal(await page.locator('[data-node="value"] [data-note-appearance]').count(),0);assert.equal(await title().isVisible(),true);
    const standard=await card().evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,shadow:s.boxShadow};});assert.notEqual(standard.background,'rgba(0, 0, 0, 0)');assert.notEqual(standard.shadow,'none');
    await select([]);assert.equal(await title().isVisible(),true);await select(['note']);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('Note is a UI label over the unchanged comment UUID/revision; defaults retain normal title/body and ordinary nodes have no appearance controls');

    for(const key of ['noteTitleOnSelection','noteTransparent']){
      await reset();const before=await graphJSON(),count=await history(),positions=(await note()).ui;if(key==='noteTransparent')await transparent();else await control(key).click();await settle();assert.equal((await note()).ui[key],true);if(key!=='noteTransparent')assert.equal(await control(key).getAttribute('aria-pressed'),'true');assert.equal(await history(),count+1);assert.equal((await note()).ui.x,positions.x);assert.equal((await note()).ui.y,positions.y);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);const after=await graphJSON();
      await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),before);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),after);assert.equal((await note()).revisionHash,identity.revisionHash);
    }checks.push('title-mode click and palette transparency selection each changes only metadata in one exact Undo/Redo, never moves the note or changes its shader identity');


    await reset();const beforeColor=await graphJSON(),titleColor=await title().evaluate(e=>getComputedStyle(e).backgroundColor);await card().locator('[data-note-color="note"]').click();await page.locator('[data-frame-color-preset="#485f8d"]').click();await settle();assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await history(),1);assert.equal(await title().evaluate(e=>getComputedStyle(e).backgroundColor),titleColor);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);const afterColor=await graphJSON(),bodyColor=await card().evaluate(e=>getComputedStyle(e).backgroundColor);assert.notEqual(bodyColor,'rgba(0, 0, 0, 0)');
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeColor);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),afterColor);await transparent();assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await card().evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');const restoreHistory=await history();await preset('#485f8d');assert.equal((await note()).ui.noteTransparent===true,false);assert.equal(await history(),restoreHistory+1);assert.equal(await card().evaluate(e=>getComputedStyle(e).backgroundColor),bodyColor);assert.equal(await title().evaluate(e=>getComputedStyle(e).backgroundColor),titleColor);checks.push('Note body preset color commits one exact Undo/Redo, keeps title color and shader unchanged, and transparency retains/restores the chosen body color');

    const surface=()=>card().evaluate(e=>{const result={};for(const [name,target]of [['card',e],['body',e.querySelector('.comment-node-canvas-content')]])for(const pseudo of [null,'::before','::after']){const s=getComputedStyle(target,pseudo);result[name+(pseudo||'')]={background:s.backgroundColor,image:s.backgroundImage};}return result;});
    for(const theme of ['dark','light'])for(const mode of ['colored','transparent']){
      await reset();await page.evaluate(theme=>setUIAppearance('theme',theme),theme);await settle();const originalSurface=await surface(),originalTitle=await title().evaluate(e=>getComputedStyle(e).backgroundColor),originalShape=await shape();
      await card().locator('[data-note-color="note"]').click();assert.equal(await page.locator('[data-note-color-default]').getAttribute('aria-checked'),'true');assert.equal(await page.locator('[data-frame-color-preset][aria-checked="true"]').count(),0);await page.locator('[data-frame-color-preset="#485f8d"]').click();await settle();if(mode==='transparent')await transparent();
      const beforeDefault=await graphJSON(),defaultHistory=await history();await card().locator('[data-note-color="note"]').click();assert.equal(await page.locator('[data-note-color-default]').getAttribute('aria-checked'),'false');await page.locator('[data-note-color-default]').click();await settle();
      const restored=await note();assert.equal(Object.hasOwn(restored.ui,'noteColor'),false);assert.equal(Object.hasOwn(restored.ui,'noteTransparent'),false);assert.equal(await history(),defaultHistory+1);assert.deepEqual(await surface(),originalSurface);assert.equal(await title().evaluate(e=>getComputedStyle(e).backgroundColor),originalTitle);sameBody(originalShape,await shape());assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
      const afterDefault=await graphJSON();await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeDefault);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),afterDefault);assert.deepEqual(await surface(),originalSurface);
      await card().locator('[data-note-color="note"]').click();assert.equal(await page.locator('[data-note-color-default]').getAttribute('aria-checked'),'true');assert.equal(await page.locator('[data-frame-color-preset][aria-checked="true"]').count(),0);await page.screenshot({path:path.join(folder,'note-default-'+theme+'-'+mode+'.png')});await page.keyboard.press('Escape');
    }checks.push('Default from a chosen color or transparency deletes both overrides in one exact Undo/Redo, restores the original dynamic body in both themes, and never changes geometry/title/shader');

    for(const theme of ['dark','light']){
      await reset();await page.evaluate(theme=>setUIAppearance('theme',theme),theme);await settle();const originalShape=await shape(),storedHeight=(await note()).ui.height,normalRadius=await card().evaluate(e=>getComputedStyle(e).borderTopLeftRadius);assert.equal(originalShape.card.height,storedHeight);await page.screenshot({path:path.join(folder,'note-title-normal-'+theme+'.png')});
      await control('noteTitleOnSelection').click();await settle();const selectedShape=await shape();sameCard(originalShape,selectedShape);assert.ok(Math.abs(selectedShape.preview.y-originalShape.preview.y)<.2);assert.equal((await note()).ui.height,storedHeight);assert.equal(await title().isVisible(),true);assert.ok(Math.abs(selectedShape.title.y-originalShape.title.y)<.2,'selected title stays at its original top');assert.ok(selectedShape.title.y<selectedShape.card.y,'title floats above the body bounds');assert.ok(selectedShape.title.y+selectedShape.title.height<=selectedShape.preview.y+1);
      await page.screenshot({path:path.join(folder,'note-title-selected-'+theme+'.png')});await select([]);await page.mouse.move(1550,1000);const unselectedShape=await shape();sameBody(originalShape,unselectedShape);assert.equal(await title().isVisible(),false);assert.equal(await card().evaluate(e=>getComputedStyle(e).borderTopLeftRadius),normalRadius);await preview().hover();assert.equal(await title().isVisible(),false,'hover does not reveal the title');await page.screenshot({path:path.join(folder,'note-title-hidden-'+theme+'.png')});
      await preview().click();await settle();assert.equal(await page.evaluate(()=>selected),'note');sameCard(originalShape,await shape());assert.equal(await title().isVisible(),true);assert.equal(await history(),1);assert.equal((await note()).ui.height,storedHeight);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
      await control('noteTitleOnSelection').click();await settle();sameBody(originalShape,await shape());assert.equal((await note()).ui.height,storedHeight);
    }checks.push('floating title visibility never changes the body or reading area position/size in either theme; hover never reveals a selection-only title');

    for(const theme of ['dark','light']){
      await reset({noteTransparent:true,noteTitleOnSelection:true});await page.evaluate(theme=>setUIAppearance('theme',theme),theme);await select([]);await page.mouse.move(1550,1000);const transparent=await card().evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,border:s.borderTopColor,shadow:s.boxShadow};});assert.equal(transparent.background,'rgba(0, 0, 0, 0)');assert.ok(transparent.border==='rgba(0, 0, 0, 0)'||transparent.border==='transparent');assert.equal(transparent.shadow,'none');
      for(const style of ['professional','excellent','godlike']){
        await page.evaluate(style=>setUIExperiments({uiStyle:style}),style);await settle();await page.mouse.move(1550,1000);
        const painted=await card().evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,image:s.backgroundImage,border:s.borderTopColor,shadow:s.boxShadow};});
        assert.equal(painted.background,'rgba(0, 0, 0, 0)',theme+' '+style+' hidden transparent body background');assert.equal(painted.image,'none');assert.ok(painted.border==='rgba(0, 0, 0, 0)'||painted.border==='transparent',theme+' '+style+' hidden transparent body border');assert.equal(painted.shadow,'none',theme+' '+style+' hidden transparent body shadow');
      }
      await page.evaluate(()=>setUIExperiments({uiStyle:'professional'}));await preview().hover();await settle();assert.notEqual(await card().evaluate(e=>getComputedStyle(e).borderTopColor),'rgba(0, 0, 0, 0)','transparent Note retains transient hover feedback');await page.mouse.move(1550,1000);await settle();assert.equal(await card().evaluate(e=>getComputedStyle(e).borderTopColor),'rgba(0, 0, 0, 0)','transparent Note removes hover feedback when pointer leaves');await preview().click();await settle();const selectedFeedback=await card().evaluate(e=>{const s=getComputedStyle(e);return{border:s.borderTopColor,shadow:s.boxShadow};});assert.ok(selectedFeedback.border!=='rgba(0, 0, 0, 0)'||selectedFeedback.shadow!=='none','selected transparent Note retains selection feedback');
      await preview().dblclick();await settle();assert.equal(await entry().isVisible(),true);assert.notEqual(await entry().evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');await entry().fill('Temporary appearance draft');await entry().press('Escape');await settle();assert.equal(await history(),0);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
      await page.screenshot({path:path.join(folder,'note-transparent-'+theme+'.png')});
      await page.evaluate(()=>{document.activeElement?.blur();const first=current().nodes.find(n=>n.id==='note'),second=clone(first);second.id='note_two';second.name='Second_note';second.ui.x=first.ui.x+480;second.ui.comment='# Second note\n\nTransparent body.';current().nodes=[first,second];current().edges=[];selection.clear();selected=null;render();});await page.mouse.move(1550,1000);await settle();const idleBodies=await page.locator('.node[data-category="annotation"]').evaluateAll(elements=>elements.map(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,border:s.borderTopColor,shadow:s.boxShadow};}));assert.equal(idleBodies.length,2);for(const painted of idleBodies){assert.equal(painted.background,'rgba(0, 0, 0, 0)');assert.equal(painted.border,'rgba(0, 0, 0, 0)');assert.equal(painted.shadow,'none');}await page.screenshot({path:path.join(folder,'notes-idle-transparent-'+theme+'.png')});
    }checks.push('transparent notes lose idle canvas background/border/shadow in dark and light, while double-click editing keeps a visible input background and Escape preserves text/history');

    await reset({noteTitleOnSelection:true,noteTransparent:true});const beforeBody=await note(),beforePan=await page.evaluate(()=>({...pan})),bodyBox=await body().boundingBox();await drag({x:bodyBox.x+5,y:bodyBox.y+bodyBox.height-8},65,35);assert.equal((await note()).ui.x,beforeBody.ui.x);assert.equal((await note()).ui.y,beforeBody.ui.y);assert.equal(await history(),0);assert.deepEqual(await page.evaluate(()=>({...pan})),beforePan);
    await select(['note']);const beforeDrag=await graphJSON(),start=await note();await drag(await titlePoint(),48,24);const moved=await note();assert.equal(moved.ui.x,start.ui.x+48);assert.equal(moved.ui.y,start.ui.y+24);assert.equal(await history(),1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeDrag);
    const buttonBox=await control('noteTitleOnSelection').boundingBox(),buttonBefore=await note();await drag({x:buttonBox.x+buttonBox.width/2,y:buttonBox.y+buttonBox.height/2},40,15);assert.equal((await note()).ui.x,buttonBefore.ui.x);assert.equal((await note()).ui.y,buttonBefore.ui.y);checks.push('note body cannot drag or pan despite body-drag preference; title drags once with Undo; appearance-button pointer gestures never drag the card');

    await reset({noteTitleOnSelection:true,noteTransparent:true});await card().locator('[data-collapse-node]').click();await settle();await select([]);assert.equal(await card().evaluate(e=>e.classList.contains('collapsed')),true);assert.equal(await title().isVisible(),true);assert.equal(await preview().count(),0);await card().locator('[data-collapse-node]').click();await settle();assert.equal(await card().evaluate(e=>e.classList.contains('collapsed')),false);assert.equal(await preview().isVisible(),true);assert.equal((await note()).ui.noteTitleOnSelection,true);assert.equal((await note()).ui.noteTransparent,true);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('collapsed notes always retain a usable title/expand control and expanding preserves both appearance flags');

    await reset({noteTitleOnSelection:true,noteTransparent:true,noteColor:'#485f8d',noteFontScale:2});const persisted=await page.evaluate(()=>{const raw=JSON.stringify(graph);graph=JSON.parse(raw);render();const payload=GraphClipboard.decode(GraphClipboard.encode(graph,current(),['note'],shaderId));let ids;change(()=>{ids=GraphClipboard.paste(graph,current(),payload,{source:shaderId,stage,target:editorTarget,catalog,types:numericTypes(),anchor:{x:650,y:580}});});return{original:clone(current().nodes.find(n=>n.id==='note')),copy:clone(current().nodes.find(n=>ids.includes(n.id)))};});
    for(const n of [persisted.original,persisted.copy]){assert.equal(n.ui.noteTitleOnSelection,true);assert.equal(n.ui.noteTransparent,true);assert.equal(n.ui.noteColor,'#485f8d');assert.equal(n.ui.noteFontScale,2);assert.equal(n.definitionUuid,identity.definitionUuid);assert.equal(n.revisionHash,identity.revisionHash);}assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('JSON roundtrip and real clipboard model copy preserve both appearance flags without changing definition or shader content');

    await reset();await page.evaluate(()=>{readonly=true;render();});assert.equal(await control('noteTitleOnSelection').isDisabled(),true);assert.equal(await card().locator('[data-note-color]').isDisabled(),true);const beforeReadonly=await graphJSON();await control('noteTitleOnSelection').evaluate(e=>e.click());assert.equal(await graphJSON(),beforeReadonly);assert.equal(await history(),0);checks.push('readonly disables appearance controls and programmatic button activation cannot mutate graph/history');


    await reset();await page.evaluate(()=>setGraphFocus(false));await settle();assert.equal(await page.locator('#inspector .comment-node-parameter [data-comment-node]').isVisible(),true);assert.equal(await page.locator('#inspector [data-note-title-setting],[data-note-color-setting]').count(),0);await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();await settle();
    const setting=()=>page.locator('#inspector [data-note-title-setting="note"]'),settingColor=()=>page.locator('#inspector [data-note-color="note"][data-note-color-setting]'),settingValue=()=>page.locator('#inspector .note-setting-color-value');
    assert.equal(await setting().isChecked(),false);assert.equal(await settingColor().count(),1);const beforeSetting=await graphJSON();await setting().check();await settle();assert.equal((await note()).ui.noteTitleOnSelection,true);assert.equal(await history(),1);assert.equal(await control('noteTitleOnSelection').getAttribute('aria-pressed'),'true');const afterSetting=await graphJSON();
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeSetting);assert.equal(await setting().isChecked(),false);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),afterSetting);assert.equal(await setting().isChecked(),true);
    await settingColor().click();await page.locator('[data-frame-color-preset="#485f8d"]').click();await settle();assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await history(),2);assert.equal((await settingValue().innerText()).toLowerCase(),'#485f8d');
    await card().locator('[data-note-color="note"]').click();await page.locator('[data-note-color-transparent]').click();await settle();assert.equal((await note()).ui.noteTransparent,true);assert.equal(await settingValue().innerText(),await page.evaluate(()=>t('note.transparent')));assert.equal(await history(),3);
    await settingColor().click();await page.locator('[data-note-color-default]').click();await settle();assert.equal(Object.hasOwn((await note()).ui,'noteColor'),false);assert.equal(Object.hasOwn((await note()).ui,'noteTransparent'),false);assert.equal(await settingValue().innerText(),await page.evaluate(()=>t('note.defaultColor')));assert.equal(await history(),4);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    await page.screenshot({path:path.join(folder,'note-settings.png')});await page.locator('#inspector').getByRole('tab',{name:/^(參數|Parameters)$/}).click();assert.equal(await page.locator('#inspector .comment-node-parameter [data-comment-node]').isVisible(),true);assert.equal(await page.locator('#inspector .comment-node-parameter [data-comment-node]').inputValue(),(await note()).ui.comment);assert.equal(await page.locator('#inspector [data-note-title-setting],[data-note-color-setting]').count(),0);await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();await page.evaluate(()=>{readonly=true;render();});assert.equal(await setting().isDisabled(),true);assert.equal(await settingColor().isDisabled(),true);const readonlySettings=await graphJSON();await setting().evaluate(e=>e.click());await settingColor().evaluate(e=>e.click());assert.equal(await graphJSON(),readonlySettings);
    await page.evaluate(()=>{readonly=false;selection=new Set(['value']);selected='value';render();});assert.equal(await page.locator('#inspector [data-note-title-setting],[data-note-color-setting]').count(),0);checks.push('Settings checkbox and shared color palette mirror canvas controls, each commit once with Undo/Redo, update labels, block readonly, and stay absent on ordinary nodes');


    await reset();await page.evaluate(()=>setGraphFocus(false));await settle();const baseCanvasFont=await preview().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),baseTitleFont=await title().evaluate(e=>getComputedStyle(e).fontSize),baseParameterFont=await page.locator('#inspector .comment-node-parameter [data-comment-node]').evaluate(e=>getComputedStyle(e).fontSize),storedFontHeight=(await note()).ui.height;
    await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();const fontScale=()=>page.locator('#inspector [data-note-font-scale="note"]');assert.equal(await fontScale().inputValue(),'1');assert.equal(await fontScale().getAttribute('min'),'1');assert.equal(await fontScale().getAttribute('max'),'10');const beforeFont=await graphJSON();
    await fontScale().fill('2');await fontScale().press('Enter');await settle();assert.equal((await note()).ui.noteFontScale,2);assert.equal(await history(),1);assert.equal(await preview().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),baseCanvasFont*2);assert.equal(await title().evaluate(e=>getComputedStyle(e).fontSize),baseTitleFont);assert.equal((await note()).ui.height,storedFontHeight);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);const doubledFont=await graphJSON();
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeFont);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),doubledFont);
    await page.locator('#inspector').getByRole('tab',{name:/^(參數|Parameters)$/}).click();assert.equal(await page.locator('#inspector .comment-node-parameter [data-comment-node]').evaluate(e=>getComputedStyle(e).fontSize),baseParameterFont);await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();
    await fontScale().fill('10');await fontScale().press('Enter');await settle();assert.equal((await note()).ui.noteFontScale,10);assert.equal(await preview().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),baseCanvasFont*10);assert.equal(await title().evaluate(e=>getComputedStyle(e).fontSize),baseTitleFont);assert.equal((await note()).ui.height,storedFontHeight);const maxFontHistory=await history();await fontScale().fill('11');await fontScale().press('Enter');await settle();assert.equal((await note()).ui.noteFontScale,10);assert.equal(await fontScale().inputValue(),'10');assert.equal(await history(),maxFontHistory,'clamping back to unchanged maximum is a no-op');
    await fontScale().fill('0');await fontScale().press('Enter');await settle();assert.equal(Object.hasOwn((await note()).ui,'noteFontScale'),false);assert.equal(await fontScale().inputValue(),'1');assert.equal(await preview().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),baseCanvasFont);assert.equal((await note()).ui.height,storedFontHeight);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    await fontScale().fill('2');await fontScale().press('Enter');await settle();await page.screenshot({path:path.join(folder,'note-font-scale.png')});await page.evaluate(()=>{graph=JSON.parse(JSON.stringify(graph));render();});assert.equal((await note()).ui.noteFontScale,2);assert.equal(await preview().evaluate(e=>parseFloat(getComputedStyle(e).fontSize)),baseCanvasFont*2);await page.evaluate(()=>{readonly=true;render();});assert.equal(await fontScale().isDisabled(),true);checks.push('Font scale 1–10 changes only canvas body text, clamps typed values, preserves title/Parameter fonts and stored height, survives JSON/clipboard, and uses shader-neutral Undo with readonly protection');


    await reset();await page.evaluate(()=>setGraphFocus(false));await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();await settle();
    const scrubEntry=()=>page.locator('#inspector [data-note-font-scale="note"]'),scrubStart=async()=>{await scrubEntry().blur();const r=await scrubEntry().boundingBox(),p={x:r.x+8,y:r.y+r.height/2,width:r.width};await page.mouse.move(p.x,p.y);await page.mouse.down();return p;};
    const scrubOriginal=await graphJSON(),firstScrub=await scrubStart();await page.mouse.move(firstScrub.x+firstScrub.width/2,firstScrub.y,{steps:5});await settle();assert.ok(Math.abs(Number(await scrubEntry().inputValue())-5.5)<=.1);assert.equal(await graphJSON(),scrubOriginal);assert.equal(await history(),0);await page.mouse.up();await settle();assert.ok(Math.abs((await note()).ui.noteFontScale-5.5)<=.1);assert.equal(await history(),1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    const atHalf=await graphJSON(),boundedStart=await scrubStart();await page.mouse.move(boundedStart.x+boundedStart.width,boundedStart.y,{steps:5});assert.equal(Number(await scrubEntry().inputValue()),10);await page.mouse.move(boundedStart.x+boundedStart.width*.9,boundedStart.y,{steps:2});assert.ok(Number(await scrubEntry().inputValue())<10&&Number(await scrubEntry().inputValue())>=1,'reverse motion immediately leaves the upper clamp');assert.equal(await graphJSON(),atHalf);await page.mouse.up();await settle();assert.equal(await history(),2);assert.ok((await note()).ui.noteFontScale>=1&&(await note()).ui.noteFontScale<=10);
    const beforeCancel=await graphJSON(),cancelHistory=await history(),cancelValue=(await note()).ui.noteFontScale,cancelStart=await scrubStart();await page.mouse.move(cancelStart.x-cancelStart.width*.5,cancelStart.y,{steps:5});assert.notEqual(Number(await scrubEntry().inputValue()),cancelValue);await page.keyboard.press('Escape');await page.mouse.up();await settle();assert.equal(await graphJSON(),beforeCancel);assert.equal(await history(),cancelHistory);assert.equal(Number(await scrubEntry().inputValue()),cancelValue);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),atHalf);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),beforeCancel);checks.push('Actual pointer Font scrubbing maps half-width to about 5.5, clamps within 1–10, immediately reverses from the clamp, commits one Undo, and Escape cancels without history or shader changes');

    await reset({width:190,height:1,comment:'X',noteTitleOnSelection:true});await page.evaluate(()=>setGraphFocus(false));await page.locator('#inspector').getByRole('tab',{name:/^(設定|Settings)$/}).click();await settle();
    const compactFont=()=>page.locator('#inspector [data-note-font-scale="note"]'),firstLine=()=>preview().locator('.comment-markdown>p').evaluate(e=>parseFloat(getComputedStyle(e).lineHeight));
    const baseCompactShape=await shape(),baseCompactLine=await firstLine(),baseCompactGraph=await graphJSON(),compactTitleFont=await title().evaluate(e=>getComputedStyle(e).fontSize);
    for(const value of [4,10]){await compactFont().fill(String(value));await compactFont().press('Enter');await settle();const scaledShape=await shape(),expectedGrowth=await firstLine()-baseCompactLine;assert.ok(Math.abs(scaledShape.card.height-baseCompactShape.card.height-expectedGrowth)<1.1,'minimum follows paragraph line-height instead of an H1 estimate');assert.equal((await note()).ui.height,1);assert.equal(await title().evaluate(e=>getComputedStyle(e).fontSize),compactTitleFont);await select([]);sameBody(scaledShape,await shape());await select(['note']);sameBody(scaledShape,await shape());assert.equal(await page.evaluate(()=>hasShaderChanges()),false);}
    const atTenShape=await shape(),atTenGraph=await graphJSON(),fontHistory=await history();await page.locator('#undo').click();await settle();assert.equal((await note()).ui.noteFontScale,4);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),atTenGraph);sameBody(atTenShape,await shape());assert.equal(await history(),fontHistory);
    await page.evaluate(()=>{document.activeElement?.blur();graph=JSON.parse(JSON.stringify(graph));render();});await settle();sameBody(atTenShape,await shape());assert.equal((await note()).ui.height,1);await page.screenshot({path:path.join(folder,'note-font-compact-10.png')});
    await compactFont().fill('1');await compactFont().press('Enter');await settle();assert.equal(await graphJSON(),baseCompactGraph);sameBody(baseCompactShape,await shape());assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('Font-scale edits resize a tiny stored paragraph only by its actual line-height, retain title/selection geometry and stored dimensions, and restore exact layouts through Undo/Redo and JSON');

    await reset({width:190,noteTitleOnSelection:true});await page.evaluate(()=>{if(!customNodeNamesEnabled())$('#customnames').click();render();});await settle();assert.equal(await title().locator('.node-function-title').innerText(),'Lighting_notes');assert.equal(await title().locator('.node-prototype').innerText(),'Note');
    const arrangement=await title().evaluate(e=>{const rect=e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom};};return{title:rect(e),name:rect(e.querySelector('.node-title-text')),subtype:rect(e.querySelector('.node-prototype')),controls:[...e.querySelectorAll('[data-note-appearance],[data-note-color]')].map(rect),width:e.clientWidth,scroll:e.scrollWidth};});
    assert.ok(arrangement.scroll<=arrangement.width+1);assert.ok(arrangement.name.right<=arrangement.subtype.left+1);assert.ok(arrangement.subtype.right<=arrangement.controls[0].left+1);assert.ok(arrangement.controls.at(-1).right<=arrangement.title.right+1);await page.screenshot({path:path.join(folder,'note-190-custom-name.png')});checks.push('at 190px width the custom name stays left, muted Note subtype follows, and both controls fit on the right without overflow');

    await reset({noteTitleOnSelection:true});await select([]);await preview().tap();await settle();assert.equal(await title().isVisible(),true);const beforeTouch=await history();await card().locator('[data-note-color="note"]').tap();await page.locator('[data-note-color-transparent]').tap();await settle();assert.equal((await note()).ui.noteTransparent,true);assert.equal(await history(),beforeTouch+1);await card().locator('[data-note-color="note"]').click();assert.equal(await page.locator('[data-note-color-transparent]').getAttribute('aria-checked'),'true');await page.locator('[data-frame-color-preset="#485f8d"]').focus();await page.keyboard.press('Space');await settle();assert.equal((await note()).ui.noteTransparent===true,false);assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await history(),beforeTouch+2);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('touch body selection reveals controls; touch and keyboard Space activate appearance controls without shader changes');
    await reset({noteTitleOnSelection:true,noteTransparent:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{scale=.7;pan={x:-55,y:75};transform();});await settle();await page.screenshot({path:path.join(folder,'note-narrow.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'note-appearance-graph.json'),await graphJSON());await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);throw error;}
}
run().catch(error=>{console.error(error);process.exitCode=1;});
