const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
(async()=>{const[source,state,folder]=process.argv.slice(2),h=await harness(source,state,folder,{skipPreview:true}),{page,checks,errors,at,drag,settle}=h;try{
 await page.selectOption('#language','en');
 await page.evaluate(()=>{nativeSourcePolling=uniformPolling=customPolling=true;uniformLive.disconnect();uniformLive.connect=()=>{};clearTimeout(autoTimer);scheduleGraphApply=()=>{};readonly=dirty=connectionInterrupted=false;graph.functions=[];graph.declarations=[];stage='pixel';graphTrail=[];past=[];future=[];selection.clear();selected=null;graph.stages.pixel={nodes:[testNode('pixel','pixel_out',760,230),testNode('src','vector',20,220,{type:'vec3'}),...Array.from({length:5},(_,i)=>testNode('dst'+i,'normalize',520,i*115,{type:'vec3'}))],edges:[]};scale=.9;pan={x:30,y:60};render();const r=$('#canvas').getBoundingClientRect();openCreator(r.left+300,r.top+300);});
 await page.locator('#createsearch').fill('Router');await page.locator('[data-create-entry="router"]').click();
 const id=await page.evaluate(()=>selected);
 await page.evaluate(id=>change(()=>{const n=current().nodes.find(n=>n.id===id);n.ui.x=340;n.ui.y=240;},{layout:true}),id);
 const card=()=>page.locator(`[data-node="${id}"]`);
 assert.equal(await card().locator('.router-dot').count(),1);assert.equal(await card().locator('.node-title,.node-resize-handle').count(),0);
 await drag(await at('[data-node="src"] .port[data-kind="outputs"]'),await at(`[data-node="${id}"] .router-dot`));
 assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).params.type,id),'vec3');
 await card().locator('.router-dot').click();await page.locator('[data-node="dst0"] .port[data-kind="inputs"]').click();
 assert.equal(await page.evaluate(()=>current().edges.length),2);
 checks.push('Creator, unnamed compact node, incoming drag and outgoing click on the same single socket; type follows vec3 source');
 for(let i=1;i<5;i++)await page.evaluate(({id,i})=>{const ok=connectPorts({node:id,kind:'outputs',port:'out'},{node:'dst'+i,kind:'inputs',port:'value'});if(!ok)throw Error('Connection rejected');},{id,i});
 assert.equal(await card().locator('.router-dot').count(),10);assert.equal(await card().locator('.router-output-dot').count(),4);assert.equal(await card().locator('.router-hollow').count(),1);
 const geometry=await page.evaluate(id=>{const n=current().nodes.find(n=>n.id===id),edges=current().edges.filter(e=>e.from[0]===id);return edges.map(e=>point(n,'out','outputs',e).y);},id);
 assert.equal(geometry[0],geometry[1]);assert(geometry[1]<geometry[2]&&geometry[2]<geometry[3]&&geometry[3]<geometry[4]);
 const sizes=await card().locator('.router-dot').evaluateAll(es=>es.map(e=>({w:e.offsetWidth,h:e.offsetHeight})));assert(sizes.every(s=>s.w===11&&s.h===11));
 checks.push('Five targets retain all edges while sharing four output positions; 10 dots, only the first tier hollow, native 11px sockets and 3px edge gap');
 const before=await page.evaluate(()=>clone(graph)),history=await page.evaluate(()=>past.length);
 const a=await at('[data-node="dst0"] .node-title');await drag(a,{x:a.x+40,y:a.y+330});
 const reordered=await page.evaluate(id=>{const n=current().nodes.find(n=>n.id===id);return current().edges.filter(e=>e.from[0]===id).map(e=>[e.to[0],point(n,'out','outputs',e).y]);},id);
 assert(reordered.find(e=>e[0]==='dst0')[1]>reordered.find(e=>e[0]==='dst1')[1]);
 assert.equal(await page.evaluate(()=>past.length),history+1);await page.evaluate(()=>undo());assert.deepEqual(await page.evaluate(()=>graph),before);await page.evaluate(()=>undo(true));
 checks.push('Moving targets changes output assignment by screen height; one layout Undo restores graph and routing');
 await page.evaluate(()=>{selection.clear();selected=null;refreshCanvasSelection();});await page.mouse.move(10,10);
 assert.equal(await card().locator('.router-drag-handle').evaluate(e=>getComputedStyle(e).opacity),'0');
 await card().hover();assert.equal(await card().locator('.router-drag-handle').evaluate(e=>getComputedStyle(e).opacity),'1');
 const layoutBefore=await page.evaluate(()=>clone(graph)),historyBefore=await page.evaluate(()=>past.length),handle=await at(`[data-node="${id}"] .router-drag-handle`);
 await drag(handle,{x:handle.x+43,y:handle.y+33});
 assert.notEqual(await page.evaluate(id=>current().nodes.find(n=>n.id===id).ui.x,id),340);
 assert.equal(await page.evaluate(()=>past.length),historyBefore+1);assert.equal(await page.evaluate(()=>linkStart),null);
 await page.mouse.move(10,10);assert.equal(await card().locator('.router-drag-handle').evaluate(e=>getComputedStyle(e).opacity),'1');
 await page.evaluate(()=>positionSelectionToolbar());
 const clearHandle=await page.evaluate(id=>{const h=document.querySelector(`[data-node="${id}"] .router-drag-handle`).getBoundingClientRect(),b=document.querySelector('#selectiontoolbar').getBoundingClientRect();return b.bottom<=h.top||b.top>=h.bottom||b.right<=h.left||b.left>=h.right;},id);assert(clearHandle,'Selection toolbar covers Router drag handle');
 await page.evaluate(()=>undo());assert.deepEqual(await page.evaluate(()=>graph),layoutBefore);await page.evaluate(()=>undo(true));
 checks.push('Hover reveals a usable title handle, selection keeps it visible, real drag moves Router without starting a wire and supports one-step Undo/Redo');
 await page.evaluate(id=>{const edges=current().edges.filter(e=>e.from[0]===id);setEdgeStyles([edges[1]],'link');setEdgeStyles(current().edges.filter(e=>e.to[0]===id),'link');showLinkLines=false;wires();},id);
 assert.equal(await page.locator('#wires .wire-link').count(),0);assert.equal(await card().locator('.link-port-navigation').count(),2);
 const gaps=await page.evaluate(id=>{
   const r=document.querySelector(`[data-node="${id}"]`),input=r.querySelector('[data-link-kind="inputs"]').getBoundingClientRect(),output=r.querySelector('[data-link-kind="outputs"]').getBoundingClientRect(),left=r.querySelector('.router-hollow').getBoundingClientRect(),right=r.querySelector('.router-output-dot').getBoundingClientRect();
   const row=document.querySelector('[data-node="src"] .port-row.output'),normal=row.querySelector('.port').getBoundingClientRect(),arrow=row.querySelector('.link-port-navigation').getBoundingClientRect();
   return {input:left.left-input.right,output:output.left-right.right,normal:arrow.left-normal.right};
 },id);assert(Math.abs(gaps.input-gaps.normal)<.1,JSON.stringify(gaps));assert(Math.abs(gaps.output-gaps.normal)<.1,JSON.stringify(gaps));
 await card().locator('[data-link-kind="outputs"]').click();assert.deepEqual(await page.evaluate(()=>[...selection]),['dst1']);
 await page.evaluate(()=>showLinkLines=true);await page.evaluate(()=>wires());assert.equal(await page.locator('#wires .wire-link').count(),2);
 checks.push('Router moves as a real node; separate incoming/outgoing Wire and Link styles, hidden-Link navigation and visible Link endpoints');
 await page.evaluate(id=>{const before=current().edges.length;const ok=connectPorts({node:'dst1',kind:'outputs',port:'out'},{node:id,kind:'inputs',port:'value'});if(ok||before!==current().edges.length)throw Error('Cycle accepted');},id);
 const saved=await page.evaluate(()=>JSON.stringify(graph));await page.evaluate(raw=>{graph=JSON.parse(raw);render();},saved);assert.equal(await card().locator('.router-dot').count(),10);
 await page.evaluate(id=>{selection=new Set([id]);selected=id;remove();},id);assert.equal(await card().count(),0);await page.evaluate(()=>undo());assert.equal(await card().locator('.router-dot').count(),10);
 checks.push('Cycle rejection, serialized reload and deletion/Undo preserve actual Router nodes and edges');
 await page.evaluate(()=>{showLinkLines=true;wires();});await page.screenshot({path:path.join(folder,'router-dark.png')});
 await page.evaluate(()=>{document.documentElement.dataset.uiTheme='light';});await page.screenshot({path:path.join(folder,'router-light.png')});
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'graph.json'),await page.evaluate(()=>JSON.stringify(graph)));await h.finish();console.log(JSON.stringify({passed:true,checks}));
}catch(e){await h.finish(e);throw e;}})().catch(e=>{console.error(e.stack);process.exitCode=1});
