// Actual Chromium middle-pointer gestures with an isolated Shader service fixture.
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const [source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8').replace(/^\uFEFF/,''));
let state=structuredClone(original),applies=0,uniformWrites=0,external=false;const checks=[],errors=[];
const components=[1,1,1,1].map((value,i)=>({parameter:'Tint'+'xyzw'[i],value,mode:'CONSTANT',writable:true}));
const snapshot=()=>({revision:state.state.revision,uniforms:{uniform_tint:{type:'vec4',default:[1,1,1,1],components}},textures:{}});
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost');res.setHeader('Cache-Control','no-store');
  if(url.pathname.startsWith('/api/')){
    res.setHeader('Content-Type','application/json');const operation=url.pathname.split('/').at(-1);let text='';for await(const chunk of req)text+=chunk;const body=text?JSON.parse(text):null;
    if(operation==='state')return res.end(JSON.stringify(state));
    if(operation==='uniforms')return res.end(JSON.stringify(snapshot()));
    if(operation==='uniform-value'){
      uniformWrites++;const item=components[body.component];if(external||!item.writable||body.expected.value!==item.value){res.statusCode=409;return res.end('{"error":"TD value changed; preserved"}');}
      item.value=body.value;return res.end(JSON.stringify(snapshot()));
    }
    if(operation==='apply'){applies++;state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}
    if(operation==='preview'){res.setHeader('Content-Type','image/png');return res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a8xkAAAAASUVORK5CYII=','base64'));}
    res.statusCode=404;return res.end('{}');
  }
  const file=url.pathname.startsWith('/shader/')?'index.html':url.pathname.slice(1);if(!/^[a-z0-9_.-]+$/i.test(file)){res.statusCode=404;return res.end();}
  const target=overlay&&fs.existsSync(path.join(overlay,file))?path.join(overlay,file):path.join(source,file);
  if(!fs.existsSync(target)){res.statusCode=404;return res.end();}
  res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(target));
});
let browser;
(async()=>{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE});
  const page=await browser.newPage({viewport:{width:1600,height:1000}});page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:'+server.address().port+'/shader/'+'a'.repeat(32)+'/#fixture');await page.waitForFunction(()=>typeof graph!=='undefined'&&graph);
  await page.locator('[data-node="tint"] .node-title').click();await page.waitForFunction(()=>document.querySelector('#inspector .uniform-live input:not(:disabled)'));
  const defaults=()=>page.locator('#inspector > .components input').first(),live=()=>page.locator('#inspector .uniform-live input').first();
  const begin=async(locator=defaults())=>{await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await locator.evaluate(e=>e.scrollIntoView({block:'center',inline:'nearest'}));const r=await locator.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down({button:'middle'});try{await page.locator('#valueladder').waitFor({timeout:3000});}catch(error){console.log(await locator.evaluate(e=>({rect:e.getBoundingClientRect().toJSON(),value:e.value,disabled:e.disabled,readonly,dirty,active:e===document.activeElement,under:document.elementFromPoint(e.getBoundingClientRect().x+e.clientWidth/2,e.getBoundingClientRect().y+e.clientHeight/2)?.outerHTML?.slice(0,200)})));await page.screenshot({path:path.join(folder,'failed.png')});throw error;}return {x:r.x+r.width/2,y:r.y+r.height/2};};
  const rung=async(step,x)=>{const r=await page.locator('[data-step="'+step+'"]').boundingBox();await page.mouse.move(x,r.y+r.height/2);return r.y+r.height/2;};
  const end=()=>page.mouse.up({button:'middle'}),value=()=>page.evaluate(()=>graph.declarations.find(d=>d.id==='uniform_tint').value[0]);
  const originalGraph=await page.evaluate(()=>JSON.stringify(graph));const history=await page.evaluate(()=>past.length);let p=await begin(),y=await rung(.1,p.x);
  for(let i=1;i<=20;i++)await page.mouse.move(p.x+i,y);
  assert.equal(Number(await defaults().inputValue()),1.2);assert.equal(await value(),1);await page.waitForTimeout(700);assert.equal(applies,0);assert.equal(uniformWrites,0);
  await page.screenshot({path:path.join(folder,'value-ladder.png')});checks.push('middle drag previews numeric field with no graph edits, compiles or Uniform writes during movement');
  await end();assert.equal(await value(),1.2);assert.equal(await page.evaluate(()=>past.length),history+1);await page.waitForFunction(()=>!dirty);assert.equal(applies,1);checks.push('release creates one graph Undo entry and one scheduled apply');
  await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),originalGraph);await page.waitForFunction(()=>!dirty);checks.push('one Undo restores the whole gesture');
  p=await begin();y=await rung(.1,p.x);await page.mouse.move(p.x+16,y);const small=Number(await defaults().inputValue());const y2=await rung(10,p.x+16);assert.equal(Number(await defaults().inputValue()),small);await page.mouse.move(p.x+24,y2);assert.equal(Number(await defaults().inputValue()),small+10);await page.keyboard.press('Escape');await end();assert.equal(await value(),1);assert.equal(Number(await defaults().inputValue()),1);checks.push('changing rung rebases horizontal motion without a value jump; Escape restores initial value');
  const cancellations=[['parameter scroll',()=>page.evaluate(()=>document.querySelector('#parameterbody').dispatchEvent(new Event('scroll')))],['window blur',()=>page.evaluate(()=>window.dispatchEvent(new Event('blur')))],['pointer cancellation',()=>page.evaluate(()=>valueLadder.entry.dispatchEvent(new PointerEvent('pointercancel',{pointerId:1,bubbles:true})))],['capture loss',()=>page.evaluate(()=>valueLadder.entry.releasePointerCapture(1))],['inspector rebuild',()=>page.evaluate(()=>inspector())],['disabled while dragging',()=>page.evaluate(()=>{valueLadder.entry.disabled=true;})],['keyboard Tab',()=>page.keyboard.press('Tab')],['resize',()=>page.setViewportSize({width:1500,height:900})]];
  for(const [name,cancel]of cancellations){await page.evaluate(()=>inspector());p=await begin();y=await rung(.01,p.x);await page.mouse.move(p.x+24,y);const past=await page.evaluate(()=>JSON.stringify({graph,past,future}));await cancel();await page.mouse.move(p.x+25,y);await page.waitForFunction(()=>!valueLadder);await end();assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future})),past);checks.push(name+' cancels without a history entry or draft edit');}
  await page.evaluate(()=>inspector());p=await begin();await end();assert.equal(await value(),1);checks.push('middle click without movement leaves the value unchanged');
  await defaults().fill('-0.0003');await defaults().press('Enter');await page.waitForFunction(()=>!dirty);p=await begin();y=await rung(.001,p.x);await page.mouse.move(p.x-8,y);await end();assert.equal(await value(),-.0013);await page.waitForFunction(()=>!dirty);checks.push('small negative values preserve precision and normal typed entry still works');
  await page.evaluate(()=>{readonly=true;render();});const disabled=defaults(),r=await disabled.boundingBox();await page.mouse.move(r.x+5,r.y+5);await page.mouse.down({button:'middle'});assert.equal(await page.locator('#valueladder').count(),0);await end();await page.evaluate(()=>{readonly=false;render();});checks.push('read-only graph fields never start a ladder');
  await page.evaluate(()=>{selected='filter';selection=new Set(['filter']);inspector();});const wired=page.locator('.input-parameter input:disabled').first();const wr=await wired.boundingBox();await page.mouse.move(wr.x+5,wr.y+5);await page.mouse.down({button:'middle'});assert.equal(await page.locator('#valueladder').count(),0);await end();checks.push('connected input defaults stay disabled');
  await page.evaluate(()=>{selected='tint';selection=new Set(['tint']);inspector();});await page.waitForFunction(()=>!document.querySelector('#inspector .uniform-live input').disabled);const graphBeforeLive=await page.evaluate(()=>JSON.stringify(graph)),writeBefore=uniformWrites;
  p=await begin(live());y=await rung(.1,p.x);await page.mouse.move(p.x+16,y);await page.waitForTimeout(700);assert.equal(uniformWrites,writeBefore);assert.equal(await live().inputValue(),'1.2');await end();await page.waitForFunction(()=>uniformPending.size===0);assert.equal(uniformWrites,writeBefore+1);assert.equal(components[0].value,1.2);assert.equal(await page.evaluate(()=>JSON.stringify(graph)),graphBeforeLive);checks.push('live Uniform uses one existing guarded parameter write and does not change its graph default');
  p=await begin(live());y=await rung(.1,p.x);await page.mouse.move(p.x+8,y);external=true;components[0].value=7;await end();await page.waitForFunction(()=>uniformPending.size===0);assert.equal(components[0].value,7);assert.ok((await page.locator('#status').innerText()).includes('preserved'));external=false;checks.push('external value race is rejected by existing compare-and-set write');
  components[0].mode='EXPRESSION';components[0].writable=false;await page.evaluate(()=>refreshUniforms());await page.waitForFunction(()=>document.querySelector('#inspector .uniform-live input').disabled);const lr=await live().boundingBox();await page.mouse.move(lr.x+5,lr.y+5);await page.mouse.down({button:'middle'});assert.equal(await page.locator('#valueladder').count(),0);await end();checks.push('Expression-driven live values stay read-only');
  await page.selectOption('#language','en');await page.locator('#livetoggle').click();await page.locator('#helptoggle').click();await page.setViewportSize({width:420,height:720});await page.locator('#toggledetails').click();p=await begin();const popup=await page.locator('#valueladder').boundingBox();assert.ok(popup.x>=0&&popup.y>=0&&popup.x+popup.width<=420&&popup.y+popup.height<=720);assert.ok((await defaults().getAttribute('title')).startsWith('Hold middle'));await page.screenshot({path:path.join(folder,'value-ladder-small.png')});await page.keyboard.press('Escape');await end();checks.push('localized tooltip and ladder fit a narrow viewport');
  await page.setViewportSize({width:1600,height:1000});await page.evaluate(()=>{enterFunction(graph.stages.pixel.nodes.find(n=>n.id==='filter'));selected='input';selection=new Set(['input']);inspector();});
  const functionBefore=await page.evaluate(()=>JSON.stringify(graph)),historyBefore=await page.evaluate(()=>past.length),portField=page.locator('#inspector .input-parameter input[type=number]').first();
  p=await begin(portField);y=await rung(.1,p.x);await page.mouse.move(p.x+8,y);await page.keyboard.press('Escape');await end();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),functionBefore);
  p=await begin(portField);y=await rung(.1,p.x);await page.mouse.move(p.x+8,y);await end();assert.equal(await page.evaluate(()=>currentFunction().scope),'local');assert.equal(await page.evaluate(()=>past.length),historyBefore+1);assert.equal(await page.evaluate(()=>currentFunction().inputs[0].default[0]),1.1);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),functionBefore);checks.push('library Function localizes only on release and one Undo restores the source reference');
  assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.body.classList.contains('scrubbing-value')),false);checks.push('no page errors or stuck gesture styling');
  fs.writeFileSync(path.join(folder,'ladder-browser-tests.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));
})().catch(e=>{console.error(e);fs.writeFileSync(path.join(folder,'ladder-browser-tests.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));process.exitCode=1;}).finally(async()=>{await browser?.close();server.close();});
