const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
(async()=>{const[source,state,folder]=process.argv.slice(2),h=await harness(source,state,folder,{skipPreview:true}),{page,checks,errors}=h;try{
 await page.selectOption('#language','en');
 await page.evaluate(()=>{nativeSourcePolling=uniformPolling=customPolling=true;uniformLive.disconnect();uniformLive.connect=()=>{};clearTimeout(autoTimer);scheduleGraphApply=()=>{};readonly=dirty=connectionInterrupted=false;graph.functions=[];graph.declarations=[];stage='pixel';graphTrail=[];past=[];future=[];graph.stages.pixel={nodes:[testNode('pixel','pixel_out',900,0)],edges:[]};render();const r=$('#canvas').getBoundingClientRect();openCreator(r.left+180,r.top+180);});
 await page.locator('#createsearch').fill('Math');await page.locator('[data-create-entry="math"]').click();
 const id=await page.evaluate(()=>selected);
 assert.equal(await page.locator('[data-math-step]').count(),2);
 assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).ui.comment),'((A + B) + C)');
 assert.deepEqual(await page.locator(`[data-node="${id}"] .port-row [data-port]`).evaluateAll(es=>es.map(e=>e.dataset.port)),['input0','input1','input2','out','__add__']);
 await page.locator('[data-math-step="0"] select').first().selectOption('subtract');await page.locator('[data-math-step="1"] select').first().selectOption('multiply');await page.locator('[data-math-step="1"] select').last().selectOption('1');
 assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).ui.comment),'((A − B) × B)');
 checks.push('Math creator, all-Add defaults, input/output ordering, per-row dropdowns and simple Notes text');
 await page.evaluate(()=>{const n=current().nodes.find(n=>n.id===selected);setNodeComment(n,n.ui.comment+'\nMy note');});
 const before=await page.evaluate(()=>clone(graph));await page.locator('[data-math-mode]').selectOption('shared');await page.locator('[data-math-operation]').selectOption('divide');
 assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).ui.comment),'((A ÷ B) ÷ C)\nMy note');
 await page.evaluate(()=>undo());await page.evaluate(()=>undo());assert.deepEqual(await page.evaluate(()=>graph),before);
 await page.evaluate(id=>{change(()=>current().nodes.push(testNode('value','scalar',0,0,{type:'float',value:2})));connectPorts({node:'value',kind:'outputs',port:'out'},{node:id,kind:'inputs',port:'__add__',add:true});},id);
 assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).params.inputCount,id),4);
 assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).ui.comment,id),'(((A − B) × B) + D)\nMy note');
 await page.evaluate(id=>{selected=id;selection=new Set([id]);inspector();},id);await page.locator('[data-math-remove]').click();
 assert.equal(await page.evaluate(id=>current().edges.some(e=>e.to[0]===id&&e.to[1]==='input3'),id),false);
 checks.push('shared/row switching preserves row choices; Notes/manual text and dynamic port removal restore atomically');
 await page.locator('[data-math-type]').first().selectOption('vec3');
 assert.equal(await page.evaluate(id=>ports(current().nodes.find(n=>n.id===id),'inputs').input2,id),'vec3');
 await page.evaluate(id=>{readonly=true;selected=id;inspector();},id);assert.equal(await page.locator('[data-math-step="0"] select').first().isDisabled(),true);
 await page.evaluate(()=>{readonly=false;inspector();});
 fs.writeFileSync(path.join(folder,'graph.json'),JSON.stringify(await page.evaluate(()=>graph)));
 await page.screenshot({path:path.join(folder,'math.png')});assert.deepEqual(errors,[]);checks.push('type selector updates dynamic inputs; read-only controls stay disabled');await h.finish();console.log(JSON.stringify({passed:true,checks}));
}catch(e){await h.finish(e);throw e;}})().catch(e=>{console.error(e.stack);process.exitCode=1});
