// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1440,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');
const categoryColor=selector=>page.locator(selector).first().evaluate(e=>({bg:getComputedStyle(e).backgroundColor,fg:getComputedStyle(e).color}));
for(const[key,id]of[['uv','uv'],['texture','texture'],['uniform','tint'],['float',null],['add',null]]){
 const entry=page.locator(`[data-entry="${key}"]`);await entry.scrollIntoViewIfNeeded();await entry.click();await page.mouse.move(800,80);const created=await page.evaluate(()=>selected);assert.deepEqual(await categoryColor(`[data-entry="${key}"]`),await categoryColor(`[data-node="${created}"] .node-title`));}
checks.push('left palette colors match created Math, Constants, Uniform and Texture node headers');
const canvas=await page.locator('#canvas').boundingBox();await page.mouse.dblclick(canvas.x+canvas.width-45,canvas.y+45);await page.locator('#creator').waitFor({state:'visible'});assert.equal(await page.locator('#createcategory [role=tab]').count(),8);assert.equal(await page.locator('#createcategory select').count(),0);checks.push('canvas double-click opens the compact category tab Create');
for(const category of ['constant','uniform','sampler','math']){await page.locator(`[data-create-category="${category}"]`).click();const entries=await page.locator('#createresults .create-entry').evaluateAll(es=>es.map(e=>e.dataset.category));assert.ok(entries.length&&entries.every(x=>x===category));const key=await page.locator('#createresults .create-entry').first().getAttribute('data-create-entry');await page.mouse.move(800,80);assert.deepEqual(await categoryColor('#createresults .create-entry'),await categoryColor(`[data-entry="${key}"]`));}
checks.push('category tabs filter candidates whose colors match the same palette entries');
await page.locator('[data-create-category="constant"]').focus();const countBefore=await page.evaluate(()=>current().nodes.length);await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-create-category="uniform"]').getAttribute('aria-selected'),'true');await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>current().nodes.length),countBefore);await page.keyboard.press('Escape');checks.push('keyboard tab navigation changes category without accidentally creating a node');
await page.locator('#canvas').focus();await page.keyboard.press('Tab');await page.locator('#creator').waitFor({state:'visible'});await page.locator('[data-create-category="math"]').click();await page.locator('#createsearch').fill('Add');assert.equal(await page.locator('#createresults .create-entry').count(),1);await page.locator('#createsearch').press('Enter');const add=await page.evaluate(()=>selected);assert.equal(await page.locator(`[data-node="${add}"]`).getAttribute('data-category'),'math');checks.push('Tab opening, category search and Enter creation remain functional');
await page.evaluate(()=>{const n=current().nodes.find(n=>nodeDefinition(n).key==='uniform');pan={x:100,y:100};n.ui={x:120,y:120};render();});const port=page.locator('.node[data-category="uniform"] .output .port').first(),pr=await port.boundingBox();await page.mouse.move(pr.x+pr.width/2,pr.y+pr.height/2);await page.mouse.down();await page.mouse.move(pr.x+230,pr.y+120,{steps:8});await page.mouse.up();await page.locator('#creator').waitFor({state:'visible'});const wire=await page.evaluate(()=>creatorState.wire);assert.ok(wire&&wire.type==='vec4');await page.locator('[data-create-category="math"]').click();await page.locator('#createsearch').fill('Add');const inputType=await page.locator('#createresults small').first().innerText();assert.ok(inputType.includes('vec4'));await page.locator('#createresults .create-entry').click();const selectedId=await page.evaluate(()=>selected);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).params.type),'vec4');assert.ok(await page.evaluate(id=>current().edges.some(e=>e.to[0]===id),selectedId));checks.push('dragging a vec4 wire still filters, creates and connects the correct Add type');
await page.locator('[data-library-tab="functions"]').click();await page.locator('[data-function-source="builtin"]').click();const fn=page.locator('#nodes .palette-entry').first();await fn.click();await page.mouse.move(800,80);const fnId=await page.evaluate(()=>selected);assert.deepEqual(await categoryColor('#nodes .palette-entry'),await categoryColor(`[data-node="${fnId}"] .node-title`));checks.push('graph Function candidates match their resulting node color');
await page.locator('.stage[data-stage="vertex"]').click();await page.locator('[data-library-tab="nodes"]').click();await page.locator('[data-entry="position"]').click();await page.mouse.move(800,80);const positionId=await page.evaluate(()=>selected);assert.deepEqual(await categoryColor('[data-entry="position"]'),await categoryColor(`[data-node="${positionId}"] .node-title`));checks.push('Vertex TD Built-ins share the category palette as well');
await page.locator('#about').click();assert.equal(await page.locator('.dedication p').first().innerText(),'For Yeh Ting-Hao (PUTA)');assert.equal(await page.locator('.dedication-dates').innerText(),'1981 — 2024');assert.ok((await page.locator('.about-author').innerText()).includes('Yea Chen (yeataro)'));assert.equal(await page.locator('.about-links a').first().getAttribute('href'),'mailto:yeataro@gmail.com');await page.locator('.about-release summary').click();assert.ok(await page.locator('.about-release p').isVisible());await page.screenshot({path:path.join(folder,'about.png')});await page.keyboard.press('Escape');assert.equal(await page.locator('.brand-tagline').innerText(),'A Shader Editor for TouchDesigner');checks.push('quiet About, author contacts, short dedication, local release notes and agreed tagline');
await page.setViewportSize({width:420,height:720});await page.locator('#canvas').focus();await page.keyboard.press('Tab');await page.locator('#creator').waitFor({state:'visible'});await page.locator('[data-create-category="builtin"]').click();let box=await page.locator('#creator').boundingBox();assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=421&&box.y+box.height<=721);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(folder,'create-narrow.png')});await page.keyboard.press('Escape');await page.selectOption('#language','en');await page.locator('#canvas').focus();await page.keyboard.press('Tab');assert.equal(await page.locator('[data-create-category="all"]').innerText(),'All');checks.push('Create tabs fit narrow views and preserve language switching');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'creator-tests.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'creator-tests.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});
