/* Numeric preset context menu; isolated fixture, never TD. */
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {harness}=require('./test_glsl_code.cjs');
const[source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const field=(id='float',i=0)=>page.locator(`[data-inline-node="${id}"][data-component="${i}"]`),menu=()=>page.locator('#numericpresets');
const snapshot=()=>page.evaluate(()=>JSON.stringify({graph,past,future})),value=()=>page.evaluate(()=>current().nodes.find(n=>n.id==='float').params.value);
const presets=()=>page.locator('#numericpresets [data-numeric-preset]').evaluateAll(buttons=>buttons.map(b=>Number(b.dataset.numericPreset)));
const open=async(entry=field())=>{await entry.click({button:'right'});await menu().waitFor();await settle();};
const choose=async value=>{await page.locator(`#numericpresets [data-numeric-preset="${value}"]`).click();await settle();};
const reset=async()=>{if(await menu().count())await page.keyboard.press('Escape');await page.evaluate(()=>{
  cancelValueLadder();document.activeElement?.blur();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;
  setUIAppearance('size','standard');setUIAppearance('scale',100);setUIAppearance('theme','dark');graphTrail=[];graph.functions=[];graph.declarations=[];stage='pixel';selected=null;selection.clear();past=[];future=[];
  graph.stages.pixel={nodes:[testNode('float','float',30,40,{value:.3}),testNode('color','color',30,260,{value:[.55,.28,.9,1]}),testNode('combine','combine',330,40,{type:'vec3',components:[.1,.2,.3,0]})],edges:[]};
  graph.stages.vertex={nodes:[],edges:[]};dirty=false;rememberSavedGraph(graph);render();scale=.8;pan={x:25,y:30};transform();
});await settle();};
try{
await reset();let before=await snapshot();await open();assert.deepEqual(await presets(),[0,1,.5,-.5,-1]);assert.equal(await menu().getAttribute('role'),'menu');assert.equal(await page.locator('#valueladder').count(),0);assert.equal(await page.locator('#grapheditmenu').count(),0);assert.equal(await snapshot(),before);
await choose(.5);assert.equal(await value(),.5);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await menu().count(),0);await page.locator('#undo').click();await settle();assert.equal(await value(),.3);await page.locator('#redo').click();await settle();assert.equal(await value(),.5);before=await snapshot();await open();await choose(.5);assert.equal(await snapshot(),before);
checks.push('right-click offers float presets without graph/Ladder menus; selection is one Undo/Redo step and choosing the current value is a no-op');

await reset();await field().fill('0.73');const draftField=await field().elementHandle();before=await snapshot();await open();assert.equal(await snapshot(),before);await page.keyboard.press('Escape');await settle();assert.equal(await field().inputValue(),'0.73');assert.equal(await snapshot(),before);assert.equal(await draftField.evaluate(e=>e.isConnected),true);
await open();await page.locator('#editorheader').click({position:{x:3,y:3}});await settle();assert.equal(await menu().count(),0);assert.equal(await field().inputValue(),'0.73');assert.equal(await snapshot(),before,'outside cancellation must not commit the draft');await open();await choose(1);assert.equal(await value(),1);assert.equal(await page.evaluate(()=>past.length),1,'preset replaces a draft with one commit');
checks.push('open/Escape/outside cancellation preserve the typed draft; selecting from it replaces the value with exactly one edit');

await reset();await field().focus();await field().press('ContextMenu');await menu().waitFor();await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.dataset.numericPreset),'-1');await page.keyboard.press('ArrowUp');assert.equal(await page.evaluate(()=>document.activeElement.dataset.numericPreset),'-0.5');await page.keyboard.press('Home');assert.equal(await page.evaluate(()=>document.activeElement.dataset.numericPreset),'0');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.dataset.numericPreset),'1');await page.keyboard.press('Enter');await settle();assert.equal(await value(),1);assert.equal(await page.evaluate(()=>past.length),1);
await field().fill('0.41');before=await snapshot();await field().press('Shift+F10');await menu().waitFor();await page.keyboard.press('Tab');await settle();assert.equal(await menu().count(),0);assert.equal(await field().inputValue(),'0.41');assert.equal(await field().evaluate(e=>e===document.activeElement),true);assert.equal(await snapshot(),before);
checks.push('ContextMenu/Shift+F10, arrows/Home/End and Enter work; Tab dismisses and restores field focus without committing its draft');

await reset();await page.evaluate(()=>{selected='color';selection=new Set(['color']);inspector();});const parameter=page.locator('#inspector .color-parameter input[type=number]').first();await open(parameter);await choose(.5);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='color').params.value[0]),.5);assert.equal(await field('color').inputValue(),'0.5');assert.equal(await page.evaluate(()=>past.length),1);
await page.evaluate(()=>{window.presetWrites={int:[],uint:[],limited:[]};for(const[id,type,start]of[['int','int',3],['uint','uint',3],['limited','float',.25]]){const row=specValueField(start,type,value=>presetWrites[id].push(value)),entry=row.querySelector('input');entry.dataset.testPreset=id;if(id==='limited'){entry.min='0';entry.max='.5';}$('#inspector').append(row);}});
await open(page.locator('[data-test-preset="int"]'));assert.deepEqual(await presets(),[0,1,-1]);await choose(-1);assert.deepEqual(await page.evaluate(()=>presetWrites.int),[-1]);await open(page.locator('[data-test-preset="uint"]'));assert.deepEqual(await presets(),[0,1]);await choose(0);assert.deepEqual(await page.evaluate(()=>presetWrites.uint),[0]);await open(page.locator('[data-test-preset="limited"]'));assert.deepEqual(await presets(),[0,.5]);await choose(.5);assert.deepEqual(await page.evaluate(()=>presetWrites.limited),[.5]);
checks.push('Parameter and inline synchronize; int omits fractions, uint omits negatives and min/max limits filter presets');

await reset();before=await snapshot();await field().evaluate(e=>e.readOnly=true);await field().click({button:'right'});await settle();assert.equal(await menu().count(),0);assert.equal(await snapshot(),before);await reset();await page.evaluate(()=>{readonly=true;render();});const disabled=await field().boundingBox();await page.mouse.click(disabled.x+disabled.width/2,disabled.y+disabled.height/2,{button:'right'});await settle();assert.equal(await menu().count(),0);
await reset();await open();before=await snapshot();await field().evaluate(e=>e.disabled=true);await page.waitForFunction(()=>!document.querySelector('#numericpresets'));assert.equal(await snapshot(),before);await reset();await open();before=await snapshot();await field().evaluate(e=>e.remove());await page.waitForFunction(()=>!document.querySelector('#numericpresets'));assert.equal(await snapshot(),before);await reset();await open();before=await snapshot();await page.evaluate(()=>{stage='vertex';render();});await page.waitForFunction(()=>!document.querySelector('#numericpresets'));assert.equal(await snapshot(),before);
checks.push('readonly/disabled fields are blocked; disabling/removing an entry or changing stage cancels an open menu without edits');

const layouts=[];for(const uiScale of[75,125]){await page.setViewportSize({width:390,height:844});await reset();await page.evaluate(uiScale=>{setUIAppearance('scale',uiScale);const r=$('#canvas').getBoundingClientRect(),p=graphPoint(r.right-15,r.bottom-90),card=$('[data-node="float"]'),n=current().nodes.find(n=>n.id==='float');n.ui.x=p.x-card.offsetWidth;n.ui.y=p.y-card.offsetHeight;render();},uiScale);await settle();before=await snapshot();const r=await field().boundingBox();await page.mouse.click(r.x+r.width-3,r.y+r.height/2,{button:'right'});await menu().waitFor();const layout=await menu().evaluate(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:innerWidth,height:innerHeight};});assert.ok(layout.x>=0&&layout.y>=0&&layout.right<=layout.width+1&&layout.bottom<=layout.height+1,JSON.stringify(layout));layouts.push({uiScale,...layout});await page.screenshot({path:path.join(folder,`390-presets-${uiScale}.png`)});await page.keyboard.press('Escape');await settle();assert.equal(await snapshot(),before);}
fs.writeFileSync(path.join(folder,'preset-layout.json'),JSON.stringify(layouts,null,2));checks.push('75/125% UI clamps cursor menus inside390px viewport for a field near the bottom-right corner');

await page.setViewportSize({width:1600,height:1050});await reset();for(const gesture of['middle','alt-right','hold']){const r=await field().boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;before=await snapshot();await page.locator('#canvas').focus();if(gesture==='alt-right')await page.keyboard.down('Alt');await page.mouse.move(x,y);const button=gesture==='middle'?'middle':gesture==='alt-right'?'right':'left';await page.mouse.down({button});await page.locator('#valueladder').waitFor();assert.equal(await menu().count(),0);await page.keyboard.press('Escape');await page.mouse.up({button});if(gesture==='alt-right')await page.keyboard.up('Alt');await settle();assert.equal(await page.locator('#valueladder').count(),0);assert.equal(await snapshot(),before);}
checks.push('middle, Alt+right and stationary left hold retain existing Value Ladder triggers and cancel cleanly');assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
}catch(error){await h.finish(error);throw error;}})().catch(error=>{console.error(error.stack);process.exitCode=1;});
