/* Keyboard navigation in the real editor, isolated from TouchDesigner. */
const assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{skipPreview:true}),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const reset=async()=>{await page.evaluate(()=>{
  stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];readonly=false;
  const n=(id,x,y)=>testNode(id,id==='a'?'scalar':'add',x,y),edge=(a,b,port='a')=>({from:[a,'out'],to:[b,port]});
  graph.stages.pixel={nodes:[n('a',0,60),n('b',360,0),n('c',360,210),n('d',360,420),n('e',740,0),n('f',740,210),n('other',0,-200)],edges:[edge('a','d'),edge('a','c'),edge('a','b'),edge('a','c','b'),edge('b','e'),edge('b','f'),edge('other','b','b')]};
  past=[];future=[];selected=null;selectedEdge=null;selection.clear();dirty=false;render();setGraphFocus(true);scale=.7;pan={x:80,y:200};transform();
  EDITOR_DEV_SETTINGS.arrowNavigationFrame=false;EDITOR_DEV_SETTINGS.frameDamping=false;selectNode(current().nodes[0]);refreshCanvasSelection();
});await settle();};
const chosen=()=>page.evaluate(()=>({selected,selection:[...selection],edge:selectedEdge}));
const key=async(k,id)=>{await page.keyboard.press(k);assert.deepEqual(await chosen(),{selected:id,selection:[id],edge:null},k+' -> '+id);};
const pick=async id=>page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));refreshCanvasSelection();},id);
const state=()=>page.evaluate(()=>JSON.stringify({graph,past,future,dirty,revision}));
try{
await reset();let before=await state();const view=await page.evaluate(()=>JSON.stringify({pan,scale}));
await key('ArrowDown','a');await key('ArrowRight','b');await key('ArrowDown','c');await key('ArrowDown','d');await key('ArrowDown','d');await key('ArrowUp','c');await key('ArrowUp','b');await key('ArrowUp','b');
assert.equal(await page.evaluate(()=>arrowNavigation.steps[0].from),'a');await key('ArrowLeft','a');
assert.equal(await state(),before);assert.equal(await page.evaluate(()=>JSON.stringify({pan,scale})),view);
checks.push('Right chooses topmost destination regardless of edge order; Up/Down stays in one branch, deduplicates nodes and stops at boundaries without writes or framing');
await key('ArrowRight','b');await key('ArrowRight','e');await key('ArrowDown','f');await key('ArrowLeft','b');await key('ArrowLeft','a');
checks.push('branch changes replace the latest destination; reverse keys retrace the complete path through multi-input nodes');
await pick('b');await key('ArrowLeft','other');await key('ArrowDown','a');await key('ArrowUp','other');await key('ArrowRight','b');
checks.push('upstream navigation is symmetric and returns to the actual downstream origin');
await key('ArrowRight','e');await page.locator('#cards [data-node="e"] .node-title').click();await key('ArrowDown','e');
await page.evaluate(()=>{selection=new Set(['a','b']);selected='b';refreshCanvasSelection();$('#canvas').focus();});let multi=await chosen();await page.keyboard.press('ArrowRight');assert.deepEqual(await chosen(),multi);
await page.evaluate(()=>clearCanvasSelection());await page.keyboard.press('ArrowRight');assert.deepEqual(await chosen(),{selected:null,selection:[],edge:null});
checks.push('fresh mouse selection requires Left/Right; multiple or empty selection never navigates');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{current().edges=current().edges.filter(e=>e.from[0]!=='a'||e.to[0]!=='b');wires();});await key('ArrowDown','b');await key('ArrowLeft','other');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{graph=clone(graph);render();$('#canvas').focus();});await key('ArrowDown','b');
checks.push('deleted connections and replacement/Undo-style graph objects invalidate old navigation paths');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{graph.stages.vertex={nodes:[],edges:[]};stage='vertex';render();stage='pixel';render();selected='b';selection=new Set(['b']);refreshCanvasSelection();$('#canvas').focus();});await key('ArrowDown','b');
await reset();await key('ArrowRight','b');assert.equal(await page.evaluate(()=>change(()=>{current().nodes[0].ui.x+=12;},{localize:false,layout:true})),true);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.evaluate(()=>undo()),true);await page.evaluate(()=>{$('#canvas').focus();});await key('ArrowDown','b');
checks.push('stage round-trips and real Undo do not revive a stale route');
await reset();await page.evaluate(()=>{readonly=true;});await key('ArrowRight','b');await key('ArrowDown','c');assert.equal(await page.evaluate(()=>readonly),true);
checks.push('readonly graphs retain non-mutating navigation');
await reset();await page.evaluate(()=>{current().nodes.find(n=>n.id==='c').ui.y=0;current().nodes.find(n=>n.id==='c').ui.x=400;render();$('#canvas').focus();});await key('ArrowRight','b');await key('ArrowDown','c');await key('ArrowUp','b');
checks.push('equal-height candidates use deterministic X/ID ties and Down/Up is reversible');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{pan={x:pan.x+40,y:pan.y-20};scale=.25;transform();});await key('ArrowDown','c');
await page.evaluate(()=>{current().nodes.find(n=>n.id==='d').ui.y=100;render();$('#canvas').focus();});await key('ArrowUp','d');
checks.push('pan/zoom preserves path context; next key uses current node positions without a presorted cache');
await reset();await key('ArrowRight','b');const input=page.locator('#cards [data-node="a"] input').first();await input.focus();await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');
await page.evaluate(()=>{const e=document.createElement('div');e.id='editable-arrow-test';e.contentEditable='true';$('#canvas').append(e);e.focus();});await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');await page.evaluate(()=>$('#editable-arrow-test').remove());
await page.evaluate(()=>setGraphFocus(false));await page.locator('#uishortcuts').click();await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');assert.deepEqual(await page.locator('[data-shortcut="arrowPath"] kbd').allTextContents(),['←','→']);await page.keyboard.press('Escape');
await page.evaluate(()=>{$('#canvas').focus();});await page.keyboard.press('Shift+ArrowDown');assert.equal((await chosen()).selected,'b');
checks.push('number fields, contenteditable, modal Help and modified arrows keep their own key handling; Help lists the new keys');
await reset();before=await state();await page.evaluate(()=>{setUIExperiments({arrowNavigationFrame:true});$('#canvas').focus();});await key('ArrowRight','b');await settle();
const center=await page.evaluate(()=>{const card=$('#cards [data-node="b"]').getBoundingClientRect(),canvas=$('#canvas').getBoundingClientRect();return Math.hypot(card.left+card.width/2-canvas.left-canvas.width/2,card.top+card.height/2-canvas.top-canvas.height/2);});assert.ok(center<2,center);
assert.equal(await state(),before);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(experimentsStorageKey)).arrowNavigationFrame),true);
await page.evaluate(()=>{setUIExperiments({frameDamping:true,frameDampingMs:80});$('#canvas').focus();});await key('ArrowDown','c');assert.equal(await page.evaluate(()=>!!canvasMotion),true);await page.waitForFunction(()=>!canvasMotion);
checks.push('optional persisted auto Frame centers the new node and reuses the existing transition without graph/history writes');
assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks:checks.length}));
}catch(error){await h.finish(error);console.error(error);process.exitCode=1;}})();
