// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.evaluate(()=>{window.testInitial=clone(graph);});

const choose=async(ids)=>page.evaluate(ids=>{selection=new Set(ids);selected=ids.at(-1);render();$('#canvas').focus();window.getSelection().removeAllRanges();},ids);
const copyEvent=async()=>page.evaluate(()=>{const data=new DataTransfer(),event=new ClipboardEvent('copy',{clipboardData:data,bubbles:true,cancelable:true});$('#canvas').dispatchEvent(event);return {prevented:event.defaultPrevented,text:data.getData('text/plain')};});
const pasteEvent=async(text)=>page.evaluate(text=>{const data=new DataTransfer();data.setData('text/plain',text);const e=new ClipboardEvent('paste',{clipboardData:data,bubbles:true,cancelable:true});$('#canvas').dispatchEvent(e);return e.defaultPrevented;},text);
await choose(['tint','filter']);const copied=await copyEvent(),payload=JSON.parse(copied.text);assert.equal(copied.prevented,true);assert.equal(payload.nodes.length,2);assert.equal(payload.edges.length,1);assert.equal(payload.functions.length,1);assert.equal(payload.declarations.length,1);assert.equal(Object.hasOwn(payload,'token'),false);checks.push('copy event contains selected nodes, internal edges and dependencies without editor credentials');
const before=await page.evaluate(()=>JSON.stringify(graph)),history=await page.evaluate(()=>past.length);assert.equal(await pasteEvent(copied.text),true);const result=await page.evaluate(()=>({nodes:current().nodes.filter(n=>selection.has(n.id)),edges:current().edges.filter(e=>selection.has(e.from[0])&&selection.has(e.to[0])),functions:graph.functions.length,declarations:graph.declarations.length}));assert.equal(result.nodes.length,2);assert.equal(result.edges.length,1);assert.equal(result.functions,1);assert.equal(result.declarations,2);assert.equal(result.nodes.find(n=>n.definitionUuid==='sgrape.function.call')?.params.functionId,payload.functions[0].id);
assert.ok(result.nodes.every(n=>!payload.nodes.some(p=>p.id===n.id)&&n.ui.x%24===0&&n.ui.y%24===0));assert.equal(await page.evaluate(()=>past.length),history+1);checks.push('same-Shader paste keeps shared Functions/Uniforms, remaps node IDs, reconnects internal edges and snaps positions');
await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before);await page.locator('#redo').click();assert.equal(await page.evaluate(()=>current().nodes.length),JSON.parse(before).stages.pixel.nodes.length+2);checks.push('paste is reversible through one Undo/Redo');
const stable=await page.evaluate(()=>JSON.stringify({graph,past}));await pasteEvent('ordinary unrelated text');assert.equal(await page.evaluate(()=>JSON.stringify({graph,past})),stable);checks.push('invalid clipboard content leaves graph and history intact');
await choose(['tint']);await page.locator('#inspector > .components input').first().focus();const native=await page.evaluate(()=>{const data=new DataTransfer(),e=new ClipboardEvent('copy',{clipboardData:data,bubbles:true,cancelable:true});document.activeElement.dispatchEvent(e);return e.defaultPrevented;});assert.equal(native,false);checks.push('copying text in numeric fields remains native');
await page.evaluate(()=>{stage='vertex';graphTrail=[];render();});const vertexBefore=await page.evaluate(()=>JSON.stringify({graph,past}));const texturePayload=await page.evaluate(()=>GraphClipboard.encode(graph,graph.stages.pixel,['texture'],clipboardSource));await pasteEvent(texturePayload);assert.equal(await page.evaluate(()=>JSON.stringify({graph,past})),vertexBefore);checks.push('incompatible stage paste rejects the whole operation');
await page.evaluate(()=>{stage='pixel';render();});const foreign=JSON.parse(copied.text);foreign.source='another-shader';await pasteEvent(JSON.stringify(foreign));const cross=await page.evaluate(()=>({call:current().nodes.find(n=>selection.has(n.id)&&n.definitionUuid===FunctionModel.CALL),uniform:current().nodes.find(n=>selection.has(n.id)&&n.definitionUuid==='sgrape.builtin.uniform'),graph:clone(graph)}));assert.notEqual(cross.call.params.functionId,payload.functions[0].id);assert.equal(cross.graph.functions.find(f=>f.id===cross.call.params.functionId).scope,'local');assert.notEqual(cross.uniform.params.declarationId,'uniform_tint');assert.equal(new Set(cross.graph.declarations.map(d=>d.name)).size,cross.graph.declarations.length);fs.writeFileSync(path.join(folder,'pasted-graph.json'),JSON.stringify(cross.graph));checks.push('cross-Shader paste imports independent Function/declaration snapshots with collision-free names');
const corrupted=JSON.parse(copied.text);corrupted.source='another-shader';corrupted.declarations[0].value={invalid:true};const unchanged=await page.evaluate(()=>JSON.stringify({graph,past}));await pasteEvent(JSON.stringify(corrupted));assert.equal(await page.evaluate(()=>JSON.stringify({graph,past})),unchanged);checks.push('malformed declaration data is rejected before it can break Parameter rendering');
const functionCopy=await copyEvent();await page.evaluate(()=>enterFunction(current().nodes.find(n=>selection.has(n.id)&&n.definitionUuid===FunctionModel.CALL)));const cycleBefore=await page.evaluate(()=>JSON.stringify({graph,past}));await pasteEvent(functionCopy.text);assert.equal(await page.evaluate(()=>JSON.stringify({graph,past})),cycleBefore);checks.push('pasting a Function into itself rolls back instead of creating recursion');
await page.evaluate(()=>{navigateGraph(0);readonly=true;render();});const ro=await page.evaluate(()=>JSON.stringify(graph));assert.equal(await pasteEvent(copied.text),false);assert.equal(await page.evaluate(()=>JSON.stringify(graph)),ro);await page.evaluate(()=>{readonly=false;render();});checks.push('read-only state refuses paste');
await page.locator('[data-node="filter"] .node-title').click({button:'right'});assert.ok(await page.locator('[data-edit="group"]').isVisible());assert.ok(await page.locator('[data-edit="copy"]').isEnabled());await page.locator('[data-edit="duplicate"]').click();assert.equal(await page.locator('#grapheditmenu').count(),0);checks.push('right-click menu exposes grouping, copying, pasting and duplication');
await page.locator('#canvas').focus();await page.keyboard.press('Shift+F10');await page.locator('#grapheditmenu').waitFor();await page.keyboard.press('End');assert.equal(await page.evaluate(()=>document.activeElement.dataset.edit),'delete');await page.keyboard.press('Escape');assert.equal(await page.locator('#grapheditmenu').count(),0);checks.push('context menu supports keyboard opening, navigation and dismissal');

assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});