const path=require('node:path'),fs=require('node:fs'),assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder);const{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
try{
await page.evaluate(()=>{readonly=false;historyBusy=false;nativeMutationBusy=false;graph.functions=[];graph.declarations=[];graph.stages.pixel={nodes:[testNode('out','pixel_out',830,70)],edges:[]};stage='pixel';graphTrail=[];past=[];future=[];selected=null;selection.clear();render();scale=1;pan={x:40,y:50};transform();});
assert.equal(errors.length,0,errors.join('\n'));
const ids=await page.evaluate(()=>{const vs=['vec2','vec3','vec4'].map((type,i)=>instantiate(availableEntries().find(d=>d.entryKey==='vector:'+type),20+i*250,40).id),rep=instantiate(catalog.find(d=>d.key==='replace'),280,250,'vec4').id,color=instantiate(catalog.find(d=>d.key==='color'),20,280).id;render();return{vs,rep,color};});
for(let i=0;i<3;i++){const node=page.locator(`[data-node="${ids.vs[i]}"]`);assert.equal(await node.locator('[data-kind="inputs"]').count(),0);assert.equal(await node.locator('[data-kind="outputs"]').count(),1);assert.equal(await node.locator('[data-inline-node]').count(),i+2);}
assert.equal(await page.evaluate(()=>availableEntries().filter(d=>['vec2','vec3','vec4'].includes(d.key)).length),0);checks.push('Vector 2/3/4 presets have manual components, zero inputs, one output; old fixed vector entries hidden');
await page.locator(`[data-value-expand="${ids.vs[2]}"]`).click();assert.equal(await page.locator(`[data-manual-values="${ids.vs[2]}"]`).getAttribute('class'),'node-manual-value-group expanded');
const geometry=await page.locator(`[data-manual-values="${ids.vs[2]}"] .node-inline-component`).evaluateAll(items=>items.map(el=>({y:el.getBoundingClientRect().y,label:getComputedStyle(el.querySelector('span')).display})));assert.ok(geometry.every((p,i)=>p.label!=='none'&&(!i||p.y>geometry[i-1].y)));
await page.locator(`[data-inline-node="${ids.vs[2]}"][data-component="2"]`).fill('0.75');await page.locator(`[data-inline-node="${ids.vs[2]}"][data-component="2"]`).press('Enter');assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).params.components[2],ids.vs[2]),.75);await page.locator(`[data-inline-node="${ids.vs[2]}"][data-component="2"]`).blur();checks.push('Vector values expand into labelled component rows and commit manually');
await page.locator(`[data-node="${ids.vs[0]}"] .vector-split-shortcut`).click();assert.equal(await page.evaluate(()=>definition(current().nodes.find(n=>n.id===selected)).key),'vector_split');await page.evaluate(()=>{current().nodes.find(n=>n.id===selected).ui={x:600,y:480};render();});checks.push('Split shortcut creates an actual Split node');
await page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));render();},ids.rep);const replace=page.locator(`[data-node="${ids.rep}"]`);assert.equal(await replace.locator('[data-kind="inputs"]').count(),5);assert.equal(await replace.locator('[data-kind="outputs"]').count(),1);assert.equal(await replace.locator('.vector-port-pair').count(),0);checks.push('Replace has separate whole and component input rows, one output');
await page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));render();},ids.vs[0]);
const inspectorIdentity=async()=>({original:await page.locator('.node-inspector-name').innerText(),custom:await page.locator('#inspector [data-node-name]').inputValue()});
const identityBefore=await inspectorIdentity();assert.equal(identityBefore.original,'Vector 2');await page.locator('#inspector').screenshot({path:path.join(folder,'parameter-original-names.png')});
assert.equal(await page.locator(`[data-node="${ids.vs[0]}"] .node-prototype`).count(),0);
const before=await page.evaluate(()=>({graph:JSON.stringify(graph),history:past.length,dirty}));await page.locator('#customnames').click();assert.deepEqual(await page.evaluate(()=>({graph:JSON.stringify(graph),history:past.length,dirty})),before);checks.push('Custom Names toggle changes display only');
assert.deepEqual(await inspectorIdentity(),identityBefore);await page.locator('#inspector').screenshot({path:path.join(folder,'parameter-custom-names.png')});
assert.equal(await page.locator(`[data-node="${ids.vs[0]}"] .node-prototype`).innerText(),'Vector');
const panelName=page.locator('#inspector [data-node-name]');await panelName.fill('Header Vector');await panelName.press('Enter');assert.equal((await inspectorIdentity()).original,'Vector 2');assert.equal((await inspectorIdentity()).custom,'Header_Vector');
await page.locator('#customnames').click();assert.equal((await inspectorIdentity()).custom,'Header_Vector');assert.equal(await page.locator(`[data-node="${ids.vs[0]}"] .node-function-title`).innerText(),'Vector 2');
await page.locator('#inspector [data-node-name]').fill('Header Always');await page.locator('#inspector [data-node-name]').press('Enter');assert.equal((await inspectorIdentity()).custom,'Header_Always');await page.locator('#customnames').click();
checks.push('Parameter always shows original type plus editable custom name; canvas toggle only adds the prototype in custom-name mode');

await page.locator(`[data-node="${ids.vs[0]}"] .node-function-title`).dblclick();const rename=page.locator(`[data-node="${ids.vs[0]}"] [data-node-name]`);await rename.fill('UV Offset');await rename.press('Enter');assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).name,ids.vs[0]),'UV_Offset');
await page.locator(`[data-node="${ids.vs[1]}"] .node-function-title`).dblclick();const second=page.locator(`[data-node="${ids.vs[1]}"] [data-node-name]`);await second.fill('UV_Offset');await second.press('Enter');assert.equal(await second.getAttribute('aria-invalid'),'true');await second.press('Escape');
await page.locator(`[data-node="${ids.vs[1]}"] .node-function-title`).dblclick();const ime=page.locator(`[data-node="${ids.vs[1]}"] [data-node-name]`);await ime.dispatchEvent('compositionstart');await ime.evaluate(el=>{el.value='IME_temp';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,isComposing:true}));});assert.notEqual(await page.evaluate(id=>current().nodes.find(n=>n.id===id).name,ids.vs[1]),'IME_temp');await ime.dispatchEvent('compositionend');await ime.press('Escape');checks.push('Inline name spaces normalize; duplicates rejected; Escape cancels; composition Enter does not commit');
await page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));duplicateSelection();},ids.vs[0]);const names=await page.evaluate(()=>current().nodes.map(n=>n.name).filter(Boolean));assert.equal(new Set(names).size,names.length);checks.push('Duplicate nodes get unique names');
await page.locator(`[data-node-selector="${ids.vs[1]}"]`).selectOption('vec4');assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).params.type,ids.vs[1]),'vec4');checks.push('Header selector uses normal type mutation');
await page.evaluate(()=>{openInputCreate('spec_constant');});await page.locator('#sourcename').fill('sEnabled');await page.locator('#sourcetype').selectOption('bool');await page.locator('#sourcecreate button[type="submit"]').click();const spec=await page.evaluate(()=>graph.declarations.find(d=>d.name==='sEnabled'));assert.equal(spec.kind,'spec_constant');assert.equal(spec.value,false);assert.equal(spec.constantId,0);await page.evaluate(id=>inputReference(id),spec.id);assert.equal(await page.locator(`[data-node="${await page.evaluate(()=>selected)}"] .node-function-title`).innerText(),'sEnabled');checks.push('Spec Constants creation allocates stable ID and boolean default; reference uses declaration name');
assert.equal(await page.locator('.node-inspector-source').innerText(),'sEnabled');assert.equal(await page.locator('#inspector [data-node-name]').count(),0);
const sourceIdentity=await page.locator('.node-inspector-title').innerText();await page.locator('#customnames').click();assert.equal(await page.locator('.node-inspector-title').innerText(),sourceIdentity);await page.locator('#customnames').click();
checks.push('Source references keep original identity and read-only declaration name independent of canvas name mode');

await page.evaluate(()=>{openInputCreate('constant');});await page.locator('#sourcename').fill('cGain');await page.locator('#sourcecreate button[type="submit"]').click();assert.ok(await page.evaluate(()=>graph.declarations.some(d=>d.kind==='constant'&&d.name==='cGain')));checks.push('Graph Constants remains separate and editable');
await page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));const text=copyGraphSelection();pasteGraphSelection(text,{x:820,y:340});},ids.vs[0]);const pastedNames=await page.evaluate(()=>current().nodes.map(n=>n.name).filter(Boolean));assert.equal(new Set(pastedNames).size,pastedNames.length);checks.push('Clipboard paste allocates a unique authored node name');
await page.locator(`[data-node="${ids.vs[0]}"] .node-function-title`).dblclick();const filter=page.locator(`[data-node="${ids.vs[0]}"] [data-node-name]`);await filter.fill('gain! value');assert.equal(await filter.inputValue(),'gain_value');await filter.evaluate(el=>{el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));el.value='中文';el.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));});assert.equal(await filter.inputValue(),'中文');await filter.dispatchEvent('compositionend');assert.equal(await filter.inputValue(),'');await filter.press('Enter');assert.equal(await filter.getAttribute('aria-invalid'),'true');await filter.fill('UV Offset');await filter.press('Tab');assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).name,ids.vs[0]),'UV_Offset');checks.push('Illegal characters filter immediately; IME text stays intact until composition ends; empty result does not replace the name; blur commits');
await page.evaluate(id=>{const decl=graph.declarations.find(d=>d.id===id);nativeSourceSnapshot={enabled:true,revision,graph:clone(graph),uniforms:[],specConstants:[{...clone(decl),nameWritable:true,pending:false,missing:false,sequence:'const',expected:'spec-row',components:[{value:0,writable:true,mode:'CONSTANT'}]}],issues:[],history:{token:'spec-before'}};nativeSourceError='';dirty=false;historyBusy=false;nativeMutationBusy=false;const baseApi=api;window.specWrites=[];api=async(operation,body)=>{if(operation==='sources')return clone(nativeSourceSnapshot);if(operation==='source-value'){specWrites.push(clone(body));const result=clone(nativeSourceSnapshot);result.specConstants[0].components[0].value=body.value;result.history={token:'spec-after',beforeToken:'spec-before'};return result;}return baseApi(operation,body);};selectInputSource(id);},spec.id);
await page.locator(`[data-native-source="${spec.id}"] [data-source-component="0"]`).selectOption('true');await page.waitForFunction(()=>specWrites.length===1&&!nativeSourceBusy);assert.equal(await page.evaluate(()=>specWrites[0].value),true);assert.equal(await page.evaluate(()=>past.at(-1).kind),'source');assert.deepEqual(await page.evaluate(()=>past.at(-1).sourceIds),[spec.id]);assert.equal(await page.locator(`[data-native-source="${spec.id}"] .input-drivers`).count(),0);checks.push('Spec current boolean value uses native source-value and shared history; unsupported Python driver editing is not offered');
await page.evaluate(()=>{const input=tdBuiltInEntries().find(d=>d.key==='uv');addBuiltInReference(input,400,450);const uv=current().nodes.find(n=>n.id===selected);uv.ui={x:20,y:610};const duplicates=current().nodes.filter(n=>n.name?.startsWith('UV_Offset_'));duplicates.forEach((n,i)=>n.ui={x:800,y:320+i*200});selectedInputId=null;selected=null;selection.clear();render();fit();});
assert.equal(await page.locator('[data-input-group="tdBuiltin"]').count(),1);assert.ok(await page.locator('.node-title-meta .node-prototype').allTextContents().then(text=>text.some(value=>value.endsWith('vUV.st'))));checks.push('TD Built In exposes existing source nodes and Texture Coordinates keeps vUV.st subtitle');await settle();await page.screenshot({path:path.join(folder,'nodes.png')});
await page.evaluate(()=>{workspaceLayout.reveal('uniforms');render();});await settle();await page.screenshot({path:path.join(folder,'inputs.png')});
for(const width of [960,390]){await page.setViewportSize({width,height:900});await settle();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(folder,'viewport-'+width+'.png')});}checks.push('Inputs and node controls remain usable without page overflow at half-width and mobile');
assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({checks,errors}));await h.finish();
}catch(e){console.error(e);await h.finish(e);process.exitCode=1;}})();
