/* Note appearance is UI metadata; fixture API never writes to TD.
 * node test_note_appearance.cjs SOURCE_DIR STATE_JSON REPORT_DIR */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
async function run(){
  const[source,stateFile,folder]=process.argv.slice(2),h=await harness(source,stateFile,folder,{touch:true}),{page,checks,errors,settle}=h;
  page.setDefaultTimeout(6000);
  const card=()=>page.locator('[data-node="note"]'),title=()=>card().locator('.node-title'),body=()=>card().locator('.comment-node-canvas-content'),preview=()=>card().locator('.comment-node-preview'),entry=()=>card().locator('[data-comment-node]');
  const control=key=>card().locator('[data-note-appearance="'+key+'"]');
  const transparent=async()=>{await card().locator('[data-note-color="note"]').click();await page.locator('[data-note-color-transparent]').click();await settle();};
  const preset=async color=>{await card().locator('[data-note-color="note"]').click();await page.locator('[data-frame-color-preset="'+color+'"]').click();await settle();};
  const graphJSON=()=>page.evaluate(()=>JSON.stringify(graph));
  const note=()=>page.evaluate(()=>clone(current().nodes.find(n=>n.id==='note')));
  const history=()=>page.evaluate(()=>past.length);
  const shape=async()=>page.evaluate(()=>{const card=document.querySelector('[data-node="note"]'),rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};};return{card:rect(card),body:rect(card.querySelector('.comment-node-canvas-content')),title:rect(card.querySelector('.node-title'))};});
  const sameBody=(a,b)=>{for(const part of ['card','body'])for(const axis of ['x','y','width','height'])assert.ok(Math.abs(a[part][axis]-b[part][axis])<.2,part+'.'+axis+' changed on selection');};
  const select=async ids=>{await page.evaluate(ids=>{document.activeElement?.blur();selection=new Set(ids);selected=ids.at(-1)||null;selectedEdge=null;render();},ids);await settle();};
  const reset=async(ui={})=>{await page.setViewportSize({width:1600,height:1100});await page.evaluate(ui=>{
    document.activeElement?.blur();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;stage='pixel';graphTrail=[];graph=clone(window.noteAppearanceFixture);Object.assign(current().nodes.find(n=>n.id==='note').ui,ui);selected='note';selectedInputId=null;inspectorTab='parameters';selectedEdge=null;selection=new Set(['note']);past=[];future=[];dirty=false;rememberSavedGraph(graph);setUIAppearance('scale',100);setUIAppearance('theme','dark');setUIExperiments({selectionToolbar:'off',nodeBodyDrag:true});setGraphFocus(true);render();scale=1;pan={x:20,y:40};transform();
  },ui);await settle();};
  const drag=async(point,dx,dy)=>{await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+dx,point.y+dy,{steps:5});await page.mouse.up();await settle();};
  const titlePoint=async()=>{const r=await title().boundingBox();return{x:r.x+r.width*.56,y:r.y+r.height*.5};};
  try{
    await page.evaluate(()=>{stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];const note=testNode('note','comment',96,192),value=testNode('value','float',680,220),output=testNode('output','pixel_out',1040,220);Object.assign(note.ui,{width:420,height:300,comment:'# Note body\n\nSelect here, then drag its title.\n\n**Markdown** stays readable.'});note.name='Lighting_notes';graph.stages.pixel={nodes:[note,value,output],edges:[{from:['value','out'],to:['output','color']}]};window.noteAppearanceFixture=clone(graph);});
    await reset();const identity=await note();assert.equal(identity.definitionUuid,'sgrape.builtin.comment');assert.ok(identity.revisionHash);assert.equal(await page.evaluate(()=>nodeTypeLabel(definition(current().nodes.find(n=>n.id==='note')))),'Note');
    assert.equal(await control('noteTitleOnSelection').count(),1);assert.equal(await control('noteTransparent').count(),0);assert.equal(await control('noteTitleOnSelection').getAttribute('aria-pressed'),'false');assert.equal(await card().locator('[data-note-color="note"]').count(),1);
    assert.equal(await page.locator('[data-node="value"] [data-note-appearance]').count(),0);assert.equal(await title().isVisible(),true);
    const standard=await card().evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,shadow:s.boxShadow};});assert.notEqual(standard.background,'rgba(0, 0, 0, 0)');assert.notEqual(standard.shadow,'none');
    await select([]);assert.equal(await title().isVisible(),true);await select(['note']);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('Note is a UI label over the unchanged comment UUID/revision; defaults retain normal title/body and ordinary nodes have no appearance controls');

    for(const key of ['noteTitleOnSelection','noteTransparent']){
      await reset();const before=await graphJSON(),count=await history(),positions=(await note()).ui;if(key==='noteTransparent')await transparent();else await control(key).click();await settle();assert.equal((await note()).ui[key],true);if(key!=='noteTransparent')assert.equal(await control(key).getAttribute('aria-pressed'),'true');assert.equal(await history(),count+1);assert.equal((await note()).ui.x,positions.x);assert.equal((await note()).ui.y,positions.y);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);const after=await graphJSON();
      await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),before);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),after);assert.equal((await note()).revisionHash,identity.revisionHash);
    }checks.push('title-mode click and palette transparency selection each changes only metadata in one exact Undo/Redo, never moves the note or changes its shader identity');


    await reset();const beforeColor=await graphJSON(),titleColor=await title().evaluate(e=>getComputedStyle(e).backgroundColor);await card().locator('[data-note-color="note"]').click();await page.locator('[data-frame-color-preset="#485f8d"]').click();await settle();assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await history(),1);assert.equal(await title().evaluate(e=>getComputedStyle(e).backgroundColor),titleColor);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);const afterColor=await graphJSON(),bodyColor=await card().evaluate(e=>getComputedStyle(e).backgroundColor);assert.notEqual(bodyColor,'rgba(0, 0, 0, 0)');
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeColor);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),afterColor);await transparent();assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await card().evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');const restoreHistory=await history();await preset('#485f8d');assert.equal((await note()).ui.noteTransparent===true,false);assert.equal(await history(),restoreHistory+1);assert.equal(await card().evaluate(e=>getComputedStyle(e).backgroundColor),bodyColor);assert.equal(await title().evaluate(e=>getComputedStyle(e).backgroundColor),titleColor);checks.push('Note body preset color commits one exact Undo/Redo, keeps title color and shader unchanged, and transparency retains/restores the chosen body color');

    await reset({noteTitleOnSelection:true});const selectedShape=await shape();assert.equal(await title().isVisible(),true);assert.ok(selectedShape.title.y+selectedShape.title.height<=selectedShape.body.y+1,'selected title sits above the body');
    await select([]);const unselectedShape=await shape();sameBody(selectedShape,unselectedShape);assert.equal(await title().isVisible(),false);await preview().click();await settle();assert.equal(await page.evaluate(()=>selected),'note');sameBody(unselectedShape,await shape());assert.equal(await title().isVisible(),true);assert.equal(await history(),0);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('selection-only title overlays above the body, hides when unselected, and selection never moves/resizes card or content');

    for(const theme of ['dark','light']){
      await reset({noteTransparent:true,noteTitleOnSelection:true});await page.evaluate(theme=>setUIAppearance('theme',theme),theme);await select([]);await page.mouse.move(1550,1000);const transparent=await card().evaluate(e=>{const s=getComputedStyle(e);return{background:s.backgroundColor,border:s.borderTopColor,shadow:s.boxShadow};});assert.equal(transparent.background,'rgba(0, 0, 0, 0)');assert.ok(transparent.border==='rgba(0, 0, 0, 0)'||transparent.border==='transparent');assert.equal(transparent.shadow,'none');
      await preview().dblclick();await settle();assert.equal(await entry().isVisible(),true);assert.notEqual(await entry().evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');await entry().fill('Temporary appearance draft');await entry().press('Escape');await settle();assert.equal(await history(),0);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
      await page.screenshot({path:path.join(folder,'note-transparent-'+theme+'.png')});
    }checks.push('transparent notes lose idle canvas background/border/shadow in dark and light, while double-click editing keeps a visible input background and Escape preserves text/history');

    await reset({noteTitleOnSelection:true,noteTransparent:true});const beforeBody=await note(),beforePan=await page.evaluate(()=>({...pan})),bodyBox=await body().boundingBox();await drag({x:bodyBox.x+5,y:bodyBox.y+bodyBox.height-8},65,35);assert.equal((await note()).ui.x,beforeBody.ui.x);assert.equal((await note()).ui.y,beforeBody.ui.y);assert.equal(await history(),0);assert.deepEqual(await page.evaluate(()=>({...pan})),beforePan);
    await select(['note']);const beforeDrag=await graphJSON(),start=await note();await drag(await titlePoint(),48,24);const moved=await note();assert.equal(moved.ui.x,start.ui.x+48);assert.equal(moved.ui.y,start.ui.y+24);assert.equal(await history(),1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeDrag);
    const buttonBox=await control('noteTitleOnSelection').boundingBox(),buttonBefore=await note();await drag({x:buttonBox.x+buttonBox.width/2,y:buttonBox.y+buttonBox.height/2},40,15);assert.equal((await note()).ui.x,buttonBefore.ui.x);assert.equal((await note()).ui.y,buttonBefore.ui.y);checks.push('note body cannot drag or pan despite body-drag preference; title drags once with Undo; appearance-button pointer gestures never drag the card');

    await reset({noteTitleOnSelection:true,noteTransparent:true});await card().locator('[data-collapse-node]').click();await settle();await select([]);assert.equal(await card().evaluate(e=>e.classList.contains('collapsed')),true);assert.equal(await title().isVisible(),true);assert.equal(await preview().count(),0);await card().locator('[data-collapse-node]').click();await settle();assert.equal(await card().evaluate(e=>e.classList.contains('collapsed')),false);assert.equal(await preview().isVisible(),true);assert.equal((await note()).ui.noteTitleOnSelection,true);assert.equal((await note()).ui.noteTransparent,true);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('collapsed notes always retain a usable title/expand control and expanding preserves both appearance flags');

    await reset({noteTitleOnSelection:true,noteTransparent:true,noteColor:'#485f8d'});const persisted=await page.evaluate(()=>{const raw=JSON.stringify(graph);graph=JSON.parse(raw);render();const payload=GraphClipboard.decode(GraphClipboard.encode(graph,current(),['note'],shaderId));let ids;change(()=>{ids=GraphClipboard.paste(graph,current(),payload,{source:shaderId,stage,target:editorTarget,catalog,types:numericTypes(),anchor:{x:650,y:580}});});return{original:clone(current().nodes.find(n=>n.id==='note')),copy:clone(current().nodes.find(n=>ids.includes(n.id)))};});
    for(const n of [persisted.original,persisted.copy]){assert.equal(n.ui.noteTitleOnSelection,true);assert.equal(n.ui.noteTransparent,true);assert.equal(n.ui.noteColor,'#485f8d');assert.equal(n.definitionUuid,identity.definitionUuid);assert.equal(n.revisionHash,identity.revisionHash);}assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('JSON roundtrip and real clipboard model copy preserve both appearance flags without changing definition or shader content');

    await reset();await page.evaluate(()=>{readonly=true;render();});assert.equal(await control('noteTitleOnSelection').isDisabled(),true);assert.equal(await card().locator('[data-note-color]').isDisabled(),true);const beforeReadonly=await graphJSON();await control('noteTitleOnSelection').evaluate(e=>e.click());assert.equal(await graphJSON(),beforeReadonly);assert.equal(await history(),0);checks.push('readonly disables appearance controls and programmatic button activation cannot mutate graph/history');

    await reset({width:190,noteTitleOnSelection:true});await page.evaluate(()=>{if(!customNodeNamesEnabled())$('#customnames').click();render();});await settle();assert.equal(await title().locator('.node-function-title').innerText(),'Lighting_notes');assert.equal(await title().locator('.node-prototype').innerText(),'Note');
    const arrangement=await title().evaluate(e=>{const rect=e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom};};return{title:rect(e),name:rect(e.querySelector('.node-title-text')),subtype:rect(e.querySelector('.node-prototype')),controls:[...e.querySelectorAll('[data-note-appearance],[data-note-color]')].map(rect),width:e.clientWidth,scroll:e.scrollWidth};});
    assert.ok(arrangement.scroll<=arrangement.width+1);assert.ok(arrangement.name.right<=arrangement.subtype.left+1);assert.ok(arrangement.subtype.right<=arrangement.controls[0].left+1);assert.ok(arrangement.controls.at(-1).right<=arrangement.title.right+1);await page.screenshot({path:path.join(folder,'note-190-custom-name.png')});checks.push('at 190px width the custom name stays left, muted Note subtype follows, and both controls fit on the right without overflow');

    await reset({noteTitleOnSelection:true});await select([]);await preview().tap();await settle();assert.equal(await title().isVisible(),true);const beforeTouch=await history();await card().locator('[data-note-color="note"]').tap();await page.locator('[data-note-color-transparent]').tap();await settle();assert.equal((await note()).ui.noteTransparent,true);assert.equal(await history(),beforeTouch+1);await card().locator('[data-note-color="note"]').click();assert.equal(await page.locator('[data-note-color-transparent]').getAttribute('aria-checked'),'true');await page.locator('[data-frame-color-preset="#485f8d"]').focus();await page.keyboard.press('Space');await settle();assert.equal((await note()).ui.noteTransparent===true,false);assert.equal((await note()).ui.noteColor,'#485f8d');assert.equal(await history(),beforeTouch+2);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);checks.push('touch body selection reveals controls; touch and keyboard Space activate appearance controls without shader changes');
    await reset({noteTitleOnSelection:true,noteTransparent:true});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{scale=.7;pan={x:-55,y:75};transform();});await settle();await page.screenshot({path:path.join(folder,'note-narrow.png')});assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'note-appearance-graph.json'),await graphJSON());await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);throw error;}
}
run().catch(error=>{console.error(error);process.exitCode=1;});

