/* Read-only browser gestures: node test_sidebar_layout.cjs SESSION_JSON REPORT_DIR [OVERLAY_DIR]
 * Session URL stays private; every non-GET request is blocked. Uses the working demo tint node.
 */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const [sessionFile,folder,overlay]=process.argv.slice(2),session=JSON.parse(fs.readFileSync(sessionFile,'utf8'));
fs.mkdirSync(folder,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE});const checks=[],errors=[],posts=[];
try{const page=await browser.newPage({viewport:{width:1600,height:1040},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',route=>{const req=route.request(),name=req.resourceType()==='document'?'index.html':path.basename(new URL(req.url()).pathname);if(req.method()!=='GET'){posts.push(req.method());return route.abort();}const file=overlay&&path.join(overlay,name);if(file&&fs.existsSync(file))return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(name)]});return route.continue();});
await page.goto(session.url);await page.waitForFunction(()=>typeof graph!=='undefined'&&graph);await page.evaluate(()=>document.fonts.ready);await page.locator('[data-node="tint"] .node-title').click();
const settleResize=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
const widths=()=>page.evaluate(()=>({left:document.querySelector('.library').getBoundingClientRect().width,right:document.querySelector('.details').getBoundingClientRect().width,canvas:document.querySelector('#canvas').getBoundingClientRect().width}));
const graphView=()=>page.evaluate(()=>JSON.stringify({graph,pan,scale,revision,past:past.length,dirty}));const original=await graphView();
const drag=async(id,dx)=>{const r=await page.locator(id).boundingBox(),x=r.x+r.width/2,y=r.y+80;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+dx,y,{steps:8});await page.mouse.up();};
let w=await widths();assert.equal(w.left,220);assert.equal(w.right,340);await drag('#libraryresize',120);let next=await widths();assert.equal(next.left,w.left+120);assert.equal(next.right,w.right);await drag('#detailsresize',-140);w=await widths();assert.equal(w.right,480);assert.equal(w.left,next.left);assert.equal(await graphView(),original);checks.push('both dividers resize only their own sidebar and preserve graph, history, pan and zoom');
await page.locator('#detailsresize').focus();await page.keyboard.press('Home');assert.equal((await widths()).right,300);await page.locator('#libraryresize').focus();await page.keyboard.press('Home');assert.equal((await widths()).left,180);checks.push('left 180px and right 300px minimums');
const tuple=await page.locator('#inspector > .components input').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.equal(tuple.length,4);assert.ok(tuple.every(r=>Math.abs(r.y-tuple[0].y)<1&&r.width>45));assert.ok(await page.locator('.parameter-hint').isVisible());checks.push('all four Vector4 values align on one row at minimum sidebar width');
await page.locator('#detailsresize').focus();await page.keyboard.press('ArrowLeft');assert.equal((await widths()).right,308);await page.keyboard.press('Shift+ArrowLeft');assert.equal((await widths()).right,340);await page.keyboard.press('End');assert.ok((await widths()).right<=640);checks.push('keyboard adjustment follows divider direction and clamps at maximum');
const beforeCancel=await widths(),r=await page.locator('#detailsresize').boundingBox();await page.mouse.move(r.x+3,r.y+100);await page.mouse.down();await page.mouse.move(r.x+103,r.y+100);await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual(await widths(),beforeCancel);checks.push('Escape cancels a width gesture without saving');
const touchBefore=await widths(),touchBox=await page.locator('#libraryresize').boundingBox(),touchX=touchBox.x+3,touchY=touchBox.y+120,cdp=await page.context().newCDPSession(page);
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchX,y:touchY}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchX+40,y:touchY}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
assert.equal((await widths()).left,touchBefore.left+40);assert.equal((await widths()).right,touchBefore.right);await cdp.detach();checks.push('touch pointer resizes a sidebar without panning the canvas');
await page.locator('#libraryresize').dblclick();await page.locator('#detailsresize').dblclick();assert.equal((await widths()).left,220);assert.equal((await widths()).right,340);checks.push('double click resets only that sidebar');
await drag('#libraryresize',60);await drag('#detailsresize',-80);const stored=await widths();await page.reload();await page.waitForFunction(()=>typeof graph!=='undefined'&&graph);assert.equal((await widths()).left,stored.left);assert.equal((await widths()).right,stored.right);checks.push('both saved widths survive page reload');
await page.locator('[data-node="tint"] .node-title').click();await page.screenshot({path:path.join(folder,'sidebar-desktop.png')});
for(const width of [1100,801]){await page.setViewportSize({width,height:900});await settleResize();w=await widths();assert.ok(w.left>=180&&w.right>=300&&w.canvas>=279,JSON.stringify({width,w}));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}checks.push('desktop viewport shrink keeps both minimums and canvas space');
await page.setViewportSize({width:1600,height:1040});await settleResize();assert.equal((await widths()).left,stored.left);assert.equal((await widths()).right,stored.right);checks.push('temporary viewport clamping preserves preferred widths');
await page.setViewportSize({width:420,height:760});await settleResize();await page.locator('#toggledetails').click();assert.ok(await page.locator('#detailsresize').isVisible());w=await widths();assert.ok(w.right<=388);await drag('#detailsresize',100);assert.equal((await widths()).right,300);const narrow=await page.locator('#inspector > .components input').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()));assert.ok(narrow.every(r=>Math.abs(r.y-narrow[0].y)<1));await page.screenshot({path:path.join(folder,'sidebar-narrow.png')});checks.push('narrow overlay can resize and keeps vec4 in one row');
await page.selectOption('#language','en');assert.ok((await page.locator('#detailsresize').getAttribute('aria-label')).startsWith('Resize'));assert.ok((await page.locator('.parameter-hint').innerText()).includes('middle'));checks.push('divider and Ladder hints are bilingual');
assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);assert.equal(await page.evaluate(()=>document.body.classList.contains('resizing-sidebar')),false);checks.push('no page errors, Shader writes or stuck drag state');
fs.writeFileSync(path.join(folder,'sidebar-tests.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}
catch(e){fs.writeFileSync(path.join(folder,'sidebar-tests.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));throw e;}
finally{await browser.close();}})().catch(e=>{console.error(e.message.replaceAll(new URL(session.url).hash.slice(1),'[session]'));process.exitCode=1;});
