/* Read-only UI check: node test_panel_resize.cjs SESSION_JSON REPORT_DIR [OVERLAY_DIR] */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const [sessionFile,folder,overlay]=process.argv.slice(2),session=JSON.parse(fs.readFileSync(sessionFile,'utf8'));fs.mkdirSync(folder,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[],writes=[];
try{const page=await browser.newPage({viewport:{width:1500,height:1040},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',r=>{const q=r.request(),name=q.resourceType()==='document'?'index.html':path.basename(new URL(q.url()).pathname),file=overlay&&path.join(overlay,name);if(q.method()!=='GET'){writes.push(q.method());return r.abort();}return file&&fs.existsSync(file)?r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(name)]}):r.continue();});
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
await page.goto(session.url);await page.waitForSelector('.node');await settle();
const heights=()=>page.locator('.inspector-panel').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height));const closeEnough=(a,b)=>assert.ok(Math.abs(a-b)<1,JSON.stringify({a,b}));
const original=await page.evaluate(()=>JSON.stringify({graph,revision,dirty,past:past.length,pan,scale}));
const drag=async(id,dy)=>{const r=await page.locator(id).boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y+dy,{steps:8});await page.mouse.up();};
let before=await heights();await drag('#resize-help',-80);let after=await heights();closeEnough(after[0],before[0]);closeEnough(after[1],before[1]-80);closeEnough(after[2],before[2]+80);checks.push('lower divider enlarges Help and changes only its adjacent Live pane');
before=after;await drag('#resize-live',30);after=await heights();closeEnough(after[0],before[0]+30);closeEnough(after[1],before[1]-30);closeEnough(after[2],before[2]);checks.push('upper divider changes only Parameter and Live');
assert.equal(await page.evaluate(()=>JSON.stringify({graph,revision,dirty,past:past.length,pan,scale})),original);checks.push('pane sizing preserves graph, history, pan and zoom');
await page.locator('#resize-help').focus();await page.keyboard.press('Home');after=await heights();assert.ok(after[1]>=117&&after[1]<=119&&after[2]>after[1]);await page.keyboard.press('End');after=await heights();assert.ok(after[2]>=117);checks.push('both expanded panes respect the header and 80px body minimum');
await page.locator('#resize-help').dblclick();before=await heights();const r=await page.locator('#resize-help').boundingBox();await page.mouse.move(r.x+r.width/2,r.y+3);await page.mouse.down();await page.mouse.move(r.x+r.width/2,r.y-40);await page.keyboard.press('Escape');await page.mouse.up();after=await heights();after.forEach((x,i)=>closeEnough(x,before[i]));checks.push('Escape cancels the gesture and restores prior heights');
await drag('#resize-help',-70);const persisted=await heights();await page.reload();await page.waitForSelector('.node');await settle();(await heights()).forEach((x,i)=>closeEnough(x,persisted[i]));checks.push('height preferences survive reload');
await page.locator('#livetoggle').click();await settle();assert.equal(await page.locator('#resize-live').isVisible(),false);assert.equal(await page.locator('#resize-help').isVisible(),true);before=await heights();await drag('#resize-help',-90);after=await heights();closeEnough(after[1],before[1]);closeEnough(after[0],before[0]-90);closeEnough(after[2],before[2]+90);checks.push('collapsed Live permits direct Parameter and Help resizing');
const ids=['parameters','live','help'];for(let mask=0;mask<8;mask++){for(let i=0;i<3;i++){const b=page.locator(`[data-panel="${ids[i]}"] .panel-heading`);if((await b.getAttribute('aria-expanded')==='true')!==!!(mask&(1<<i)))await b.click();}await settle();assert.equal(await page.locator('.panel-divider:visible').count(),Math.max(0,ids.filter((_,i)=>mask&(1<<i)).length-1));const host=await page.locator('.details').boundingBox();for(const id of ids){const b=await page.locator(`[data-panel="${id}"] .panel-heading`).boundingBox();assert.ok(b.y>=host.y&&b.y+b.height<=host.y+host.height+1);}}
checks.push('all collapse combinations retain reachable headings and only meaningful dividers');
await page.locator('#livetoggle').click();await page.locator('#resize-help').focus();before=await heights();await page.keyboard.press('Shift+ArrowUp');after=await heights();closeEnough(after[2],before[2]+32);checks.push('keyboard divider movement follows the visual direction');
const tb=await page.locator('#resize-help').boundingBox(),cdp=await page.context().newCDPSession(page);before=await heights();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tb.x+40,y:tb.y+3}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tb.x+40,y:tb.y-27}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();after=await heights();closeEnough(after[2],before[2]+30);checks.push('touch pointer resizes pane heights');
await page.locator('[data-node="texture"] .node-title').click();await drag('#resize-help',-130);await page.screenshot({path:path.join(folder,'help-expanded.png')});
for(const viewport of [{width:420,height:720},{width:360,height:480}]){await page.setViewportSize(viewport);await settle();if(!await page.locator('.details').isVisible())await page.locator('#toggledetails').click();await settle();for(const id of ids){const b=await page.locator(`[data-panel="${id}"] .panel-heading`).boundingBox();assert.ok(b.y>=0&&b.y+b.height<=viewport.height+1);}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}checks.push('short mobile views adapt minimums while keeping every heading accessible');
await page.selectOption('#language','en');assert.ok((await page.locator('#resize-help').getAttribute('aria-label')).includes('Resize'));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);checks.push('localized handles, no Shader writes and no browser errors');
fs.writeFileSync(path.join(folder,'pane-resize-tests.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}
catch(e){fs.writeFileSync(path.join(folder,'pane-resize-tests.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));throw e;}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});

