/* Actual editor UI with an isolated API fixture; no live TD writes. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawnSync}=require('node:child_process');
const {harness}=require('./test_glsl_code.cjs');
(async()=>{
 const [source,state,folder]=process.argv.slice(2);
 const oracle=spawnSync(process.env.PYTHON||'python',[path.join(__dirname,'../unit/top_compiler_oracle.py')],{encoding:'utf8',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
 assert.equal(oracle.status,0,oracle.stderr);
 const cases=JSON.parse(oracle.stdout).cases,good=cases.find(c=>!c.error).graph,bad=cases.find(c=>c.name==='disconnected cycle').graph;
 const h=await harness(source,state,folder,{skipPreview:true}),{page,checks,errors}=h;
 let calls=0,fail=false,hold=null;
 await page.route('**/api/validate',async route=>{calls++;if(hold)await hold;await route.fulfill(fail?{status:422,json:{error:'Fixture Python compile failure'}}:{json:{vertex:'// HOST VERTEX',pixel:'// HOST PYTHON'}});});
 const shown=()=>page.locator('#generationstatus').evaluate(e=>({route:e.dataset.route,state:e.dataset.state,text:e.textContent}));
 const setGraph=async(source,frontend)=>page.evaluate(({source,frontend})=>{
   clearTimeout(autoTimer);scheduleGraphApply=()=>{};nativeSourcePolling=uniformPolling=customPolling=true;uniformLive.disconnect();uniformLive.connect=()=>{};
   readonly=conflicted=dirty=false;connectionInterrupted=true;graph=source;stage='pixel';graphTrail=[];selected=null;selection.clear();
   frontendCompiler=frontend?{protocol:GrapeTopCompiler.protocol,catalogHash:'fixture'}:null;generationActivity=null;render();
 },{source,frontend});
 try{
  await setGraph(good,true);assert.equal((await shown()).route,'frontend');assert.equal((await shown()).state,'pending');
  const before=await page.evaluate(()=>JSON.stringify({graph,past,future}));
  await page.evaluate(()=>generateGLSL(clone(graph)));assert.equal((await shown()).state,'ready');assert.equal(calls,0);
  assert.match((await shown()).text,/TypeScript.*New/);checks.push('Frontend generation uses the real compiler and makes no Python validation request');
  await page.evaluate(()=>{graph.stages.pixel.nodes[0].name='Changed graph';mark();});assert.equal((await shown()).state,'pending');
  checks.push('A new graph edit cannot display the preceding generation as current success');
  await setGraph(good,false);await page.evaluate(()=>generateGLSL(clone(graph)));assert.equal(calls,1);assert.equal((await shown()).route,'python');assert.equal((await shown()).state,'ready');
  checks.push('Python results explicitly show the host Legacy route');
  await setGraph({...good,target:'mat'},true);await page.evaluate(()=>generateGLSL(clone(graph)));assert.equal((await shown()).route,'python');
  checks.push('An unsupported whole graph selects Python even when the frontend compiler is available');
  fail=true;await page.evaluate(()=>generateGLSL(clone(graph)).catch(()=>{}));assert.equal((await shown()).state,'failed');fail=false;
  assert.ok(await page.evaluate(()=>statusHistory.some(i=>i.error&&i.message.includes('Fixture Python compile failure'))));
  await setGraph(bad,true);await page.evaluate(()=>generateGLSL(clone(graph)).catch(()=>{}));assert.equal((await shown()).route,'frontend');assert.equal((await shown()).state,'failed');
  checks.push('Real frontend compiler rejection and Python rejection retain route and error history');
  await setGraph(good,false);
  let release;hold=new Promise(r=>release=r);
  await page.evaluate(()=>{window.pendingGeneration=generateGLSL(clone(graph));});
  await page.waitForFunction(()=>document.querySelector('#generationstatus').dataset.state==='running');
  await page.evaluate(()=>{graph.stages.pixel.nodes[0].name='Newer graph';mark();});
  release();hold=null;await page.evaluate(()=>pendingGeneration);assert.equal((await shown()).state,'pending');
  assert.ok(await page.evaluate(()=>statusHistory.some(i=>i.message.includes('Earlier graph version'))));
  checks.push('Late response for an edited graph is historical, never current success');
  await setGraph(good,false);
  // Exercise actual Apply routing, not just the code viewer.
  let lastApply;
  await page.route('**/api/apply',async route=>{const body=lastApply=route.request().postDataJSON();await route.fulfill({json:{state:{graph:body.graph,revision:1},shaderUpdated:true,target:'/fixture/Shader'}});});
  await page.evaluate(()=>{dirty=true;savedGraphContent=null;connectionInterrupted=false;});
  await page.evaluate(()=>performApplyGraph());assert.equal((await shown()).route,'python');assert.equal((await shown()).state,'ready');
  checks.push('Actual Apply reports Python generation even when the GLSL viewer is closed');
  assert.equal(lastApply.frontendArtifact,undefined);
  await setGraph(good,true);await page.evaluate(()=>{dirty=true;savedGraphContent=null;connectionInterrupted=false;});
  await page.evaluate(()=>performApplyGraph());assert.equal((await shown()).route,'frontend');assert.equal((await shown()).state,'ready');assert.equal(typeof lastApply.frontendArtifact.compiled.pixel,'string');
  checks.push('Frontend Apply status agrees with the GLSL artifact actually sent to the host');
  await setGraph(good,true);const graphBefore=await page.evaluate(()=>JSON.stringify({graph,past,future,pan,scale}));
  await page.evaluate(()=>{status('Persistent error',true);status('Background success');for(let i=0;i<205;i++)status('Activity '+i);status('Activity 204');status('<img src=x onerror=alert(1)>');});
  assert.equal(await page.locator('#status').textContent(),'Persistent error');
  assert.equal(await page.evaluate(()=>statusHistory.length),200);
  assert.equal(await page.evaluate(()=>statusHistory[1].count),2);
  await page.locator('#statushistorytoggle').click();await page.locator('#statushistory:popover-open').waitFor();
  assert.equal(await page.locator('#statushistorytoggle').getAttribute('aria-expanded'),'true');
  assert.equal(await page.locator('#statushistorylist img').count(),0);
  const list=page.locator('#statushistorylist');assert.ok(await list.evaluate(e=>e.scrollHeight>e.clientHeight));
  const panel=await page.locator('#statushistory').boundingBox(),button=await page.locator('#statushistorytoggle').boundingBox();
  assert.ok(panel.y+panel.height<=button.y);await list.hover();await page.mouse.wheel(0,550);await page.waitForTimeout(150);assert.ok(await list.evaluate(e=>e.scrollTop>0));
  assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future,pan,scale})),graphBefore);
  checks.push('Bounded, deduplicated, scrollable upward history keeps persistent errors and cannot edit/pan/zoom the graph');
  await page.keyboard.press('Escape');assert.equal(await page.locator('#statushistory:popover-open').count(),0);assert.equal(await page.locator('#statushistorytoggle').evaluate(e=>e===document.activeElement),true);
  await page.keyboard.press('Enter');await page.locator('#statushistory:popover-open').waitFor();await page.locator('#statushistoryclose').click();
  checks.push('Keyboard activation, Escape and close restore usable focus');
  await page.evaluate(()=>{setLanguage('zh-Hant');renderGenerationStatus();status('已載入，供測試',false,{clearError:true});});
  assert.match((await shown()).text,/前端 TypeScript（新）/);
  await page.locator('#statushistorytoggle').click();await page.screenshot({path:path.join(folder,'status-history-desktop.png')});await page.locator('#statushistoryclose').click();
  await page.setViewportSize({width:390,height:844});await page.locator('#statushistorytoggle').click();
  const narrow=await page.locator('#statushistory').boundingBox();assert.ok(narrow.x>=0&&narrow.x+narrow.width<=391);assert.ok(narrow.y>=0);
  assert.ok(await page.locator('#generationstatus').evaluate(e=>e.scrollWidth<=e.clientWidth),'Full generation route remains readable on a phone');
  await page.screenshot({path:path.join(folder,'status-history-mobile.png')});
  await page.locator('#statushistoryclose').click();await page.locator('#statushistorytoggle').click();await page.locator('#canvas').click({position:{x:10,y:10}});assert.equal(await page.locator('#statushistory:popover-open').count(),0);
  checks.push('Traditional Chinese, mobile fit, and outside dismissal work');
  await page.reload();await page.waitForSelector('.node');assert.ok(await page.evaluate(()=>statusHistory.length<200));
  checks.push('History is session-only and resets on reload');
  assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
 }catch(e){await h.finish(e);throw e;}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
