/* Keyboard navigation in the real editor, isolated from TouchDesigner. */
const assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{skipPreview:true}),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const reset=async(bidirectional=false)=>{await page.evaluate(bidirectional=>{
  stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];readonly=false;
  const n=(id,x,y)=>testNode(id,id==='a'?'scalar':'add',x,y),edge=(a,b,port='a')=>({from:[a,'out'],to:[b,port]});
  graph.stages.pixel={nodes:[n('a',0,60),n('b',360,0),n('c',360,210),n('d',360,420),n('e',740,0),n('f',740,210),n('other',0,-200)],edges:[edge('a','d'),edge('a','c'),edge('a','b'),edge('a','c','b'),edge('b','e'),edge('b','f'),edge('other','b','b')]};
  past=[];future=[];selected=null;selectedEdge=null;selection.clear();dirty=false;render();setGraphFocus(true);scale=.7;pan={x:80,y:200};transform();
  EDITOR_DEV_SETTINGS.arrowNavigationMode=bidirectional?'branches':'legacy';EDITOR_DEV_SETTINGS.arrowNavigationFrame=false;EDITOR_DEV_SETTINGS.frameDamping=false;selectNode(current().nodes[0]);refreshCanvasSelection();
},bidirectional);await settle();};
const chosen=()=>page.evaluate(()=>({selected,selection:[...selection],edge:selectedEdge}));
const key=async(k,id)=>{await page.keyboard.press(k);assert.deepEqual(await chosen(),{selected:id,selection:[id],edge:null},k+' -> '+id);};
const pick=async id=>page.evaluate(id=>{selectNode(current().nodes.find(n=>n.id===id));refreshCanvasSelection();},id);
const state=()=>page.evaluate(()=>JSON.stringify({graph,past,future,dirty,revision}));
try{
await reset();let before=await state();const view=await page.evaluate(()=>JSON.stringify({pan,scale}));
await key('ArrowDown','a');await key('ArrowRight','b');await key('ArrowDown','c');await key('ArrowDown','d');await key('ArrowDown','d');await key('ArrowUp','c');await key('ArrowUp','b');await key('ArrowUp','b');
assert.equal(await page.evaluate(()=>arrowNavigation.steps[0].from),'a');await key('ArrowLeft','a');
assert.equal(await state(),before);assert.equal(await page.evaluate(()=>JSON.stringify({pan,scale})),view);
checks.push('Right chooses topmost destination regardless of edge order; Up/Down stays in one branch, deduplicates nodes and stops at boundaries without writes or framing');
await key('ArrowRight','b');await key('ArrowRight','e');await key('ArrowDown','f');await key('ArrowLeft','b');await key('ArrowLeft','a');
checks.push('branch changes replace the latest destination; reverse keys retrace the complete path through multi-input nodes');
await pick('b');await key('ArrowLeft','other');await key('ArrowDown','a');await key('ArrowUp','other');await key('ArrowRight','b');
checks.push('upstream navigation is symmetric and returns to the actual downstream origin');
await key('ArrowRight','e');await page.locator('#cards [data-node="e"] .node-title').click();await key('ArrowDown','e');
await page.evaluate(()=>{selection=new Set(['a','b']);selected='b';refreshCanvasSelection();$('#canvas').focus();});let multi=await chosen();await page.keyboard.press('ArrowRight');assert.deepEqual(await chosen(),multi);
await page.evaluate(()=>clearCanvasSelection());await page.keyboard.press('ArrowRight');assert.deepEqual(await chosen(),{selected:null,selection:[],edge:null});
checks.push('fresh mouse selection requires Left/Right; multiple or empty selection never navigates');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{current().edges=current().edges.filter(e=>e.from[0]!=='a'||e.to[0]!=='b');wires();});await key('ArrowDown','b');await key('ArrowLeft','other');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{graph=clone(graph);render();$('#canvas').focus();});await key('ArrowDown','b');
checks.push('deleted connections and replacement/Undo-style graph objects invalidate old navigation paths');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{graph.stages.vertex={nodes:[],edges:[]};stage='vertex';render();stage='pixel';render();selected='b';selection=new Set(['b']);refreshCanvasSelection();$('#canvas').focus();});await key('ArrowDown','b');
await reset();await key('ArrowRight','b');assert.equal(await page.evaluate(()=>change(()=>{current().nodes[0].ui.x+=12;},{localize:false,layout:true})),true);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.evaluate(()=>undo()),true);await page.evaluate(()=>{$('#canvas').focus();});await key('ArrowDown','b');
checks.push('stage round-trips and real Undo do not revive a stale route');
await reset();await page.evaluate(()=>{readonly=true;});await key('ArrowRight','b');await key('ArrowDown','c');assert.equal(await page.evaluate(()=>readonly),true);
checks.push('readonly graphs retain non-mutating navigation');
await reset();await page.evaluate(()=>{current().nodes.find(n=>n.id==='c').ui.y=0;current().nodes.find(n=>n.id==='c').ui.x=400;render();$('#canvas').focus();});await key('ArrowRight','b');await key('ArrowDown','c');await key('ArrowUp','b');
checks.push('equal-height candidates use deterministic X/ID ties and Down/Up is reversible');
await reset();await key('ArrowRight','b');await page.evaluate(()=>{pan={x:pan.x+40,y:pan.y-20};scale=.25;transform();});await key('ArrowDown','c');
await page.evaluate(()=>{current().nodes.find(n=>n.id==='d').ui.y=100;render();$('#canvas').focus();});await key('ArrowUp','d');
checks.push('pan/zoom preserves path context; next key uses current node positions without a presorted cache');
await reset();await key('ArrowRight','b');const input=page.locator('#cards [data-node="a"] input').first();await input.focus();await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');
await page.evaluate(()=>{const e=document.createElement('div');e.id='editable-arrow-test';e.contentEditable='true';$('#canvas').append(e);e.focus();});await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');await page.evaluate(()=>$('#editable-arrow-test').remove());
await page.evaluate(()=>setGraphFocus(false));await page.locator('#uishortcuts').click();await page.keyboard.press('ArrowDown');assert.equal((await chosen()).selected,'b');assert.deepEqual(await page.locator('[data-shortcut="arrowPath"] kbd').allTextContents(),['←','→']);await page.keyboard.press('Escape');
await page.evaluate(()=>{$('#canvas').focus();});await page.keyboard.press('Shift+ArrowDown');assert.equal((await chosen()).selected,'b');
checks.push('number fields, contenteditable, modal Help and modified arrows keep their own key handling; Help lists the new keys');
await reset();before=await state();await page.evaluate(()=>{setUIExperiments({arrowNavigationFrame:true});$('#canvas').focus();});await key('ArrowRight','b');await settle();
const center=await page.evaluate(()=>{const card=$('#cards [data-node="b"]').getBoundingClientRect(),canvas=$('#canvas').getBoundingClientRect();return Math.hypot(card.left+card.width/2-canvas.left-canvas.width/2,card.top+card.height/2-canvas.top-canvas.height/2);});assert.ok(center<2,center);
assert.equal(await state(),before);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(experimentsStorageKey)).arrowNavigationFrame),true);
await page.evaluate(()=>{setUIExperiments({frameDamping:true,frameDampingMs:80});$('#canvas').focus();});await key('ArrowDown','c');assert.equal(await page.evaluate(()=>!!canvasMotion),true);await page.waitForFunction(()=>!canvasMotion);
checks.push('optional persisted auto Frame centers the new node and reuses the existing transition without graph/history writes');
assert.equal(await page.evaluate(()=>EDITOR_DEV_DEFAULTS.arrowNavigationMode),'branches');
await reset(true);before=await state();
await key('ArrowRight','b');await key('ArrowLeft','a');await key('ArrowUp','other');await key('ArrowUp','other');await key('ArrowDown','a');await key('ArrowDown','a');
assert.equal(await page.evaluate(()=>arrowNavigation.branch.from),'b');await key('ArrowRight','b');await key('ArrowDown','c');
assert.equal(await state(),before);
checks.push('trial retains the downstream anchor after returning upstream; Up/Down explores its other inputs without wrap or graph writes');
await key('ArrowLeft','a');await key('ArrowRight','c');await key('ArrowDown','d');await key('ArrowLeft','a');await key('ArrowRight','d');
checks.push('trial reversal remembers the actual lower branch instead of jumping to the topmost destination');
await reset(true);await key('ArrowRight','b');await key('ArrowRight','e');await key('ArrowDown','f');await key('ArrowLeft','b');await key('ArrowRight','f');await key('ArrowLeft','b');await key('ArrowLeft','a');
checks.push('trial preserves nested return paths as well as the most recent horizontal relation');
await reset(true);await page.evaluate(()=>{current().edges.push({from:['a','out'],to:['e','b']});wires();});
await key('ArrowRight','b');await key('ArrowRight','e');await key('ArrowLeft','b');await key('ArrowDown','a');await key('ArrowRight','e');await key('ArrowLeft','a');await key('ArrowUp','b');await key('ArrowLeft','other');
checks.push('trial finds shared downstream inputs even when one is an earlier ancestor, then starts return history from that shared node');
await reset(true);await key('ArrowRight','b');await key('ArrowLeft','a');
await page.evaluate(()=>{current().edges=current().edges.filter(e=>e.from[0]!=='a'||e.to[0]!=='b');wires();});await key('ArrowUp','a');assert.equal(await page.evaluate(()=>arrowNavigation.branch??null),null);
await reset(true);await key('ArrowRight','b');await key('ArrowLeft','a');await pick('a');await key('ArrowUp','a');
checks.push('trial invalidates the independent branch anchor when its connection is deleted or selection restarts');
await reset(true);await key('ArrowRight','b');await key('ArrowLeft','a');before=await state();
await page.evaluate(()=>setGraphFocus(false));await settle();await page.locator('#uiexperiments').click();await settle();
await page.evaluate(()=>{window.arrowTestCard=$('#cards .node');window.arrowTestWire=$('#wires path');});
await page.locator('[data-experiment="arrowNavigationMode"]').selectOption('legacy');
assert.equal(await page.evaluate(()=>arrowNavigation),null);
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(experimentsStorageKey)).arrowNavigationMode),'legacy');
assert.equal(await page.evaluate(()=>window.arrowTestCard===$('#cards .node')&&window.arrowTestWire===$('#wires path')),true);
await page.keyboard.press('Escape');await page.evaluate(()=>$('#canvas').focus());await key('ArrowRight','b');await key('ArrowLeft','a');await key('ArrowUp','a');
await page.locator('#uiexperiments').click();await page.locator('[data-experiment="arrowNavigationMode"]').selectOption('branches');await page.keyboard.press('Escape');await page.evaluate(()=>$('#canvas').focus());
await key('ArrowRight','b');await key('ArrowLeft','a');await key('ArrowUp','other');assert.equal(await state(),before);
assert.equal(await page.evaluate(()=>parseUIExperiments(localStorage.getItem(experimentsStorageKey)).arrowNavigationMode),'branches');
checks.push('trial selector persists, resets only navigation memory, preserves canvas DOM and switches back to the original behavior');
await reset(true);await page.evaluate(()=>{
  setUIExperiments({arrowNavigationMode:'spatial'});
  const n=(id,x,y)=>testNode(id,'add',x,y);
  graph.stages.pixel={nodes:[n('center',0,0),n('left',-360,0),n('right',360,0),n('top',0,-300),n('bottom',0,300)],edges:[]};
  render();selectNode(current().nodes[0]);refreshCanvasSelection();
});before=await state();const spatialView=await page.evaluate(()=>JSON.stringify({pan,scale}));
await key('ArrowRight','right');await key('ArrowRight','right');await key('ArrowLeft','center');await key('ArrowLeft','left');await key('ArrowRight','center');await key('ArrowUp','top');await key('ArrowUp','top');await key('ArrowDown','center');await key('ArrowDown','bottom');
assert.equal(await state(),before);assert.equal(await page.evaluate(()=>JSON.stringify({pan,scale})),spatialView);assert.equal(await page.evaluate(()=>arrowNavigation),null);
checks.push('spatial mode navigates all four directions from a fresh selection without connections, wrapping, history, writes or automatic framing');
await pick('center');await page.evaluate(()=>{current().nodes.push(testNode('diagonal','add',80,140));render();$('#canvas').focus();pan={x:200,y:120};scale=.25;transform();});
await key('ArrowRight','right');await pick('center');await key('ArrowDown','diagonal');
await page.evaluate(()=>{current().nodes.find(n=>n.id==='right').ui.x=400;current().nodes.push(testNode('near','add',250,0));render();$('#canvas').focus();});await pick('center');await key('ArrowRight','near');
checks.push('spatial mode prefers the forward sector, then nearest distance, using current positions independently of zoom');
await page.evaluate(()=>{selection=new Set(['center','near']);selected='near';refreshCanvasSelection();$('#canvas').focus();});const spatialMulti=await chosen();await page.keyboard.press('ArrowRight');assert.deepEqual(await chosen(),spatialMulti);
await page.evaluate(()=>setGraphFocus(false));await page.locator('#uishortcuts').click();assert.match(await page.locator('[data-shortcut="arrowPath"] dt').innerText(),/依位置/);assert.match(await page.locator('[data-shortcut="arrowBranch"] dt').innerText(),/依位置/);await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>parseUIExperiments(localStorage.getItem(experimentsStorageKey)).arrowNavigationMode),'spatial');
checks.push('spatial mode remains single-selection only and its persisted setting is reflected in shortcut Help');
assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks:checks.length}));
}catch(error){await h.finish(error);console.error(error);process.exitCode=1;}})();
