/* Array/structure editor flows in an isolated browser; never touches TD. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const {harness}=require('./test_glsl_code.cjs');
(async()=>{
  const [source,stateFile,folder]=process.argv.slice(2);fs.mkdirSync(folder,{recursive:true});
  const fixture=path.join(folder,'fresh-state.json');execFileSync(process.env.PYTHON_EXECUTABLE||'python',[path.join(__dirname,'export_editor_fixture.py'),stateFile,fixture]);
  const h=await harness(source,fixture,folder),{page,checks,errors,settle}=h;page.setDefaultTimeout(6500);
  const pick=async id=>{await page.evaluate(id=>{selected=id;selection=new Set([id]);inspectorTab='parameters';render();},id);await settle();};
  const state=()=>page.evaluate(()=>JSON.stringify(graph));
  const wire=async(from,to,port,output='out')=>{const result=await page.evaluate(({from,to,port,output})=>connectPorts({node:from,kind:'outputs',port:output},{node:to,kind:'inputs',port}),{from,to,port,output});await settle();return result;};
  try{
    await page.selectOption('#language','en');
    await page.evaluate(()=>{
      clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=nativeMutationBusy=false;graphTrail=[];stage='pixel';past=[];future=[];selected=selectedEdge=null;selection.clear();graph.functions=[];graph.declarations=[];
      graph.typeDefinitions=[{id:'sample',name:'Sample',provider:'generated',fields:[{id:'position',name:'offset',type:'vec2'},{id:'weight',name:'amount',type:'float'}]}];
      graph.stages.pixel={nodes:[testNode('result','pixel_out',1100,70),testNode('array','array',40,70),testNode('get','array_get',420,70),testNode('replace','array_replace',420,360),testNode('length','array_length',40,360),testNode('field','struct_field',800,360),testNode('scalar','scalar',40,640,{type:'float',value:5}),testNode('source','builtin_source',800,70,{source:'uTD2DInfos'})],edges:[]};
      selected='array';selection=new Set(['array']);scale=.7;pan={x:15,y:15};rememberSavedGraph(graph);render();transform();
    });await settle();
    assert.equal(await page.locator('[data-array-summary="array"]').innerText(),'float × 4');
    await page.locator('#inspector [data-array-element-type="array"]').selectOption('vec3');await settle();
    const beforeLength=await state();await page.locator('#inspector [data-array-length="array"]').fill('8');await page.locator('#inspector [data-array-length="array"]').press('Enter');await settle();
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='array'),'outputs').out),'vec3[8]');
    assert.equal(await page.locator('[data-node="array"] input').count(),0);
    await page.evaluate(()=>undo());await settle();assert.equal(await state(),beforeLength);await page.evaluate(()=>undo(true));await settle();
    checks.push('Array element type and fixed length edits are undoable and the canvas shows one compact summary');
    assert.equal(await wire('array','get','Array'),true);assert.equal(await wire('array','replace','Array'),true);assert.equal(await wire('array','length','Array'),true);
    assert.deepEqual(await page.evaluate(()=>['get','replace','length'].map(id=>ports(current().nodes.find(n=>n.id===id),'outputs').out)),['vec3','vec3[8]','int']);
    await pick('replace');assert.equal(await page.locator('#inspector [data-input="replacement"] input[type=number]:visible').count(),3);
    assert.match(await page.locator('#inspector').innerText(),/out-of-range index leaves the array unchanged/);
    await pick('get');assert.match(await page.locator('#inspector').innerText(),/clamped to the array bounds/);
    const beforeInvalid=await state();assert.equal(await wire('scalar','get','Array'),false);assert.equal(await state(),beforeInvalid);
    checks.push('Array consumers infer source element/length, Replace edits a single value, and non-array wires are rejected atomically');
    await pick('array');await page.locator('#inspector [data-array-element-type="array"]').selectOption('struct:sample');await settle();
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='get'),'outputs').out),'struct:sample');
    assert.equal(await wire('get','field','value'),true);await pick('field');
    assert.deepEqual(await page.locator('#inspector [data-struct-field]').locator('option').evaluateAll(es=>es.map(e=>[e.value,e.textContent])),[['position','offset · vec2'],['weight','amount · float']]);
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='field'),'outputs').out),'vec2');
    await page.locator('#inspector [data-struct-field]').selectOption('weight');await settle();
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='field'),'outputs').out),'float');
    assert.equal(await page.locator('[data-node="field"] [data-struct-field]').inputValue(),'weight');
    assert.match(await page.locator('#inspector').innerText(),/Structure type/);assert.doesNotMatch(await page.locator('#inspector').innerText(),/Output type/);
    assert.deepEqual(await page.evaluate(()=>compositeZeroValue('struct:sample[2]')),[{position:[0,0],weight:0},{position:[0,0],weight:0}]);
    await page.screenshot({path:path.join(folder,'array-structure.png')});
    checks.push('Custom structure fields use stable identities, display GLSL names, and propagate typed outputs without dedicated nodes');
    await page.evaluate(()=>{window.testOldPlan=planWireTypes;window.testFullPlans=0;planWireTypes=(...args)=>{testFullPlans++;return testOldPlan(...args);};const r=$('#canvas').getBoundingClientRect();openCreator(r.left+300,r.top+240,{node:'array',port:'out',kind:'outputs',type:ports(current().nodes.find(n=>n.id==='array'),'outputs').out});});await settle();
    await page.locator('#createsearch').fill('array');await settle();
    assert.ok(await page.evaluate(()=>creatorMatches.some(match=>match.d.key==='array_get')));assert.equal(await page.evaluate(()=>testFullPlans),0);
    const beforeCreator=await state();
    await page.evaluate(()=>{planWireTypes=testOldPlan;chooseCreator(creatorMatches.findIndex(match=>match.d.key==='array_get'));});await settle();
    assert.equal(await page.evaluate(()=>{const n=current().nodes.find(n=>n.id===selected);return ports(n,'outputs').out;}),'struct:sample');
    await page.evaluate(()=>undo());await settle();assert.equal(await state(),beforeCreator);
    checks.push('Dragged array search uses local signature matching without any whole-graph connection trials while typing');
    await page.evaluate(()=>{const r=$('#canvas').getBoundingClientRect();openCreator(r.left+400,r.top+330);});await page.locator('#createsearch').fill('array');await settle();
    assert.ok(await page.evaluate(()=>['array','array_get','array_replace','array_length'].every(key=>creatorMatches.some(match=>match.d.key===key))));
    await page.screenshot({path:path.join(folder,'array-creator.png')});
    await page.evaluate(()=>chooseCreator(creatorMatches.findIndex(match=>match.d.key==='array')));await settle();
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id===selected),'outputs').out),'float[4]');await page.evaluate(()=>undo());await settle();assert.equal(await state(),beforeCreator);
    checks.push('Standalone creator lists all array operations and creates the default Array, while wire creation commits an inferred node with one Undo');
    const sources=await page.evaluate(()=>{const def=catalog.find(d=>d.key==='builtin_source'),top=builtinSourceEntries(def).map(d=>d.defaults.source);editorTarget='mat';stage='vertex';const mat=builtinSourceEntries(def).map(d=>d.defaults.source);editorTarget='top';stage='pixel';return {top,mat};});
    assert.ok(sources.top.includes('uTD2DInfos')&&sources.top.includes('sTD2DInputs'));assert.equal(sources.top.includes('uTDMats'),false);assert.ok(sources.mat.includes('uTDMats')&&sources.mat.includes('uTDCamInfos'));assert.equal(sources.mat.includes('uTD2DInfos'),false);
    await page.evaluate(()=>{const n=current().nodes.find(n=>n.id==='source');n.params.source='sTD2DInputs';render();});
    await page.evaluate(()=>{const d=catalog.find(d=>d.key==='array_replace');window.testSamplerVariants=creatorVariants(d,{kind:'outputs',type:'sampler2D[TD_NUM_2D_INPUTS]'});});assert.equal(await page.evaluate(()=>testSamplerVariants.length),0);
    await page.evaluate(()=>{current().nodes.push(testNode('samplerGet','array_get',800,640));render();});
    assert.equal(await wire('source','samplerGet','Array'),true);assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='samplerGet'),'outputs').out),'sampler2D');
    checks.push('Built-in source choices honor TOP/MAT/stage and opaque sampler arrays support reading but cannot be replaced');
    await page.evaluate(()=>openInputCreate('uniform'));await page.locator('#sourcekind').selectOption('array');await page.locator('#sourcetype').selectOption('vec3');await page.locator('#sourcename').fill('uPoints');await page.locator('#sourcearraylength').fill('8');await page.locator('#sourcearraypath').fill('/project1/points');await page.locator('#sourcecreate button[type=submit]').click();await settle();
    const declaration=await page.evaluate(()=>clone(graph.declarations.find(d=>d.name==='uPoints')));assert.equal(declaration.type,'vec3[8]');assert.equal(declaration.nativeSequence,'array');assert.equal(declaration.arraySource,'/project1/points');
    assert.equal(await page.locator('#inspector [data-source-custom]').count(),0);assert.equal(await page.locator('#inspector .input-defaults').count(),0);
    assert.equal(await page.evaluate(()=>{const decl=graph.declarations.find(d=>d.name==='uPoints'),n=testNode('uniformArray','uniform',1100,640,{declarationId:decl.id});current().nodes.push(n);return ports(n,'outputs').out;}),'vec3[8]');
    checks.push('Uniform Array creation records element type, length and CHOP source without presenting scalar sliders or custom-parameter shortcuts');
    await page.evaluate(()=>{const decl=graph.declarations.find(d=>d.name==='uPoints');nativeSourceSnapshot={enabled:true,revision,uniforms:[{...clone(decl),sequence:'array',components:[],arrayBinding:{mode:'CONSTANT',value:decl.arraySource,expression:'',expected:'binding-hash',writable:true,length:8,elementType:'vec3'},nameWritable:true}],specConstants:[]};nativeSourceError='';dirty=false;nativeSourceBusy=false;conflicted=false;selectedInputId=decl.id;selected=null;selection.clear();window.testArrayEdit=null;nativeSourceRequest=async(endpoint,body)=>{testArrayEdit={endpoint,body};return null;};inspector();});await settle();
    assert.equal(await page.locator('#inspector [data-array-binding-editor]').count(),1);assert.equal(await page.locator('#inspector [data-source-component]').count(),0);
    await page.locator('[data-array-binding-editor] input').fill('/project1/newPoints');await page.locator('[data-array-binding-editor] button').click();
    assert.deepEqual(await page.evaluate(()=>({endpoint:testArrayEdit.endpoint,action:testArrayEdit.body.action,value:testArrayEdit.body.value,expected:testArrayEdit.body.expected})),{endpoint:'source-edit',action:'arrayBinding',value:'/project1/newPoints',expected:'binding-hash'});
    checks.push('Native array binding uses the source-edit concurrency token and CHOP binding UI instead of value polling/edit controls');
    await page.evaluate(()=>{
      connectionInterrupted=true;conflicted=true;dirty=false;nativeSourceSnapshot=null;selectedInputId=null;past=[];future=[];
      graph.declarations=[{id:'size',kind:'spec_constant',name:'elementCount',type:'int',value:4,constantId:7},{id:'fixed',kind:'constant',name:'fixedCount',type:'int',value:6}];
      graph.stages.pixel={nodes:[testNode('array','array',40,70),testNode('get','array_get',420,70),testNode('result','pixel_out',800,70)],edges:[]};render();
    });await pick('array');const beforeSymbol=await state();
    await page.locator('#inspector [data-array-length-source]').selectOption('sg_len_size');await settle();
    assert.equal(await page.locator('[data-array-summary="array"]').innerText(),'float × N');
    assert.equal(await page.evaluate(()=>ports(current().nodes[0],'outputs').out),'float[sg_len_size]');
    assert.equal(await page.locator('#inspector [data-array-length="array"]').count(),0);
    await page.evaluate(()=>undo());await settle();assert.equal(await state(),beforeSymbol);await page.evaluate(()=>undo(true));await settle();
    assert.equal(await wire('array','get','Array'),true);
    assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='get'),'outputs').out),'float');
    await page.evaluate(()=>{graph.declarations[0].name='renamedCount';render();});await pick('array');
    assert.equal(await page.evaluate(()=>arrayLengthExpression('sg_len_size')),'renamedCount');
    assert.ok(await page.evaluate(()=>sourceReferences('size').some(n=>n.id==='array')));
    checks.push('Unknown length displays N but retains constant identity, survives Undo and rename, and propagates through array consumers');
    await page.locator('#inspector [data-array-length-source]').selectOption('sg_len_fixed');await settle();
    assert.equal(await page.locator('[data-array-summary="array"]').innerText(),'float × 6');
    assert.equal(await page.evaluate(()=>ports(current().nodes[0],'outputs').out),'float[sg_len_fixed]');
    await page.evaluate(()=>{readonly=true;inspector();});assert.equal(await page.locator('#inspector [data-array-length-source]').isDisabled(),true);await page.evaluate(()=>{readonly=false;inspector();});
    const carrierOptions=await page.evaluate(()=>{const control=arrayLengthControl(4,()=>{},false);return [...control.querySelector('select').options].map(o=>({value:o.value,disabled:o.disabled}));});
    assert.equal(carrierOptions.find(o=>o.value==='sg_len_size').disabled,true);assert.equal(carrierOptions.find(o=>o.value==='sg_len_fixed').disabled,false);
    checks.push('Known Graph Constant length displays its literal, readonly edits stay disabled, and the native carrier blocks only specialization length');
    assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks}));
  }catch(error){await h.finish(error);throw error;}
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
