/* Isolated editor fixture. Never sends graph edits to TouchDesigner. */
const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{skipPreview:true}),{page,checks,errors,settle}=h;page.setDefaultTimeout(7000);
const reset=async()=>{await page.evaluate(()=>{cancelNodePlacement();closeCreator();closeGraphMenu();readonly=false;nativeMutationBusy=false;historyBusy=false;graph.declarations=[];graph.functions=[];stage='pixel';graphTrail=[];graph.stages.pixel={nodes:[testNode('src','scalar',70,90,{value:.375}),testNode('dest','add',650,90),testNode('other','add',650,360),testNode('color','color',70,450,{value:[0,0,0,1]})],edges:[{from:['src','out'],to:['dest','a']},{from:['src','out'],to:['other','a']}]};past=[];future=[];selected=null;selectedEdge=null;selection.clear();dirty=false;rememberSavedGraph(graph);render();setGraphFocus(true);scale=.8;pan={x:40,y:40};transform();});await settle();};
const snapshot=()=>page.evaluate(()=>({graph:JSON.stringify(graph),past:past.length,dirty}));
const port=(id,kind,name)=>page.locator(`#cards [data-node="${id}"] [data-kind="${kind}"][data-port="${name}"]`);
const choose=async(id='src',kind='outputs',name='out',query='Multiply')=>{await port(id,kind,name).click({button:'right'});await page.locator('#createsearch').fill(query);await page.locator('#createresults .create-entry').filter({hasText:query}).first().click();await page.waitForFunction(()=>!!nodePlacement);await settle();};
const wireMenu=async index=>{const p=await page.locator('#wires path[data-from]').nth(index).evaluate(e=>{const p=e.getPointAtLength(e.getTotalLength()/2),q=new DOMPoint(p.x,p.y).matrixTransform(e.getScreenCTM());return{x:q.x,y:q.y};});await page.mouse.click(p.x,p.y,{button:'right'});await page.locator('#grapheditmenu [data-edit="selectSource"]').waitFor();};
try{
await reset();const widths=await page.evaluate(()=>{const card=()=>$('#cards [data-node="color"]'),n=current().nodes.find(n=>n.id==='color'),short=card().offsetWidth;n.params.value=[.07058823529411765,.20392156862745098,.33725490196078434,1];render();const long=card().offsetWidth;n.ui.width=260;render();const manual=card().offsetWidth;n.params.value=[0,0,0,1];render();return{short,long,manual,manualShort:card().offsetWidth};});assert.equal(widths.short,widths.long);assert.equal(widths.manual,260);assert.equal(widths.manualShort,260);checks.push('Color precision never changes automatic or manual width');
await reset();const number=page.locator('#cards [data-node="src"] .numeric-slider').first();await number.dblclick();await page.keyboard.type('0.625');await page.keyboard.press('Enter');await page.keyboard.press('Tab');await settle();assert.equal(await page.evaluate(()=>current().nodes[0].params.value),.625);assert.equal(await page.evaluate(()=>past.length),1);checks.push('two physical clicks from an unfocused slider select the entire value for replacement in one edit');
await reset();let before=await snapshot();await choose();assert.deepEqual(await snapshot(),before);assert.equal(await page.locator('.node-placement-measure').count(),0);await page.mouse.move(1000,540);await settle();await page.screenshot({path:path.join(folder,'placement-dark.png')});const dimensions=await page.locator('.node-placement-outline').evaluate(e=>({width:parseFloat(e.style.width),height:parseFloat(e.style.height)}));await page.mouse.click(1000,540);await settle();assert.equal(await page.locator('.node-placement').count(),0);assert.equal(await page.evaluate(()=>current().nodes.length),5);assert.equal(await page.evaluate(()=>current().edges.length),3);assert.equal(await page.evaluate(()=>past.length),1);const actual=await page.evaluate(()=>{const e=$('#cards [data-node="'+selected+'"]');return{width:e.offsetWidth,height:e.offsetHeight};});assert.equal(actual.width,Math.round(dimensions.width));assert.equal(actual.height,Math.round(dimensions.height));await page.evaluate(()=>undo());assert.equal((await snapshot()).graph,before.graph);await page.evaluate(()=>undo(true));assert.equal(await page.evaluate(()=>current().nodes.length),5);checks.push('right-click output uses measured real geometry, waits for a click, and atomically creates/undoes/redoes one node and wire');
await reset();before=await snapshot();await choose();
const previewStyle=await page.locator('.node-placement-outline').evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor,pointer:getComputedStyle(e).pointerEvents}));
assert.equal(previewStyle.color,'rgb(112, 220, 105)');assert.equal(previewStyle.background,'rgba(0, 0, 0, 0.32)');assert.equal(previewStyle.pointer,'none');
const glass=await page.evaluate(()=>['simple','professional','cool','excellent','legendary','godlike'].map(style=>{document.documentElement.dataset.uiStyle=style;return getComputedStyle($('.node-placement-outline')).backdropFilter;}));
assert.deepEqual(glass,['none','none','none','blur(6px)','blur(6px)','blur(6px)']);await page.screenshot({path:path.join(folder,'placement-glass.png')});await page.evaluate(()=>{document.documentElement.dataset.uiStyle='professional';});
await page.keyboard.press('Escape');assert.deepEqual(await snapshot(),before);assert.equal(await page.locator('.node-placement').count(),0);checks.push('green placement has a translucent black fill; Escape cancels without graph, declarations, dirty state or history changes');
await reset();before=await snapshot();await choose('dest','inputs','a','Scalar');assert.deepEqual(await snapshot(),before);await page.mouse.click(900,640);await settle();assert.equal(await page.evaluate(()=>current().edges.length),2);assert.equal(await page.evaluate(()=>current().edges.find(e=>e.to[0]==='dest').from[0]===selected),true);await page.evaluate(()=>undo());assert.equal((await snapshot()).graph,before.graph);checks.push('input-side creation preserves an occupied input until commit and Undo restores its original edge');
for(const action of ['blur','readonly','graph','outside']){await reset();before=await snapshot();await choose();if(action==='blur')await page.evaluate(()=>window.dispatchEvent(new Event('blur')));if(action==='readonly')await page.evaluate(()=>{readonly=true;});if(action==='graph')await page.evaluate(()=>{graph=clone(graph);render();});if(action==='outside')await page.locator('#graphfocus').click();await page.waitForFunction(()=>!nodePlacement);assert.equal((await snapshot()).graph,before.graph);assert.equal((await snapshot()).past,0);}checks.push('blur, read-only transition, graph replacement and outside interaction cancel placement');
await reset();await choose();const appearance=await page.evaluate(()=>{const root=document.documentElement,outline=$('.node-placement-outline'),title=$('.node-placement-title'),read=()=>({color:getComputedStyle(outline).color,glow:getComputedStyle(outline).boxShadow,text:getComputedStyle(title).textShadow});root.dataset.uiTheme='dark';root.dataset.uiStyle='simple';const simple=read();root.dataset.uiStyle='professional';const professional=read();root.style.setProperty('--purple','#000');root.style.setProperty('--ui-tone-text','#000');const brightness=read();root.dataset.uiTheme='light';const light=read();return{simple,professional,brightness,light};});assert.equal(appearance.simple.glow,'none');assert.equal(appearance.simple.text,'none');assert.notEqual(appearance.professional.glow,'none');assert.deepEqual(appearance.professional,appearance.brightness);assert.notEqual(appearance.light.color,appearance.professional.color);await page.screenshot({path:path.join(folder,'placement-light.png')});await page.keyboard.press('Escape');checks.push('Simple disables placement Glow; Professional enables it; dedicated dark/light accents ignore UI color overrides');
await reset();before=await snapshot();await wireMenu(1);assert.equal(await page.locator('#grapheditmenu>button').count(),3);assert.equal(await page.locator('#grapheditmenu>[role="separator"]').count(),1);await page.locator('[data-edit="selectSource"]').click();assert.deepEqual(await page.evaluate(()=>[...selection]),['src']);assert.deepEqual(await snapshot(),before);await wireMenu(1);await page.locator('[data-edit="selectDestination"]').click();assert.deepEqual(await page.evaluate(()=>[...selection]),['other']);await wireMenu(1);await page.evaluate(()=>{selectedEdge=0;});await page.locator('#grapheditmenu [data-edit="delete"]').click();assert.deepEqual(await page.evaluate(()=>current().edges.map(e=>e.to[0])),['dest']);assert.equal(await page.evaluate(()=>past.length),1);await page.evaluate(()=>undo());assert.equal((await snapshot()).graph,before.graph);checks.push('wire menu selects immediate endpoints; disconnect targets the clicked branch despite selectedEdge changes, with one Undo');
await reset();await wireMenu(0);await page.evaluate(()=>{current().edges.splice(0,1);});const stale=await snapshot();await page.locator('#grapheditmenu [data-edit="delete"]').click();assert.deepEqual(await snapshot(),stale);await reset();await page.evaluate(()=>{readonly=true;render();});await wireMenu(0);assert.equal(await page.locator('#grapheditmenu [data-edit="delete"]').isDisabled(),true);await page.locator('[data-edit="selectDestination"]').click();assert.deepEqual(await page.evaluate(()=>[...selection]),['dest']);checks.push('stale wire menus do nothing; readonly still permits endpoint selection but disables Disconnect');
await reset();const glow=await page.evaluate(()=>{document.documentElement.dataset.uiTheme='dark';document.documentElement.dataset.uiStyle='excellent';const decl={id:'test',kind:'constant',type:'float',name:'Test',value:0},available=sourceCard(decl,null,null,null),key=Object.keys(typeContract.sources.uniformPresets)[0],dormant=sourceCard(null,key,null,null),host=el('div');host.append(available,dormant);document.body.append(host);const result=[available,dormant].map(e=>({available:e.dataset.sourceAvailable,shadow:getComputedStyle(e).boxShadow,text:getComputedStyle(e.querySelector('.input-source-select>span')).textShadow}));host.remove();return result;});assert.equal(glow[0].available,'true');assert.equal(glow[1].available,'false');assert.notEqual(glow[0].shadow,glow[1].shadow);assert.equal(glow[1].text,'none');checks.push('available Source glows; dormant Source has no category/name Glow');
assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks:checks.length}));
}catch(error){await h.finish(error);console.error(error);process.exitCode=1;}})();
