// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='shaders')return res.end(JSON.stringify({projectFile:'Review Project.toe'}));if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});


(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{
const page=await browser.newPage({viewport:{width:1500,height:1000},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.selectOption('#language','en');
const stable=()=>page.evaluate(()=>JSON.stringify({graph,revision,dirty,pan,scale,past,future})),before=await stable();
const height=async id=>(await page.locator(id).boundingBox()).height;
const h=await height('[data-workspace-group=parameters]'),help=await height('[data-workspace-group=help]');await page.locator('#resize-live').focus();await page.keyboard.press('ArrowDown');assert.equal(await height('[data-workspace-group=parameters]'),h+8);assert.equal(await height('[data-workspace-group=help]'),help);
for(let i=0;i<5;i++)await page.selectOption('#language',i%2?'en':'zh-Hant');await page.selectOption('#language','en');const currentHeight=await height('[data-workspace-group=parameters]');await page.locator('#resize-live').focus();await page.keyboard.press('ArrowDown');assert.equal(await height('[data-workspace-group=parameters]'),currentHeight+8);checks.push('Pane resize remains adjacent and each rebuilt separator has one keyboard listener');
await page.locator('#livetoggle').click();await page.locator('#livetoggle').click();assert.equal(await page.locator('#livetoggle').getAttribute('aria-expanded'),'true');
await page.locator('#livetoggle').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#livetoggle').getAttribute('aria-expanded'),'true');
await page.locator('#uniformstoggle').click();await page.locator('#uniformstoggle').click();assert.ok(await page.locator('#pane-uniforms').isVisible());await page.locator('#browsertoggle').click();
checks.push('Single-panel and tabbed headings select or expand; repeated clicks and Space never collapse');
await page.locator('[data-workspace-group=live] .workspace-fold').click();assert.equal(await page.locator('#resize-live').isVisible(),false);assert.equal(await page.locator('#resize-help').isVisible(),true);await page.locator('#livetoggle').click();
for(let mask=0;mask<8;mask++){for(let i=0;i<3;i++){const b=page.locator(['#parametertoggle','#livetoggle','#helptoggle'][i]);if((await b.getAttribute('aria-expanded')==='true')!==!!(mask&(1<<i)))await b.locator('..').locator('.workspace-fold').click();}assert.equal(await page.locator('#parameter-sidebar .panel-divider:visible').count(),Math.max(0,[0,1,2].filter(i=>mask&(1<<i)).length-1));}
assert.equal(await stable(),before);checks.push('All collapse combinations retain valid dividers and preserve Shader graph/view');
const initial=await page.evaluate(()=>workspaceLayout.snapshot());await page.evaluate(()=>{try{workspaceLayout.apply({version:1,left:[{panels:['browser','browser']}],right:[]});}catch{}});assert.deepEqual(await page.evaluate(()=>workspaceLayout.snapshot()),initial);checks.push('Invalid or duplicated panel layouts fail atomically');
await page.evaluate(()=>workspaceLayout.move('parameters','left','browser','after'));await page.locator('[data-node="tint"] .node-title').click();assert.ok(await page.locator('#sidebar-left .node-inspector-title').isVisible());
await page.locator('#togglelibrary').click();assert.equal(await page.locator('#sidebar-left').isVisible(),false);await page.locator('#togglelibrary').click();assert.ok(await page.locator('#sidebar-left .node-inspector-title').isVisible());checks.push('Node parameters continue to work in the left sidebar and follow its visibility button');
await page.evaluate(()=>openCreator(400,200,{node:'uv',port:'out',kind:'outputs',type:'vec2'}));await page.locator('#createsearch').fill('multiply');await page.locator('[data-create-entry="multiply"]').click();assert.ok(await page.evaluate(()=>current().edges.some(e=>e.from[0]==='uv'&&current().nodes.find(n=>n.id===e.to[0])?.definitionUuid==='sgrape.builtin.multiply')));
await page.evaluate(()=>openCreator(400,200,{node:'pixel',port:'color',kind:'inputs',type:'vec4'}));await page.locator('#createsearch').fill('Color RGBA');await page.locator('[data-create-entry="color"]').click();assert.ok(await page.evaluate(()=>current().edges.some(e=>e.to[0]==='pixel'&&current().nodes.find(n=>n.id===e.from[0])?.definitionUuid==='sgrape.builtin.color')));checks.push('Column creator retains forward and reverse wire-compatible insertion');
await page.setViewportSize({width:390,height:740});await page.locator('#togglelibrary').click();await page.evaluate(()=>workspaceLayout.move('browser','right'));await page.locator('#toggledetails').click();await page.evaluate(()=>addNode(availableEntries().find(d=>d.key==='float'),100,100));assert.equal(await page.locator('#parameter-sidebar').isVisible(),false);checks.push('Mobile Add Node dismisses the sidebar that actually contains its browser');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));
}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.stack},null,2));console.error(e.stack);process.exitCode=1;}finally{await browser.close();await new Promise(r=>server.close(r));}})();
