// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.evaluate(()=>{window.testInitial=clone(graph);});

await page.locator('[data-node="filter"] .node-title').click();assert.equal(await page.locator('[data-function-name]').inputValue(),'Tint');checks.push('Function name is directly available on the selected call Parameter');
await page.evaluate(()=>duplicateSelection());const oldId=await page.evaluate(()=>current().nodes.find(n=>n.id==='filter').params.functionId);await page.locator('[data-function-name]').fill('色調控制');await page.locator('[data-function-name]').press('Enter');
const renamed=await page.evaluate(old=>({source:FunctionModel.find(graph,old),calls:current().nodes.filter(n=>n.definitionUuid===FunctionModel.CALL).map(n=>n.params.functionId),functions:graph.functions}),oldId);
assert.equal(renamed.source.name,'Tint');assert.equal(new Set(renamed.calls).size,1);assert.notEqual(renamed.calls[0],oldId);assert.equal(renamed.functions.find(f=>f.id===renamed.calls[0]).name,'色調控制');assert.equal(await page.locator('.node-function-name', {hasText:'色調控制'}).count(),2);checks.push('renaming a source Function localizes all Shader calls together and preserves the source snapshot');
const stableId=renamed.calls[0],before=await page.evaluate(()=>clone(graph));await page.locator('[data-function-name]').fill('Final Tint');await page.locator('[data-function-name]').press('Enter');assert.ok(await page.evaluate(id=>current().nodes.filter(n=>n.definitionUuid===FunctionModel.CALL).every(n=>n.params.functionId===id),stableId));const after=await page.evaluate(()=>clone(graph));const stripped=x=>{x=structuredClone(x);for(const f of x.functions)delete f.name;return x;};assert.deepEqual(stripped(before),stripped(after));fs.writeFileSync(path.join(folder,'rename-graphs.json'),JSON.stringify({before,after}));checks.push('local Function rename preserves IDs, all call references, ports, edges and values');
await page.locator('#undo').click();assert.equal(await page.locator('[data-function-name]').inputValue(),'色調控制');await page.locator('#redo').click();assert.equal(await page.locator('[data-function-name]').inputValue(),'Final Tint');checks.push('rename is a single Undo/Redo transaction');
const history=await page.evaluate(()=>past.length);await page.locator('[data-function-name]').fill('   ');await page.locator('[data-function-name]').press('Enter');assert.equal(await page.locator('[data-function-name]').inputValue(),'Final Tint');assert.equal(await page.evaluate(()=>past.length),history);checks.push('empty Function names are rejected without changing references or history');
await page.evaluate(()=>{enterFunction(current().nodes.find(n=>n.id==='filter'));selected='input';selection=new Set(['input']);inspector();});await page.locator('[data-function-name]').fill('Nested Rename');await page.locator('[data-function-name]').press('Enter');assert.ok((await page.locator('#graphpath').innerText()).includes('Nested Rename'));assert.equal(await page.evaluate(()=>currentFunction().id),stableId);checks.push('renaming inside a Function updates graph breadcrumbs with the same local identity');
await page.evaluate(()=>navigateGraph(0));await page.locator('[data-node="filter"] .node-title').click({button:'right'});await page.locator('[data-edit="rename"]').click();assert.equal(await page.locator('[data-function-name]').evaluate(e=>e===document.activeElement),true);checks.push('right-click Rename Function opens and focuses the same Parameter control');
await page.screenshot({path:path.join(folder,'function-name.png')});await page.evaluate(()=>{readonly=true;inspector();});assert.equal(await page.locator('[data-function-name]').isDisabled(),true);checks.push('read-only graphs do not allow Function renaming');

assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});