const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const [source,fixture,w]=process.argv.slice(2);fs.mkdirSync(w,{recursive:true});let state=JSON.parse(fs.readFileSync(fixture,'utf8'));fs.writeFileSync(path.join(w,'fixture.json'),JSON.stringify(state));
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const b of req)raw+=b;const op=name.split('/').at(-1);if(op==='state')return res.end(JSON.stringify(state));if(op==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));res.statusCode=404;return res.end('{}');}const file=path.join(source,name==='/'?'index.html':path.basename(name));if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'application/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),errors=[],checks=[];let page;
try{page=await browser.newPage({viewport:{width:1700,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');
await page.selectOption('#language','en');await page.evaluate(()=>{applyGraph=async()=>{};clearTimeout(autoTimer);window.originalGraph=clone(graph);window.reset=()=>{graph=clone(originalGraph);stage='pixel';graphTrail=[];past=[];future=[];selected=null;selection.clear();dirty=false;readonly=false;inspectorScope='node';inspectorTab='parameters';render();fit();};});
assert.deepEqual(await page.evaluate(()=>graph),state.state.graph);checks.push('Loading old graphs does not migrate their nodes or sources');
assert.deepEqual(await page.evaluate(()=>availableEntries().filter(d=>['texture','texture_sample','sampler'].includes(d.key)).map(d=>d.key).sort()),['sampler','texture_sample']);checks.push('New node menus offer separate source and sampling nodes');
await page.evaluate(()=>{selected='texture';selection=new Set(['texture']);inspectorScope='node';inspectorTab='parameters';render();workspaceLayout.reveal('parameters');});
await page.getByRole('button',{name:'Separate Sampler',exact:true}).click();
const split=await page.evaluate(()=>({graph:clone(graph),history:past.length,types:ports(current().nodes.find(n=>n.id==='texture'),'inputs')}));
assert.equal(split.history,1);assert.deepEqual(split.types,{sampler:'sampler2D',uv:'vec2'});assert.equal(split.graph.declarations[0].id,'texture_main');assert.equal(split.graph.declarations[0].source,'input:0');assert.equal(split.graph.stages.pixel.nodes.find(n=>n.id==='texture').definitionUuid,'sgrape.builtin.texture_sample');checks.push('Explicit legacy split preserves source identity, image settings, UV wiring and the sampling node ID');
assert.equal(await page.locator('[data-input="sampler"] input').count(),0);assert.match(await page.locator('[data-input="sampler"]').innerText(),/opaque black/);checks.push('Sampler sockets expose no numeric default editor');
await page.evaluate(()=>undo());assert.deepEqual(await page.evaluate(()=>graph),state.state.graph);await page.evaluate(()=>undo(true));assert.deepEqual(await page.evaluate(()=>graph),split.graph);checks.push('Split is one reversible edit');
// Select the source and operations together: sources remain outside the packed graph.
await page.evaluate(()=>{selection=new Set(current().nodes.filter(n=>!definition(n).key.endsWith('_out')).map(n=>n.id));groupSelection();render();});
const grouped=await page.evaluate(()=>{const f=graph.functions.at(-1);return {graph:clone(graph),f:clone(f),outside:current().nodes.map(n=>definition(n).key)};});
assert(grouped.outside.includes('sampler'));assert(!grouped.f.graph.nodes.some(n=>n.definitionUuid==='sgrape.builtin.sampler'));assert(grouped.f.inputs.some(p=>p.name==='uTexture'&&p.type==='sampler2D'&&p.default===null));checks.push('Grouping leaves Sampler outside and names its input after the source');
await page.evaluate(()=>{enterFunction(current().nodes.find(n=>n.definitionUuid===FunctionModel.CALL));selected=current().nodes.find(n=>n.definitionUuid===FunctionModel.INPUT).id;selection=new Set([selected]);inspectorScope='node';inspectorTab='settings';render();workspaceLayout.reveal('parameters');});
assert(await page.locator('#inspector select option[value="sampler2D"]').count()>0);assert.deepEqual(await page.evaluate(()=>[convertValue(null,'float'),convertValue(null,'vec4'),convertValue([1,2,3,4],'sampler2D')]),[0,[0,0,0,0],null]);checks.push('Subgraph interface type editor includes sampler2D and restores valid numeric defaults');
await page.evaluate(()=>{navigateGraph(0);selection=new Set(current().nodes.filter(n=>!definition(n).key.endsWith('_out')).map(n=>n.id));selected=[...selection][0];copyGraphSelection();pasteGraphSelection(editorClipboard,{x:900,y:700});});
assert.equal(await page.evaluate(()=>graph.functions.length),1);assert.equal(await page.evaluate(()=>current().nodes.filter(n=>n.definitionUuid===FunctionModel.CALL).length),2);checks.push('Same-Shader copy/paste retains the shared sampler interface definition');
const pasted=await page.evaluate(()=>clone(graph));
await page.evaluate(()=>{reset();graph.declarations=[];const source=instantiate(catalog.find(d=>d.key==='sampler'),60,600);newSampler(source);render();});
const created=await page.evaluate(()=>({g:clone(graph),source:clone(current().nodes.find(n=>n.id===selected))}));assert.equal(created.g.declarations.length,2);assert(created.g.declarations.every(d=>d.source==='builtin:black'));assert.notEqual(created.g.declarations[0].id,created.source.params.declarationId);checks.push('Independent sampler sources can be created with an opaque-black default');
await page.selectOption('#language','zh-Hant');assert.equal(await page.getByRole('button',{name:'新增 Sampler 來源',exact:true}).count(),1);checks.push('Sampler controls localize correctly');
// Save valid, UI-produced cases for compiler/native checks (the deliberate deletion above is not a valid final graph).
fs.writeFileSync(path.join(w,'browser-graphs.json'),JSON.stringify([split.graph,grouped.graph,pasted]));
await page.evaluate(()=>{graph=clone(originalGraph);splitLegacyTexture(current().nodes.find(n=>n.id==='texture'));render();fit();});await page.screenshot({path:path.join(w,'sampler-split.png')});assert.deepEqual(errors,[]);
fs.writeFileSync(path.join(w,'browser-result.json'),JSON.stringify({passed:true,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));
}catch(e){if(page)await page.screenshot({path:path.join(w,'browser-failure.png')});fs.writeFileSync(path.join(w,'browser-result.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));throw e;}
finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
