const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{touch:true}),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const card=id=>page.locator('[data-node="'+id+'"]'),handle=id=>page.locator('[data-node-resize="'+id+'"]');
const worldWidth=id=>card(id).evaluate(e=>e.getBoundingClientRect().width/scale);
const center=async id=>{const r=await handle(id).boundingBox();return{x:r.x+r.width/2,y:r.y+r.height/2};};
const start=async id=>{const p=await center(id);await page.mouse.move(p.x,p.y);await page.mouse.down();return p;};
const drag=async(id,dx)=>{const p=await start(id);await page.mouse.move(p.x+dx,p.y,{steps:4});await page.mouse.up();await settle();};
const fixture=()=>{readonly=false;historyBusy=false;nativeMutationBusy=false;graph.functions=[];graph.declarations=[];graph.stages.pixel={nodes:[testNode('vector','vector',40,40,{type:'vec4',components:[0.123456,123.456,0,0]}),testNode('split','vector_split',530,40,{type:'vec4'}),testNode('color','color',40,360),testNode('add','add',530,300),testNode('uv','uv',40,620),testNode('power','pow',530,550)],edges:[{from:['vector','out'],to:['split','value']}]};stage='pixel';graphTrail=[];past=[];future=[];selected=null;selection.clear();dirty=false;rememberSavedGraph(graph);render();scale=.5;pan={x:40,y:60};transform();};
const defaultLayout=async target=>target.locator('#cards .node').evaluateAll(cards=>cards.map(c=>{
  const bounds=c.getBoundingClientRect(),title=c.querySelector('.node-title'),titleBounds=title.getBoundingClientRect(),name=c.querySelector('.node-title-text'),meta=c.querySelector('.node-title-meta');
  const labels=[...c.querySelectorAll('.node-function-title,.node-function-name,.node-prototype,.node-source-subtitle,.port-label,.port-type')].filter(e=>e.getClientRects().length&&e.textContent.trim()).map(e=>{
    const r=e.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(e);const text=range.getBoundingClientRect();
    return{text:e.textContent,clipped:e.scrollWidth>e.clientWidth+1||text.left<r.left-1||text.right>r.right+1||r.left<bounds.left-1||r.right>bounds.right+1};
  });
  const context=document.createElement('canvas').getContext('2d'),fields=[...c.querySelectorAll('.node-inline-values input')].filter(e=>e.getClientRects().length).map(e=>{const s=getComputedStyle(e);context.font=s.font;const available=e.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight);return{value:e.value,available,required:context.measureText(e.value).width};});
  const uv=[...title.querySelectorAll('small')].find(e=>e.textContent==='vUV.st'),ur=uv?.getBoundingClientRect(),nr=name.getBoundingClientRect(),mr=meta?.getBoundingClientRect();
  return{id:c.dataset.node,minimum:Number(c.dataset.nodeMinWidth),preferred:Number(c.dataset.nodeDefaultWidth),width:bounds.width/scale,headerHeight:titleBounds.height/scale,labels,fields,headerOverlap:!!mr&&nr.right>mr.left+1,uvInline:!ur||(ur.left>=nr.right-1&&Math.abs((ur.top+ur.bottom)-(nr.top+nr.bottom))<2)};
}));
const assertDefaultLayout=layout=>{
  for(const item of layout){assert.ok(item.width>=item.minimum,item.id);assert.equal(item.width,item.preferred,item.id);assert.equal(item.headerOverlap,false,item.id+' header overlap');assert.ok(item.labels.every(label=>!label.clipped),JSON.stringify(item));assert.ok(item.fields.every(field=>field.required<=field.available+1),JSON.stringify(item));}
  const heights=layout.map(item=>item.headerHeight);assert.ok(heights.every(height=>Math.abs(height-41)<.1),JSON.stringify(layout.map(({id,headerHeight})=>({id,headerHeight}))));assert.equal(layout.find(item=>item.id==='uv').uvInline,true,'UV expression stays beside the node name');
};
try{
await page.evaluate(fixture);
const initialLayout=await defaultLayout(page),minimums=Object.fromEntries(initialLayout.map(item=>[item.id,item]));assertDefaultLayout(initialLayout);
assert.equal(minimums.vector.minimum,230);assert.equal(minimums.color.minimum,230);assert.equal(minimums.add.minimum,190);assert.ok(initialLayout.some(item=>item.width>item.minimum),'At least one full node needs a preferred width above its drag minimum');
checks.push('Default widths fit full header and port labels while preserving the existing 190/230 drag minimums; UV metadata stays inline');
assert.match((await card('vector').locator('.node-title').innerText()).replace(/\s+/g,' '),/Constant\s*·/);assert.match((await card('add').locator('.node-title').innerText()).replace(/\s+/g,' '),/GLSL\s*·/);assert.equal(await card('vector').locator('.port-row.output .port-label').innerText(),'out');checks.push('Type selectors follow their Constant/GLSL affiliation and Vector uses the out output label');
let desktopLayout;const desktop=await harness(source,stateFile,path.join(folder,'desktop'),{touch:false});
try{await desktop.page.evaluate(fixture);desktopLayout=await defaultLayout(desktop.page);assertDefaultLayout(desktopLayout);assert.equal(desktopLayout[0].headerHeight,initialLayout[0].headerHeight);assert.equal(await page.evaluate(()=>matchMedia('(pointer:coarse)').matches),true);assert.equal(await desktop.page.evaluate(()=>matchMedia('(pointer:coarse)').matches),false);assert.equal(await desktop.page.locator('.node-size-probe').count(),0);assert.deepEqual(desktop.errors,[]);await desktop.page.screenshot({path:path.join(folder,'default-width-desktop.png')});await desktop.finish();}catch(error){await desktop.finish(error);throw error;}
fs.writeFileSync(path.join(folder,'default-layout.json'),JSON.stringify({coarse:initialLayout,desktop:desktopLayout},null,2));await page.screenshot({path:path.join(folder,'default-width-touch.png')});assert.equal(await page.locator('.node-size-probe').count(),0);assert.equal(await page.evaluate(()=>current().nodes.every(n=>!Object.hasOwn(n.ui,'width'))),true);
checks.push('Headers with selectors, plain names and UV metadata share one height on desktop and coarse touch pointers');
const wider=initialLayout.find(item=>item.width>item.minimum);await drag(wider.id,-200);assert.equal(await worldWidth(wider.id),wider.minimum);assert.equal(await page.evaluate(id=>current().nodes.find(n=>n.id===id).ui.width,wider.id),wider.minimum);assert.ok(await worldWidth(wider.id)<wider.preferred);await page.evaluate(()=>undo());assert.equal(await worldWidth(wider.id),wider.preferred);await page.evaluate(()=>{past=[];future=[];dirty=false;});checks.push('A manual override can shrink below the readable default to the original minimum, and Undo restores the default');
const vectorDefault=minimums.vector.width,vectorExpanded=Math.round(vectorDefault+160);
const before=await page.evaluate(()=>({graph:JSON.stringify(graph),content:graphContent(graph),history:past.length,position:[current().nodes[0].ui.x,current().nodes[0].ui.y],pan:{...pan},wire:$('#wires path').getAttribute('d')}));
const p=await start('vector');await page.mouse.move(p.x+80,p.y,{steps:5});assert.equal(await worldWidth('vector'),vectorExpanded);assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before.graph);assert.equal(await page.evaluate(()=>past.length),0);assert.notEqual(await page.locator('#wires path').getAttribute('d'),before.wire);assert.equal(await handle('vector').evaluate(e=>e.hasPointerCapture(1)),true);checks.push('At 50% zoom, 80 screen pixels previews 160 graph pixels and updates wires without changing graph/history');
await page.mouse.up();await settle();assert.equal(await page.evaluate(()=>current().nodes[0].ui.width),vectorExpanded);assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.evaluate(()=>graphContent(graph)),before.content);assert.equal(await page.evaluate(()=>hasShaderChanges(graph)),false);assert.deepEqual(await page.evaluate(()=>[current().nodes[0].ui.x,current().nodes[0].ui.y]),before.position);assert.deepEqual(await page.evaluate(()=>pan),before.pan);assert.equal(await page.evaluate(()=>dirty),true);checks.push('Release writes one layout-only Undo step, preserves node position/pan and does not mark Shader semantics changed');
await page.evaluate(()=>undo());assert.equal(await worldWidth('vector'),vectorDefault);assert.equal(await page.evaluate(()=>Object.hasOwn(current().nodes[0].ui,'width')),false);await page.evaluate(()=>undo(true));assert.equal(await worldWidth('vector'),vectorExpanded);await page.evaluate(()=>render());assert.equal(await worldWidth('vector'),vectorExpanded);checks.push('Undo, Redo and redraw preserve the width override exactly');
await drag('vector',-(vectorExpanded-minimums.vector.minimum+30)/2);assert.equal(await worldWidth('vector'),230);assert.equal(await page.evaluate(()=>current().nodes[0].ui.width),230);const atMin=await page.evaluate(()=>past.length);await drag('vector',-30);assert.equal(await page.evaluate(()=>past.length),atMin);checks.push('Shrinking stops at each node minimum and a clamped no-op adds no Undo entry');
await drag('vector',800);assert.equal(await worldWidth('vector'),1200);assert.equal(await page.evaluate(()=>current().nodes[0].ui.width),1200);const atMax=await page.evaluate(()=>past.length);await drag('vector',30);assert.equal(await worldWidth('vector'),1200);assert.equal(await page.evaluate(()=>past.length),atMax);await page.evaluate(()=>render());assert.equal(await worldWidth('vector'),1200);await page.evaluate(()=>undo());assert.equal(await worldWidth('vector'),230);checks.push('Enlarging clamps at the loose 1200px maximum, persists across redraw and adds no Undo step when already clamped');
await drag('vector',55);const stable=await page.evaluate(()=>({graph:JSON.stringify(graph),history:past.length,dirty})),stableWidth=await worldWidth('vector');
for(const reason of ['Escape','blur','pointercancel','lostpointercapture']){
  const point=await start('vector');await page.mouse.move(point.x+30,point.y,{steps:3});assert.ok(await worldWidth('vector')>stableWidth);
  if(reason==='Escape')await page.keyboard.press('Escape');
  else if(reason==='blur')await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  else if(reason==='pointercancel')await handle('vector').evaluate(e=>e.dispatchEvent(new PointerEvent('pointercancel',{pointerId:1,bubbles:true})));
  else await handle('vector').evaluate(e=>e.releasePointerCapture(1));
  await page.mouse.up();await settle();assert.equal(await worldWidth('vector'),stableWidth);assert.deepEqual(await page.evaluate(()=>({graph:JSON.stringify(graph),history:past.length,dirty})),stable);
}checks.push('Escape, window blur, pointercancel and capture loss restore the exact previous view without a graph/history edit');
await page.evaluate(()=>{readonly=true;render();});assert.equal(await page.locator('.node-resize-handle').count(),0);assert.equal(await worldWidth('vector'),stableWidth);await page.evaluate(()=>{readonly=false;render();scale=1;transform();});checks.push('Read-only graphs preserve saved widths and expose no resize controls');
const cdp=await page.context().newCDPSession(page),touchPoint=await center('vector'),touchBefore=await page.evaluate(()=>({pan:{...pan},history:past.length,width:current().nodes[0].ui.width}));
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchPoint.x,y:touchPoint.y,id:7}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchPoint.x+40,y:touchPoint.y,id:7}]});assert.equal(await worldWidth('vector'),touchBefore.width+40);assert.equal(await page.evaluate(()=>past.length),touchBefore.history);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();assert.equal(await page.evaluate(()=>current().nodes[0].ui.width),touchBefore.width+40);assert.equal(await page.evaluate(()=>past.length),touchBefore.history+1);assert.deepEqual(await page.evaluate(()=>pan),touchBefore.pan);checks.push('Trusted touch resizing uses the handle without starting canvas pan or node movement');

const field=page.locator('[data-inline-node="vector"][data-component="0"]');await field.focus();await field.fill('0.75');const valueBefore=await page.evaluate(()=>({value:current().nodes[0].params.components[0],history:past.length}));await drag('vector',40);assert.equal(await field.inputValue(),'0.75');assert.equal(await page.evaluate(()=>current().nodes[0].params.components[0]),valueBefore.value);assert.equal(await page.evaluate(()=>past.length),valueBefore.history+1);assert.equal(await worldWidth('vector'),touchBefore.width+80);await field.press('Enter');await field.blur();await settle();assert.equal(await page.evaluate(()=>current().nodes[0].params.components[0]),.75);assert.equal(await worldWidth('vector'),touchBefore.width+80);checks.push('An uncommitted inline value survives resizing; the width persists even when numeric focus defers rendering');
await drag('vector',430);await page.locator('#fit').click();const fitted=await page.evaluate(()=>{const canvas=$('#canvas').getBoundingClientRect();return [...document.querySelectorAll('#cards .node')].map(e=>{const r=e.getBoundingClientRect();return{id:e.dataset.node,inside:r.left>=canvas.left&&r.right<=canvas.right&&r.top>=canvas.top&&r.bottom<=canvas.bottom};});});assert.ok(fitted.every(n=>n.inside),JSON.stringify(fitted));checks.push('Fit uses the enlarged card width so all node borders remain inside the canvas');
const selector=page.locator('[data-node-selector="vector"]'),selectorStyle=await selector.evaluate(e=>{const s=getComputedStyle(e);return{border:s.borderWidth,background:s.backgroundColor};});assert.equal(selectorStyle.border,'0px');assert.equal(selectorStyle.background,'rgba(0, 0, 0, 0)');await selector.selectOption('vec3');assert.equal(await page.evaluate(()=>current().nodes[0].params.type),'vec3');assert.equal(await page.evaluate(()=>current().edges.length),1);checks.push('The transparent borderless header selector remains usable and preserves the existing type-draft policy');
await selector.selectOption('vec4');await page.evaluate(()=>{current().nodes.find(n=>n.id==='split').ui.x=1010;current().nodes.find(n=>n.id==='add').ui.x=1010;render();fit();});assert.equal(await page.locator('.node-size-probe').count(),0);await page.screenshot({path:path.join(folder,'node-width.png')});assert.equal(errors.length,0,errors.join('\n'));await h.finish();console.log(JSON.stringify({passed:true,count:checks.length,checks,errors,defaultWidths:initialLayout.map(({id,width,minimum,headerHeight})=>({id,width,minimum,headerHeight})),desktopWidths:desktopLayout.map(({id,width})=>({id,width}))}));
}catch(error){await h.finish(error);console.error(error);process.exitCode=1;}})();
