/* Canvas context actions reuse toolbar icons and preserve keyboard navigation. */
const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const[source,stateFile,folder]=process.argv.slice(2);
(async()=>{
  const h=await harness(source,stateFile,folder),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
  const open=async()=>{await page.evaluate(()=>{const r=$('#canvas').getBoundingClientRect();openGraphMenu(r.left+260,r.top+180);});await settle();};
  try{
    await page.selectOption('#language','en');await page.evaluate(()=>{
      clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;graphTrail=[];stage='pixel';graph.functions=[];graph.declarations=[];
      const a=testNode('a','float',100,100),b=testNode('b','float',500,100);b.ui.collapsed=true;
      graph.stages.pixel={nodes:[a,b,testNode('output','pixel_out',1000,150)],edges:[]};selection=new Set(['a','b']);selected='a';past=[];future=[];rememberSavedGraph(graph);render();fit();
    });await settle();const before=await page.evaluate(()=>JSON.stringify({graph,past,future,selection:[...selection]}));await open();
    const items=await page.locator('#grapheditmenu [data-edit]').evaluateAll(es=>es.map(e=>({action:e.dataset.edit,icons:e.querySelectorAll('svg').length,hidden:e.querySelector('svg')?.getAttribute('aria-hidden'),label:e.querySelector('.graph-menu-label').textContent,shortcut:e.querySelector(':scope>small').textContent})));
    assert.deepEqual(items.map(i=>i.action),['add','copy','paste','duplicate','collapse','expand','arrange','frame','group','fitAll','fit','focus','fullscreen','delete']);
    for(const item of items){assert.equal(item.icons,1);assert.equal(item.hidden,'true');assert.ok(item.label);}
    assert.equal(items.find(i=>i.action==='copy').shortcut,'Ctrl＋C');assert.ok(!items[0].label.startsWith('＋'));
    for(const [action,id] of Object.entries({copy:'graphcopy',paste:'graphpaste',group:'graphgroup',delete:'graphdelete',collapse:'graphcollapseselection',expand:'graphexpandselection'}))assert.equal(await page.locator(`#grapheditmenu [data-edit="${action}"] svg`).innerHTML(),await page.locator(`#${id} svg`).innerHTML());
    checks.push('Canvas context actions display one decorative icon; shared actions exactly reuse toolbar SVGs and preserve shortcut text');
    await page.screenshot({path:path.join(folder,'context-icons.png')});
    await page.keyboard.press('End');assert.equal(await page.locator('#grapheditmenu [data-edit="delete"]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Home');assert.equal(await page.locator('#grapheditmenu [data-edit="add"]').evaluate(e=>e===document.activeElement),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#grapheditmenu').count(),0);assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future,selection:[...selection]})),before);
    checks.push('Icons do not change selection/history, keyboard Home/End navigation or Escape dismissal');
    await open();await page.locator('#grapheditmenu [data-edit="arrange"]').focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#grapharrangesubmenu').isVisible(),true);
    assert.equal(await page.locator('#grapharrangesubmenu [data-arrange="spaceX"]').isDisabled(),true);
    await page.keyboard.press('ArrowLeft');assert.equal(await page.locator('#grapharrangesubmenu').isVisible(),false);
    await page.locator('#grapheditmenu [data-edit="arrange"]').click();await page.locator('#grapharrangesubmenu [data-arrange="left"]').click();await settle();
    assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='a').ui.x===current().nodes.find(n=>n.id==='b').ui.x),true);
    assert.equal(await page.evaluate(()=>past.length),1);await page.evaluate(()=>undo());await settle();
    assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future:[],selection:[...selection]})),before);
    checks.push('Arrange submenu supports keyboard and pointer entry, enforces group size, and uses one undoable existing arrange transaction');
    const graphBeforeFit=await page.evaluate(()=>JSON.stringify(graph));await page.evaluate(()=>{pan={x:5000,y:5000};transform();});await open();await page.locator('#grapheditmenu [data-edit="fit"]').click();await settle();
    assert.equal(await page.evaluate(()=>JSON.stringify(graph)),graphBeforeFit);assert.ok(await page.evaluate(()=>Math.abs(pan.x)<5000));
    await page.setViewportSize({width:660,height:580});await page.evaluate(()=>openGraphMenu(innerWidth-8,innerHeight-8,null,{touch:true}));
    await page.locator('#grapheditmenu [data-edit="arrange"]').click();
    const bounds=await page.locator('#grapharrangesubmenu').boundingBox();assert.ok(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=660&&bounds.y+bounds.height<=580,JSON.stringify(bounds));
    assert.ok(await page.locator('#grapharrangesubmenu button').first().evaluate(e=>e.offsetHeight>=44));
    await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.setViewportSize({width:1500,height:1000});
    checks.push('Fit selection only changes the viewport; nested menus stay within a narrow viewport and retain touch-sized rows');
    await open();await page.locator('#grapheditmenu [data-edit="arrange"]').click();await page.evaluate(()=>{selection=new Set(['a']);selected='a';});
    await page.locator('#grapharrangesubmenu [data-arrange="left"]').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),graphBeforeFit);
    checks.push('A stale submenu cannot rearrange a different selection');
    await page.evaluate(()=>{selection=new Set(['a','b']);selected='a';render();});await open();await page.locator('#grapheditmenu [data-edit="frame"]').click();await page.keyboard.press('Escape');await settle();
    assert.deepEqual(await page.evaluate(()=>GraphFrames.read(current())[0].nodes),['a','b']);
    await page.evaluate(()=>{selection=new Set(['a']);selected='a';render();});await open();await page.locator('#grapheditmenu [data-edit="detachFrame"]').click();await settle();
    assert.deepEqual(await page.evaluate(()=>GraphFrames.read(current())[0].nodes),['b']);
    await page.evaluate(()=>{selection=new Set(['a','b']);selected='a';render();});await open();await page.locator('#grapheditmenu [data-edit="joinFrame"]').click();await settle();
    assert.deepEqual(await page.evaluate(()=>[...GraphFrames.read(current())[0].nodes].sort()),['a','b']);
    await page.evaluate(()=>{undo();undo();undo();});await settle();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),graphBeforeFit);
    checks.push('Create, detach and join group-frame entries use existing actions and Undo restores the original graph');
    await page.evaluate(()=>{newFunction();closeGraphMenu();});await settle();await open();assert.equal(await page.locator('#grapheditmenu [data-edit="rename"] svg').count(),1);await page.keyboard.press('Escape');
    await page.evaluate(()=>{readonly=true;});await open();assert.equal(await page.locator('#grapheditmenu [data-edit="delete"]').isDisabled(),true);assert.equal(await page.locator('#grapheditmenu [data-edit="delete"] svg').count(),1);
    const geometry=await page.locator('#grapheditmenu button').evaluateAll(es=>es.map(e=>({width:e.clientWidth,scroll:e.scrollWidth})));assert.ok(geometry.every(g=>g.scroll<=g.width+1));
    checks.push('Rename has the same pencil as group frames, disabled actions retain icons, and menu contents fit their rows');
    await page.keyboard.press('Escape');await page.evaluate(()=>{selection.clear();selected=null;selectedEdge=null;render();pan={x:5000,y:5000};transform();});await settle();
    const viewBefore=await page.evaluate(()=>JSON.stringify({graph,past,future,selection:[...selection]}));
    await open();assert.equal(await page.locator('#grapheditmenu [data-edit="fit"]').count(),0);
    assert.equal(await page.locator('#grapheditmenu [data-edit="fitAll"]').getAttribute('aria-keyshortcuts'),'H');
    await page.locator('#grapheditmenu [data-edit="fitAll"]').click();await settle();assert.ok(await page.evaluate(()=>Math.abs(pan.x)<5000));
    await open();assert.equal(await page.locator('#grapheditmenu [data-edit="focus"]').getAttribute('aria-checked'),'false');
    await page.locator('#grapheditmenu [data-edit="focus"]').click();await settle();assert.equal(await page.evaluate(()=>graphFocused),true);
    await open();assert.equal(await page.locator('#grapheditmenu [data-edit="focus"]').getAttribute('aria-checked'),'true');assert.equal(await page.locator('#grapheditmenu [data-edit="focus"] .graph-menu-label').innerText(),await page.locator('#graphfocus').innerText());
    await page.locator('#grapheditmenu [data-edit="focus"]').click();await settle();assert.equal(await page.evaluate(()=>graphFocused),false);
    checks.push('Frame all and focus/restore layout work on an empty selection in read-only mode and use the existing labels/actions');
    await open();await page.locator('#grapheditmenu [data-edit="fullscreen"]').click();await page.waitForFunction(()=>!!document.fullscreenElement&&!fullscreenBusy);await settle();
    await open();assert.equal(await page.locator('#grapheditmenu [data-edit="fullscreen"]').getAttribute('aria-checked'),'true');
    assert.equal(await page.locator('#grapheditmenu [data-edit="fullscreen"] svg').innerHTML(),await page.locator('#uifullscreen svg:not([hidden])').innerHTML());
    assert.equal(await page.locator('#grapheditmenu [data-edit="fullscreen"] .graph-menu-label').innerText(),'Exit browser fullscreen');
    await page.locator('#grapheditmenu [data-edit="fullscreen"]').click();await page.waitForFunction(()=>!document.fullscreenElement&&!fullscreenBusy);await settle();
    await page.evaluate(()=>{fullscreenBusy=true;renderViewModes();});await open();assert.equal(await page.locator('#grapheditmenu [data-edit="fullscreen"]').isDisabled(),true);await page.keyboard.press('Escape');await page.evaluate(()=>{fullscreenBusy=false;renderViewModes();});
    assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future,selection:[...selection]})),viewBefore);
    checks.push('Context fullscreen enters/exits the native browser mode, follows its active icon/busy state, and view actions preserve graph/history');
    assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);console.error(error);process.exitCode=1;}
})();
