/* Type and port-shape edits remain recoverable drafts; never changes live TD. */
const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{autoDisconnectInvalidEdges:false}),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);try{
await page.evaluate(()=>{readonly=false;historyBusy=false;nativeMutationBusy=false;graph.functions=[];graph.declarations=[];stage='pixel';graphTrail=[];graph.stages.pixel={nodes:[testNode('vector','vector',40,40,{type:'vec4'}),testNode('split','vector_split',350,40,{type:'vec4'}),testNode('replace','replace',350,320,{type:'vec4'}),testNode('float','float',40,380),testNode('add','add',640,320,{type:'float'}),testNode('swizzle','swizzle',640,40,{type:'vec4',mask:'zw'})],edges:[{from:['vector','out'],to:['split','value']},{from:['float','out'],to:['replace','z']}]};current().nodes.forEach(n=>{n.name=n.id[0].toUpperCase()+n.id.slice(1);if(['split','swizzle','add'].includes(n.id))n.ui.typeMode='locked';});past=[];future=[];selected='vector';selection=new Set(['vector']);dirty=false;rememberSavedGraph(graph);render();scale=1;pan={x:20,y:30};transform();});
const baseline=await page.evaluate(()=>({edges:JSON.stringify(current().edges),revision,saved:savedGraphContent}));
await page.locator('[data-node-selector="vector"]').selectOption('vec2');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec2');assert.equal(await page.evaluate(()=>dirty),true);assert.equal(await page.evaluate(()=>JSON.stringify(current().edges)),baseline.edges);assert.equal(await page.locator('#wires path.invalid').count(),1);checks.push('Header keeps incompatible Vector type and original wires as a pending draft');
await page.route('**/api/apply',route=>route.fulfill({json:{ok:false,upgradeReview:{required:false,blocked:true,changes:[],issues:[{code:'compile',node:'split',message:'Type mismatch: vec2 to vec4'}]}}}));
await page.evaluate(()=>applyGraph());assert.deepEqual(await page.evaluate(()=>({revision,saved:savedGraphContent})),{revision:baseline.revision,saved:baseline.saved});assert.equal(await page.evaluate(()=>dirty),true);assert.equal(await page.evaluate(()=>conflicted),false);assert.equal(await page.evaluate(()=>upgradePending),null);assert.ok((await page.evaluate(()=>compileIssueText)).includes('vec2 to vec4'));checks.push('Current-version native blocked reply is a compile diagnostic, keeps last successful graph and editable draft, never opens Upgrade');
await page.evaluate(()=>change(()=>{current().nodes.find(n=>n.id==='vector').ui.x+=24;current().nodes.find(n=>n.id==='float').params.value=.75;}));assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='float').params.value),.75);checks.push('Invalid draft remains movable and unrelated parameter values editable');
await page.evaluate(()=>undo());await page.evaluate(()=>undo());assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec4');await page.evaluate(()=>undo(true));assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec2');checks.push('Undo and Redo cross the invalid type change without deleting edges');
await page.locator('#inspector [data-vector-type="vector"]').selectOption('vec4');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec4');await page.locator('#inspector [data-vector-type="vector"]').selectOption('vec2');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec2');assert.equal(await page.evaluate(()=>JSON.stringify(current().edges)),baseline.edges);checks.push('Parameter uses the same draft policy and can repair the type');
await page.evaluate(()=>{current().nodes.find(n=>n.id==='split').ui.typeMode='auto';});await page.locator('[data-node-selector="vector"]').selectOption('vec3');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='split').params.type),'vec3');checks.push('Compatible Auto downstream continues to infer and synchronize normally');
await page.evaluate(()=>{selected='replace';selection=new Set(['replace']);render();});await page.locator('[data-node-selector="replace"]').selectOption('vec2');assert.equal(await page.locator('[data-node="replace"] .missing-port [data-port="z"]').count(),1);assert.equal(await page.locator('#wires path[data-to="replace:z"]').count(),1);assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='replace').params.type),'vec2');checks.push('Replace shrink retains out-of-range Z edge with a visible disabled endpoint');
await page.unroute('**/api/apply');await page.route('**/api/apply',route=>route.fulfill({json:{ok:false,upgradeReview:{required:false,blocked:true,changes:[],issues:[{code:'repair',message:'This version cannot safely migrate the graph. Original connections were preserved.'}]}}}));await page.evaluate(()=>applyGraph());assert.equal(await page.evaluate(()=>conflicted),false);assert.equal(await page.evaluate(()=>upgradePending),null);assert.ok((await page.evaluate(()=>compileIssueText)).includes('Replace.z'));assert.ok(!(await page.evaluate(()=>compileIssueText)).includes('migrate'));await page.screenshot({path:path.join(folder,'missing-port-draft.png')});checks.push('Native repair-only reply points to the preserved missing port, without a misleading Upgrade state');

const invalid=await page.evaluate(()=>JSON.stringify(graph));assert.equal(await page.evaluate(()=>connectPorts({node:'float',port:'out',kind:'outputs'},{node:'replace',port:'value',kind:'inputs'})),false);assert.equal(await page.evaluate(()=>JSON.stringify(graph)),invalid);assert.equal(await page.evaluate(()=>connectPorts({node:'float',port:'out',kind:'outputs'},{node:'add',port:'a',kind:'inputs'})),true);checks.push('New invalid wiring remains strict; valid wiring elsewhere in an invalid draft works');
await page.locator('[data-node-selector="replace"]').selectOption('vec4');assert.equal(await page.locator('[data-node="replace"] .missing-port').count(),0);checks.push('Restoring Replace dimension revives the same Z connection');
await page.evaluate(()=>{selected='swizzle';selection=new Set(['swizzle']);render();});await page.locator('[data-node-selector="swizzle"]').selectOption('vec2');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='swizzle').params.mask),'zw');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='swizzle').params.type),'vec2');await page.locator('#inspector [data-swizzle-component="0"]').selectOption('x');await page.locator('#inspector [data-swizzle-component="1"]').selectOption('y');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='swizzle').params.mask),'xy');checks.push('Swizzle retains an invalid mask when changing type and can repair it through its existing selectors');
await page.evaluate(()=>{const uv=testNode('uv','uv',40,640),sum=current().nodes.find(n=>n.id==='add');current().nodes.push(uv);sum.ui.typeMode='auto';change(()=>current().edges=current().edges.filter(e=>e.to[0]!=='add'));connectPorts({node:'uv',port:'out',kind:'outputs'},{node:'add',port:'a',kind:'inputs'});selected='add';selection=new Set(['add']);inspectorTab='settings';render();});await page.locator('[data-require-constant="add"]').click();assert.equal(await page.evaluate(()=>!!current().nodes.find(n=>n.id==='add').params.requireConstant),false);checks.push('Direct Require Constant toggle retains the strict rule against runtime inputs');
await page.evaluate(()=>{graph.declarations=[{id:'runtime',name:'uRuntime',kind:'uniform',type:'vec4',value:[0,0,0,0]}];graph.stages.pixel={nodes:[testNode('runtime','uniform',20,40,{declarationId:'runtime'}),testNode('vector','vector',20,200,{type:'vec4'}),testNode('replace','replace',320,40,{type:'vec4',groups:{x:'vec4'}}),testNode('need','add',640,40,{type:'vec4',requireConstant:true})],edges:[{from:['runtime','out'],to:['replace','value']},{from:['vector','out'],to:['replace','x']},{from:['replace','out'],to:['need','a']}]};past=[];future=[];selected='vector';selection=new Set(['vector']);inspectorTab='parameters';render();});assert.equal(await page.evaluate(()=>constantRequirementIssues(graph).length),0);await page.locator('[data-node-selector="vector"]').selectOption('vec2');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.type),'vec2');assert.equal(await page.evaluate(()=>current().edges.length),3);assert.ok(await page.evaluate(()=>constantRequirementIssues(graph).length));await page.locator('[data-node-selector="vector"]').selectOption('vec4');assert.equal(await page.evaluate(()=>constantRequirementIssues(graph).length),0);checks.push('A type change that indirectly exposes runtime components keeps a const-invalid draft and repairs without losing wires');

await page.evaluate(()=>{graph.declarations=[];graph.stages.pixel={nodes:[testNode('vector','vector',30,40,{type:'vec3'}),testNode('replace','replace',360,40,{type:'vec4',groups:{y:'vec3'}})],edges:[{from:['vector','out'],to:['replace','y']}]};past=[];future=[];selected='replace';selection=new Set(['replace']);render();});await page.locator('[data-node-selector="replace"]').selectOption('vec2');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='replace').params.type),'vec2');assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='replace').params.groups),{y:'vec3'});assert.equal(await page.locator('#wires path[data-to="replace:y"]').count(),1);await page.evaluate(()=>change(()=>current().nodes.find(n=>n.id==='vector').ui.x+=20));await page.locator('[data-node-selector="replace"]').selectOption('vec4');assert.equal(await page.evaluate(()=>ports(current().nodes.find(n=>n.id==='replace'),'inputs').y),'vec3');checks.push('A grouped vector crossing the new dimension retains its raw layout and wire, remains editable, then repairs');
await page.evaluate(()=>{editorTarget='mat';graph.stages.pixel={nodes:[testNode('vector','vector',30,40,{type:'vec4'}),testNode('result','pixel_out',360,40,{bufferCount:2})],edges:[{from:['vector','out'],to:['result',typeContract.pixelBufferOutputs.ports[1]]}]};past=[];future=[];selected='result';selection=new Set(['result']);render();});const bufferEdge=await page.evaluate(()=>JSON.stringify(current().edges));await page.locator('#inspector [data-pixel-buffer-count="result"]').selectOption('1');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='result').params.bufferCount),1);assert.equal(await page.evaluate(()=>JSON.stringify(current().edges)),bufferEdge);assert.equal(await page.locator('[data-node="result"] .missing-port').count(),1);await page.locator('#inspector [data-pixel-buffer-count="result"]').selectOption('2');assert.equal(await page.locator('[data-node="result"] .missing-port').count(),0);checks.push('Color Output buffer shrink retains the connected removed port and restoring count revives it');
assert.equal(errors.length,0,errors.join('\n'));await page.screenshot({path:path.join(folder,'type-draft.png')});console.log(JSON.stringify({checks,errors}));await h.finish();
}catch(error){console.error(error);await h.finish(error);process.exitCode=1;}})();
