// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.evaluate(()=>{window.testInitial=clone(graph);});

await page.selectOption('#language','en');
const before=await page.evaluate(()=>clone(graph));
assert.equal(await page.locator('.node-output-type').count(),0);assert.ok(await page.locator('.port-row small').count()>0);checks.push('Header output summaries are removed while port types remain visible');
await page.evaluate(()=>{const n=current().nodes.find(n=>n.id==='filter');selectNode(n);render();});
assert.equal(await page.locator('[data-node=filter] .node-title-text>.subgraph-icon').count(),1);assert.equal(await page.locator('[data-node=filter] .node-function-name').innerText(),'Tint');
await page.locator('[data-node-label]').fill('主色 / Accent');await page.locator('[data-node-label]').press('Enter');
const rects=await page.locator('[data-node=filter] .node-title').evaluate(e=>{const title=e.querySelector('.node-title-text').getBoundingClientRect(),label=e.querySelector('.node-alias').getBoundingClientRect();return {right:title.right,left:label.left,dy:Math.abs((title.top+title.height/2)-(label.top+label.height/2))};});assert.ok(rects.right<=rects.left&&rects.dy<2);checks.push('Subgraph icon precedes its definition name; instance Label occupies the right side of the same header');
await page.locator('[data-node=filter] .node-alias').dblclick();assert.equal(await page.locator('[data-node-label]').evaluate(e=>document.activeElement===e),true);assert.equal(await page.evaluate(()=>graphTrail.length),0);
await page.locator('[data-node-label]').fill('x'.repeat(80));await page.locator('[data-node-label]').press('Enter');const width=await page.locator('[data-node=filter]').boundingBox();assert.ok(width.width<250);assert.equal(await page.locator('[data-node=filter] .node-alias').getAttribute('title'),'x'.repeat(80));checks.push('Label double-click edits only the label; long labels truncate without growing the node');
await page.locator('[data-node-label]').fill('Accent');await page.locator('[data-node-label]').press('Enter');
await page.locator('.node-comment-field summary').click();const comment='Keep alpha intact.\n貼圖備註 <script>alert(1)</script>\n*/ #version 450 \\';
const history=await page.evaluate(()=>past.length);await page.locator('[data-node-comment]').fill(comment);await page.locator('[data-node-comment]').press('Control+Enter');assert.equal(await page.locator('[data-node-comment]').inputValue(),comment);assert.equal(await page.evaluate(()=>past.length),history+1);assert.equal(await page.locator('.node-comment-help p').innerText(),comment);assert.equal(await page.locator('.node-comment-help script').count(),0);checks.push('Multiline Comment is inert plain text, shown in Help and stored with one undo step');
await page.locator('#undo').click();assert.equal(await page.evaluate(()=>nodeComment(current().nodes.find(n=>n.id==='filter'))),'');await page.locator('#redo').click();assert.equal(await page.locator('[data-node-comment]').inputValue(),comment);
await page.locator('[data-node-comment]').fill('cancel me');await page.locator('[data-node-comment]').press('Escape');assert.equal(await page.locator('[data-node-comment]').inputValue(),comment);checks.push('Comment supports Undo/Redo and Escape cancellation');
const h=await page.evaluate(()=>past.length);assert.equal(await page.evaluate(()=>setNodeComment(current().nodes.find(n=>n.id==='filter'),'x'.repeat(2001))),false);assert.equal(await page.evaluate(()=>past.length),h);checks.push('Invalid comments are rejected without changes');
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='filter'));window.identityClipboard=copyGraphSelection();});assert.equal(await page.evaluate(()=>pasteGraphSelection(identityClipboard,{x:500,y:500})),true);assert.equal(await page.evaluate(()=>nodeComment(current().nodes.find(n=>n.id===selected))),comment);assert.equal(await page.evaluate(()=>nodeLabel(current().nodes.find(n=>n.id===selected))),'Accent');checks.push('Node clipboard preserves Label and Comment with source references intact');
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='filter'));render();});
const ref=await page.evaluate(()=>current().nodes.find(n=>n.id==='filter').params.functionId);await page.locator('[data-node=filter] .node-function-name').dblclick();assert.equal(await page.evaluate(()=>graphTrail.at(-1)),ref);
await page.evaluate(()=>{const n=current().nodes.find(n=>n.definitionUuid===FunctionModel.INPUT);selectNode(n);render();});const functionsBefore=await page.evaluate(()=>graph.functions.length);await page.locator('[data-node-label]').fill('Incoming');await page.locator('[data-node-label]').press('Enter');await page.locator('.node-comment-field summary').click();await page.locator('[data-node-comment]').fill('Local presentation note');await page.locator('[data-node-comment]').press('Control+Enter');assert.equal(await page.evaluate(()=>graph.functions.length),functionsBefore);assert.equal(await page.evaluate(()=>currentFunction().scope),'library');checks.push('Presentation notes inside a source snapshot do not create semantic copies or change its definition identity');
await page.evaluate(()=>navigateGraph(0));const after=await page.evaluate(()=>clone(graph));fs.writeFileSync(path.join(folder,'identity-graphs.json'),JSON.stringify({before,after}));
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='filter'));render();fit();});await page.screenshot({path:path.join(folder,'node-identity.png')});
await page.selectOption('#language','zh-Hant');assert.equal(await page.locator('.node-comment-field summary').innerText(),'Comment · 註記');await page.evaluate(()=>{readonly=true;inspector();});assert.equal(await page.locator('[data-node-comment]').isDisabled(),true);assert.equal(await page.locator('[data-node-label]').isDisabled(),true);checks.push('Bilingual labels and read-only editing protection remain available');

assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});