/* Shared single-select menus through trusted pointer and keyboard events. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const[source,stateFile,folder]=process.argv.slice(2);
(async()=>{
  const h=await harness(source,stateFile,folder),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
  const menu=()=>page.locator('#selectmenu'),header=()=>page.locator('[data-node-selector="split"]');
  const snapshot=()=>page.evaluate(()=>JSON.stringify({graph,past,future}));
  const open=async source=>{await source.click();await menu().waitFor();await settle();};
  const choose=async value=>{await menu().locator(`[data-select-value="${value}"]`).click();await settle();};
  const close=async()=>{if(await menu().count()){await page.keyboard.press('Escape');await settle();}};
  const size=()=>menu().evaluate(e=>{const r=e.getBoundingClientRect(),b=e.querySelector('[role=option]').getBoundingClientRect(),s=getComputedStyle(e);return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom,itemHeight:b.height,radius:parseFloat(s.borderRadius),font:parseFloat(getComputedStyle(e.querySelector('[role=option]')).fontSize)};});
  const stackedMenu=async(label)=>{
    const geometry=await menu().evaluate(e=>{const rect=element=>{const r=element.getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};};return{viewport:{width:innerWidth,height:innerHeight},menu:rect(e),rows:[...e.querySelectorAll('[role=option]')].map(button=>{const range=document.createRange();range.selectNodeContents(button);return{...rect(button),label:button.textContent.trim(),lineCount:range.getClientRects().length,scrollWidth:button.scrollWidth,clientWidth:button.clientWidth};})};});
    assert.ok(geometry.rows.length>1,label+' must exercise multiple options');const {menu:m,viewport:v,rows}=geometry;assert.ok(m.x>=-1&&m.y>=-1&&m.right<=v.width+1&&m.bottom<=v.height+1,label+' menu must fit viewport');
    for(let i=0;i<rows.length;i++){const row=rows[i];assert.ok(row.x>=m.x-1&&row.right<=m.right+1,label+' option must fit menu width');assert.ok(row.scrollWidth<=row.clientWidth+1,label+' text must not be clipped');if(row.label.length<=12)assert.equal(row.lineCount,1,label+' short label must remain whole: '+row.label);if(i){assert.ok(row.y>=rows[i-1].bottom-.5,label+' option rows must stack without overlap');assert.ok(Math.abs(row.x-rows[i-1].x)<=1,label+' rows must align');}}
    return{label,...geometry};
  };
  const reset=async()=>{await close();await page.evaluate(()=>{
    clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;graph.functions=[];graph.declarations=[];graphTrail=[];stage='pixel';selected=selectedEdge=null;selection.clear();
    graph.stages.pixel={nodes:[testNode('split','vector_split',20,40,{type:'vec2'}),testNode('number','float',350,220,{value:.3})],edges:[]};current().nodes[0].ui.typeMode='auto';past=[];future=[];dirty=false;rememberSavedGraph(graph);render();scale=.8;pan={x:30,y:35};transform();
  });await settle();};
  const custom=()=>page.locator('#select-fixture');
  const customFixture=async()=>{await page.evaluate(()=>{
    document.querySelector('#select-fixture')?.remove();window.selectFixtureEvents=[];
    const select=el('select',{id:'select-fixture','aria-label':'Fixture choices'}),group=el('optgroup',{label:'Available group'}),disabledGroup=el('optgroup',{label:'Disabled group',disabled:true});
    select.append(el('option',{value:'alpha'},'Alpha'));group.append(el('option',{value:'beta'},'Beta'),el('option',{value:'gamma',disabled:true},'Gamma'));disabledGroup.append(el('option',{value:'delta'},'Delta'));select.append(group,disabledGroup,el('option',{value:'omega'},'Omega'));
    Object.assign(select.style,{position:'fixed',left:'30px',top:'180px',width:'180px',zIndex:100});select.addEventListener('input',()=>selectFixtureEvents.push('input:'+select.value));select.addEventListener('change',()=>selectFixtureEvents.push('change:'+select.value));document.body.append(select);
  });await settle();};
  try{
    await page.selectOption('#language','en');await reset();const initial=await snapshot();
    const measures=[];for(const uiScale of[75,125])for(const graphScale of[.25,1.7]){
      await close();await page.evaluate(({uiScale,graphScale})=>{setUIAppearance('size','standard');setUIAppearance('scale',uiScale);scale=graphScale;pan={x:30,y:35};transform();},{uiScale,graphScale});await settle();await open(header());
      assert.equal(await menu().getAttribute('role'),'listbox');assert.equal(await menu().getAttribute('data-align'),'right');const m=await size();assert.ok(m.radius>=7,'popup has rounded corners');assert.ok(m.itemHeight*100/uiScale>=28,'menu options stay comfortably sized');assert.ok(m.font>=12,'menu text uses UI scale, not tiny node text');assert.ok(m.x>=-1&&m.y>=-1&&m.right<=1601&&m.bottom<=1101);measures.push({uiScale,graphScale,...m});assert.equal(await snapshot(),initial);if(uiScale===125&&graphScale===.25)await page.screenshot({path:path.join(folder,'node-header-small-graph.png')});
    }
    for(const uiScale of[75,125]){const pair=measures.filter(m=>m.uiScale===uiScale);assert.ok(Math.abs(pair[0].itemHeight-pair[1].itemHeight)<1,'graph zoom does not scale option rows');assert.ok(Math.abs(pair[0].height-pair[1].height)<1,'graph zoom does not scale popup height');}
    fs.writeFileSync(path.join(folder,'geometry.json'),JSON.stringify(measures,null,2));await close();checks.push('rounded node header menu stays readable and independent of .25/1.7 graph zoom at75/125% UI scale; opening never edits graph/history');

    await page.evaluate(()=>{setUIAppearance('scale',100);scale=.8;transform();});await open(header());await choose('vec3');assert.equal(await header().inputValue(),'vec3');assert.deepEqual(await page.evaluate(()=>({type:current().nodes[0].params.type,mode:current().nodes[0].ui.typeMode,undo:past.length})),{type:'vec3',mode:'locked',undo:1});await page.locator('#undo').click();await settle();assert.equal(await header().inputValue(),'auto');assert.deepEqual(JSON.parse(await snapshot()).graph,JSON.parse(initial).graph);assert.equal(await page.evaluate(()=>past.length),0);assert.equal(await page.evaluate(()=>future.length),1);
    await page.locator('#redo').click();await settle();assert.equal(await header().inputValue(),'vec3');assert.equal(await page.evaluate(()=>past.length),1);
    await header().selectOption('vec4');await settle();assert.equal(await header().inputValue(),'vec4');assert.equal(await page.evaluate(()=>past.length),2);assert.equal(await menu().count(),0);
    checks.push('custom type choice preserves existing onchange and one Undo/Redo; native selectOption remains supported and does not duplicate commits');

    await reset();let before=await snapshot();await open(header());await page.keyboard.press('End');assert.equal(await snapshot(),before);await page.keyboard.press('Escape');await settle();assert.equal(await menu().count(),0);assert.equal(await header().evaluate(e=>e===document.activeElement),true);assert.equal(await snapshot(),before);await open(header());await page.locator('#editorheader').click({position:{x:3,y:3}});await settle();assert.equal(await menu().count(),0);assert.equal(await snapshot(),before);
    await header().focus();await page.keyboard.press('ArrowDown');await menu().waitFor();await page.keyboard.press('End');assert.equal(await snapshot(),before);await page.keyboard.press('Enter');await settle();assert.equal(await header().inputValue(),'vec4');assert.equal(await page.evaluate(()=>past.length),1);
    checks.push('Escape/outside cancel without edits; keyboard opening/navigation delays commit until Enter and returns focus to the native select');

    await reset();const number=page.locator('[data-inline-node="number"][data-component="0"]');await number.fill('0.73');before=await snapshot();await number.click({button:'right'});await page.locator('#numericpresets').waitFor();await header().click();await settle();assert.equal(await page.locator('#numericpresets').count(),0);assert.equal(await menu().count(),0);assert.equal(await number.inputValue(),'0.73');assert.equal(await snapshot(),before,'first select click only dismisses numeric presets');await open(header());await close();assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='number').params.value),.73);assert.equal(await page.evaluate(()=>past.length),1,'second click follows normal numeric blur commit once');checks.push('first select click dismisses numeric presets without committing the draft; second click opens normally and commits blur once');

    await customFixture();await open(custom());assert.equal(await menu().getByText('Available group',{exact:true}).count(),1);assert.equal(await menu().getByText('Disabled group',{exact:true}).count(),1);assert.equal(await menu().locator('[data-select-value="gamma"]').isDisabled(),true);assert.equal(await menu().locator('[data-select-value="delta"]').isDisabled(),true);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await settle();assert.equal(await custom().inputValue(),'beta');assert.deepEqual(await page.evaluate(()=>selectFixtureEvents),['input:beta','change:beta']);
    await open(custom());await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await settle();assert.equal(await custom().inputValue(),'omega','disabled option and disabled group must be skipped');
    await open(custom());await custom().evaluate(e=>e.disabled=true);await page.waitForFunction(()=>!document.querySelector('#selectmenu'));await custom().evaluate(e=>e.disabled=false);await open(custom());await custom().evaluate(e=>e.replaceChildren(new Option('Replacement','replacement')));await page.waitForFunction(()=>!document.querySelector('#selectmenu'));await open(custom());await custom().evaluate(e=>e.remove());await page.waitForFunction(()=>!document.querySelector('#selectmenu'));
    checks.push('optgroup labels and disabled states are preserved; keyboard skips disabled options; source disable/removal/options replacement close safely');

    await customFixture();await open(custom());await choose('alpha');assert.equal(await menu().count(),0);assert.deepEqual(await page.evaluate(()=>selectFixtureEvents),[],'choosing current value emits no input/change');await open(custom());await page.keyboard.press('o');assert.equal(await page.evaluate(()=>document.activeElement.dataset.selectValue),'omega');assert.equal(await custom().inputValue(),'alpha');await page.keyboard.press('Tab');await settle();assert.equal(await menu().count(),0);assert.equal(await custom().inputValue(),'alpha');assert.deepEqual(await page.evaluate(()=>selectFixtureEvents),[],'Tab cancels pending typeahead');await open(custom());await page.keyboard.press('b');await page.keyboard.press('Enter');await settle();assert.equal(await custom().inputValue(),'beta');assert.deepEqual(await page.evaluate(()=>selectFixtureEvents),['input:beta','change:beta']);await custom().evaluate(e=>e.remove());checks.push('typeahead moves focus without committing, Tab cancels, Enter commits once and selecting the current option is a zero-event no-op');

    await page.selectOption('#language','zh-Hant');await open(page.locator('#language'));assert.equal((await menu().locator('[data-select-value="zh-Hant"]').innerText()).trim(),(await page.locator('#language option[value="zh-Hant"]').innerText()).trim());await close();await page.selectOption('#language','en');await customFixture();await custom().evaluate(e=>e.replaceChildren(el('option',{value:'all','data-i18n':'browser.source.all'},t('browser.source.all'))));await open(custom());const english=await menu().locator('[data-select-value="all"]').innerText();await close();await page.selectOption('#language','zh-Hant');await open(custom());assert.notEqual(await menu().locator('[data-select-value="all"]').innerText(),english);await close();await custom().evaluate(e=>e.remove());await page.selectOption('#language','en');
    checks.push('menu labels follow current translated native option labels without stale text');

    await page.route('**/api/**share-links',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({origins:[{origin:new URL(page.url()).origin,kind:'local'},{origin:'http://192.168.50.7:9980',kind:'lan'},{origin:'http://192.168.50.8:9980',kind:'lan'}],lanEnabled:true,tokenRequired:false,shaderPath:'/'})}));
    await page.locator('#uishare').click();await page.locator('#sharepanel').waitFor();await page.waitForFunction(()=>document.querySelector('#shareorigin').options.length===3);await open(page.locator('#shareorigin'));assert.equal(await menu().evaluate(e=>e.closest('dialog')?.id),'sharepanel');assert.equal(await menu().evaluate(e=>e.matches(':popover-open')),true);const shareLayout=await stackedMenu('shareorigin in modal');fs.writeFileSync(path.join(folder,'share-menu-geometry.json'),JSON.stringify(shareLayout,null,2));await choose('http://192.168.50.8:9980');assert.ok((await page.locator('#shareurl').inputValue()).startsWith('http://192.168.50.8:9980/'));assert.equal(await page.locator('#sharepanel').evaluate(e=>e.matches(':modal')),true);await page.locator('#shareclose').click();
    checks.push('QR dialog options are full-width stacked rows within the viewport and select the origin without closing their modal owner');

    const sourceLayouts=[],sourceWrites=[];const trackSourceWrite=request=>{if(request.method()==='POST'&&new URL(request.url()).pathname.startsWith('/api/'))sourceWrites.push(new URL(request.url()).pathname);};page.on('request',trackSourceWrite);
    for(const width of[1600,320])for(const uiScale of[75,125]){
      await page.setViewportSize({width,height:width===320?844:1000});await page.evaluate(uiScale=>setUIAppearance('scale',uiScale),uiScale);await settle();if(!await page.locator('[data-workspace-panel="uniforms"]').isVisible())await page.locator('#togglelibrary').click();await page.locator('[data-workspace-panel="uniforms"]').click();await page.locator('[data-input-create="uniform"]').click();await page.locator('#sourcecreatedialog').waitFor();const sourceBefore=await snapshot();
      await open(page.locator('#sourcekind'));assert.equal(await menu().evaluate(e=>e.closest('dialog')?.id),'sourcecreatedialog');if(uiScale===125)await page.screenshot({path:path.join(folder,`sourcekind-${width}-${uiScale}.png`)});sourceLayouts.push(await stackedMenu(`sourcekind ${width}px UI${uiScale}`));await choose('color');assert.equal(await page.locator('#sourcekind').inputValue(),'color');assert.equal(await page.locator('#sourcetype').inputValue(),'vec4');assert.equal(await page.locator('#sourcetype').isDisabled(),true);assert.match(await page.locator('#sourcename').inputValue(),/^uColor/);assert.equal(await snapshot(),sourceBefore,'kind selection changes only the unsaved form');
      await open(page.locator('#sourcekind'));await choose('uniform');assert.equal(await page.locator('#sourcetype').isEnabled(),true);await open(page.locator('#sourcetype'));if(uiScale===125)await page.screenshot({path:path.join(folder,`sourcetype-${width}-${uiScale}.png`)});sourceLayouts.push(await stackedMenu(`sourcetype ${width}px UI${uiScale}`));await choose('vec3');assert.equal(await page.locator('#sourcetype').inputValue(),'vec3');assert.equal(await page.locator('#sourcekind').inputValue(),'uniform');assert.equal(await snapshot(),sourceBefore,'type selection must not create a declaration or Undo entry before Create');await page.locator('#closesourcecreate').click();assert.equal(await snapshot(),sourceBefore);
    }
    page.off('request',trackSourceWrite);assert.deepEqual(sourceWrites,[]);fs.writeFileSync(path.join(folder,'source-dialog-geometry.json'),JSON.stringify(sourceLayouts,null,2));checks.push('actual Inputs create dialog kind/type menus stack nonoverlapping rows with intact short labels at1600/320px and75/125%; choices update the original form without source/history/API mutation before Create');

    for(const uiScale of[75,125]){await page.setViewportSize({width:320,height:640});await page.evaluate(uiScale=>setUIAppearance('scale',uiScale),uiScale);await customFixture();await custom().evaluate(e=>Object.assign(e.style,{left:'auto',top:'auto',right:'3px',bottom:'3px'}));await open(custom());const m=await size();assert.ok(m.x>=-1&&m.y>=-1&&m.right<=321&&m.bottom<=641,JSON.stringify(m));await choose('omega');assert.equal(await custom().inputValue(),'omega');await custom().evaluate(e=>e.remove());}
    checks.push('menus at the viewport bottom-right clamp within320px at75/125% and remain selectable');
    await page.setViewportSize({width:1000,height:900});await page.evaluate(()=>setUIAppearance('scale',100));await reset();const touchBefore=await snapshot();const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});await page.evaluate(()=>{window.selectTouchEvents=[];document.addEventListener('pointerdown',event=>{if(event.pointerType==='touch')selectTouchEvents.push({trusted:event.isTrusted,target:event.target.closest('select')?.dataset.nodeSelector||event.target.closest('[data-select-value]')?.dataset.selectValue});},true);});
    const tap=async locator=>{const r=await locator.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:r.x+r.width/2,y:r.y+r.height/2,radiusX:4,radiusY:4}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();};
    try{await tap(header());await menu().waitFor();assert.equal(await snapshot(),touchBefore);await tap(menu().locator('[data-select-value="vec3"]'));assert.equal(await menu().count(),0);assert.equal(await header().inputValue(),'vec3');assert.equal(await page.evaluate(()=>past.length),1);const events=await page.evaluate(()=>selectTouchEvents);assert.ok(events.some(e=>e.target==='split')&&events.some(e=>e.target==='vec3')&&events.every(e=>e.trusted),JSON.stringify(events));}finally{await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await cdp.detach();}
    checks.push('trusted Chromium touch taps open the node header menu and choose a type in exactly one Undo operation (emulated touch, not physical device)');
    assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);throw error;}
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
