/* Connected selection is view-only and runs against an isolated editor fixture. */
const assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{skipPreview:true}),{page,checks,errors,settle}=h;
page.setDefaultTimeout(6000);const writes=[];
page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname.startsWith('/api/'))writes.push(new URL(r.url()).pathname);});
const reset=async()=>{await page.evaluate(()=>{
  stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];readonly=false;
  const n=(id,x,y)=>testNode(id,'add',x,y),edge=(from,to,port='a')=>({from:[from,'out'],to:[to,port]});
  graph.stages.pixel={nodes:[n('a',0,0),n('b',320,0),n('c',320,240),n('d',640,100),n('e',960,100),n('x',0,500),n('y',320,500),n('isolated',640,500)],edges:[edge('a','b'),edge('a','b','b'),edge('b','d'),edge('c','d','b'),edge('d','e'),edge('x','y')]};
  past=[];future=[];dirty=false;selected=selectedEdge=null;selection.clear();
  EDITOR_DEV_SETTINGS.ctrlArrowAdjacent=false;EDITOR_DEV_SETTINGS.arrowNavigationView='none';
  render();setGraphFocus(true);scale=.65;pan={x:50,y:60};transform();selectNode(current().nodes.find(n=>n.id==='b'));refreshCanvasSelection();
});await settle();};
const pick=async(...ids)=>page.evaluate(ids=>{selectNode(current().nodes.find(n=>n.id===ids[0]));for(const id of ids.slice(1))selection.add(id);refreshCanvasSelection();$('#canvas').focus();},ids);
const selected=()=>page.evaluate(()=>[...selection].sort());
const key=async(chord,ids)=>{await page.keyboard.press(chord);assert.deepEqual(await selected(),[...ids].sort(),chord);};
const state=()=>page.evaluate(()=>JSON.stringify({graph,past,future,dirty,revision,pan,scale}));
try{
await reset();let before=await state();await page.evaluate(()=>{window.selectionTestCard=$('#cards .node');window.selectionTestWire=$('#wires path');});
await key('Control+ArrowLeft',['a','b']);await pick('b');await key('Control+ArrowRight',['b','d','e']);
await pick('d');await key('Control+ArrowLeft',['a','b','c','d']);await pick('b');await key('Control+ArrowUp',['a','b','c','d','e']);
assert.equal(await page.evaluate(()=>selected),'b');assert.equal(await state(),before);
assert.equal(await page.evaluate(()=>window.selectionTestCard===$('#cards .node')&&window.selectionTestWire===$('#wires path')),true);
checks.push('Ctrl Left/Right follows all ancestors/descendants including starting nodes; Ctrl Up follows both directions across merges, without graph/history/view writes or canvas rebuilds');
await pick('b');await key('Control+ArrowDown',['x','y','isolated']);assert.equal(await page.evaluate(()=>selected),'x');
await key('Control+ArrowUp',['x','y','isolated']);await key('Control+ArrowDown',['a','b','c','d','e']);
checks.push('Ctrl Down is the exact complement of the full connected component, including isolated nodes and excluding starting nodes');
await pick('b','x');await key('Control+ArrowRight',['b','d','e','x','y']);
await pick('b','x');await key('Control+ArrowUp',['a','b','c','d','e','x','y']);
await pick('b','x');await key('Control+ArrowDown',['isolated']);
await pick('b','x','isolated');await key('Control+ArrowDown',[]);assert.equal(await page.evaluate(()=>selected),null);
checks.push('multiple starting nodes combine their traversals; a fully covered graph has an empty complement with no stale active node');
await pick('b');await page.evaluate(()=>{current().edges.push({from:['e','out'],to:['b','b']},{from:['b','out'],to:['b','a']},{from:['b','out'],to:['missing','a']},{from:['missing','out'],to:['x','b']});});
await key('Control+ArrowUp',['a','b','c','d','e']);
checks.push('duplicate edges, cycles, self-links and dangling endpoints terminate safely without joining unrelated nodes');
await reset();await page.evaluate(()=>{readonly=true;current().ui={frames:[{id:'mixed',name:'Mixed',nodes:['b','x'],color:'#777777'}]};renderGroupFrames();});
await key('Control+ArrowUp',['a','b','c','d','e']);await pick('b');await key('Control+ArrowDown',['x','y','isolated']);
checks.push('readonly graphs allow selection; sharing a Group does not imply a connection');
await reset();await key('Meta+ArrowLeft',['a','b']);await pick('b');await key('Meta+ArrowRight',['b','d','e']);await pick('b');await key('Meta+ArrowUp',['a','b','c','d','e']);await pick('b');await key('Meta+ArrowDown',['x','y','isolated']);
checks.push('Cmd equivalents perform all four connected selection actions');
await reset();await page.evaluate(()=>setUIExperiments({ctrlArrowAdjacent:true}));before=await state();
await key('Control+ArrowRight',['b','d']);await key('Control+ArrowRight',['b','d','e']);await key('Control+ArrowRight',['b','d','e']);
await key('Control+ArrowLeft',['a','b','c','d','e']);await key('Control+ArrowLeft',['a','b','c','d','e']);
await pick('e');await key('Control+ArrowLeft',['d','e']);await key('Control+ArrowLeft',['b','c','d','e']);await key('Control+ArrowLeft',['a','b','c','d','e']);
assert.equal(await state(),before);
checks.push('one-step mode preserves all selected nodes and adds exactly one neighboring layer per press, including merges, direction changes and endpoints');
await pick('b','x');await key('Control+ArrowRight',['b','d','x','y']);await key('Control+ArrowRight',['b','d','e','x','y']);await key('Control+ArrowLeft',['a','b','c','d','e','x','y']);
await pick('b','isolated');await key('Meta+ArrowRight',['b','d','isolated']);assert.equal(await page.evaluate(()=>selected),'b');
await pick('b');await key('Control+ArrowUp',['a','b','c','d','e']);await pick('b');await key('Control+ArrowDown',['x','y','isolated']);
checks.push('one-step mode grows from multiple selections, retains isolated starts and the active node, supports Cmd, and leaves Ctrl Up/Down unchanged');
await reset();await page.keyboard.down('Control');await page.keyboard.down('ArrowDown');assert.deepEqual(await selected(),['isolated','x','y']);
await page.keyboard.down('ArrowDown');assert.deepEqual(await selected(),['isolated','x','y']);await page.keyboard.up('ArrowDown');await page.keyboard.up('Control');
checks.push('holding a Ctrl arrow does not repeatedly toggle the complement or skip several one-step layers');
await reset();await page.evaluate(()=>clearCanvasSelection());for(const k of ['Left','Right','Up','Down'])await key('Control+Arrow'+k,[]);
await page.evaluate(()=>{selectedEdge=0;selected=null;selection.clear();$('#canvas').focus();});for(const k of ['Left','Right','Up','Down'])await key('Control+Arrow'+k,[]);assert.equal(await page.evaluate(()=>selectedEdge),0);
checks.push('empty selections and selected wires do not become traversal starting points');
await reset();const input=page.locator('#cards [data-node="a"] input').first();await input.focus();for(const k of ['Left','Right','Up','Down'])await key('Control+Arrow'+k,['b']);
await page.evaluate(()=>{const e=document.createElement('div');e.id='selection-editable';e.contentEditable='true';e.textContent='edit text';$('#canvas').append(e);e.focus();});await key('Control+ArrowUp',['b']);await page.evaluate(()=>$('#selection-editable').remove());
await page.evaluate(()=>{$('#canvas').focus();});for(const chord of ['Control+Shift+ArrowUp','Alt+ArrowRight','Control+Meta+ArrowUp'])await key(chord,['b']);
await page.evaluate(()=>{$('#canvas').onpointermove=()=>{};});await key('Control+ArrowUp',['b']);await page.evaluate(()=>{$('#canvas').onpointermove=null;nodePlacement={};});await key('Control+ArrowUp',['b']);await page.evaluate(()=>{nodePlacement=null;});
checks.push('text fields, contenteditable, other modifiers, active gestures and pending placement retain their own controls');
await page.evaluate(()=>setGraphFocus(false));await page.locator('#uishortcuts').click();await key('Control+ArrowUp',['b']);await page.keyboard.press('Escape');
await page.locator('#uiexperiments').click();await settle();await page.locator('[data-experiment="ctrlArrowAdjacent"]').check();
assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem(experimentsStorageKey)).ctrlArrowAdjacent),true);await key('Control+ArrowRight',['b']);await page.keyboard.press('Escape');
await page.locator('#uishortcuts').click();assert.match(await page.locator('[data-shortcut="selectUpstream"] dt').innerText(),/immediate upstream/);assert.deepEqual(await page.locator('[data-shortcut="selectUnlinked"] kbd').allTextContents(),['Ctrl','↓']);await page.keyboard.press('Escape');
checks.push('experimental one-step control persists, Help describes its current meaning, and dialogs/popovers block graph shortcuts');
await reset();await page.evaluate(()=>{graph.stages.vertex={nodes:[testNode('v1','add',0,0),testNode('v2','add',300,0)],edges:[{from:['v1','out'],to:['v2','a']}]};stage='vertex';render();selectNode(current().nodes[0]);refreshCanvasSelection();});await key('Control+ArrowUp',['v1','v2']);await key('Control+ArrowDown',[]);
checks.push('selection is scoped to the current Stage, never the entire Shader document');
await reset();const large=await page.evaluate(()=>{
  const data=current();data.nodes=Array.from({length:2500},(_,i)=>testNode('large'+i,'add',i*200,0));data.edges=data.nodes.slice(1).map((n,i)=>({from:['large'+i,'out'],to:[n.id,'a']}));
  selected='large0';selection=new Set([selected]);const start=JSON.stringify({graph,past,future,dirty});selectConnectedNodes(1);return{count:selection.size,unchanged:start===JSON.stringify({graph,past,future,dirty})};
});assert.deepEqual(large,{count:2500,unchanged:true});
checks.push('iterative traversal handles a 2500-node chain without recursive stack limits or graph mutation');
assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks:checks.length}));
}catch(error){await h.finish(error);console.error(error);process.exitCode=1;}})();
