/* Group frames use isolated graph fixtures and never write to TD.
 * node test_group_frames.cjs SOURCE_DIR STATE_JSON REPORT_DIR */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
async function run(){
  const[source,stateFile,folder]=process.argv.slice(2),h=await harness(source,stateFile,folder,{touch:true}),{page,checks,errors,settle}=h;
  page.setDefaultTimeout(6000);
  const graphJSON=()=>page.evaluate(()=>JSON.stringify(graph));
  const frames=()=>page.evaluate(()=>clone(current().ui?.frames||[]));
  const frame=id=>page.locator(`[data-frame="${id}"]`);
  const select=async ids=>{await page.evaluate(ids=>{selection=new Set(ids);selected=ids.at(-1)||null;selectedEdge=null;render();},ids);await settle();};
  const reset=async()=>{await page.evaluate(()=>{document.activeElement?.blur();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;stage='pixel';graphTrail=[];graph=clone(window.frameFixture);past=[];future=[];dirty=false;selectedEdge=null;selected='b';selection=new Set(['a','b']);rememberSavedGraph(graph);setUIAppearance('scale',100);setUIExperiments({selectionToolbar:'off'});render();scale=.7;pan={x:40,y:90};transform();});await settle();};
  const create=async()=>{await page.locator('#graphframe').click();await settle();const list=await frames();assert.equal(list.length,1);const entry=frame(list[0].id).locator('[data-frame-name]');if(await entry.count())await entry.press('Enter');await settle();return list[0].id;};
  const positions=()=>page.evaluate(()=>Object.fromEntries(current().nodes.map(n=>[n.id,{x:n.ui.x,y:n.ui.y}])));
  const titlePoint=async id=>{const r=await frame(id).locator('.group-frame-title').boundingBox();assert.ok(r);return{x:r.x+r.width*.4,y:r.y+r.height/2};};
  const drag=async(point,dx,dy)=>{await page.mouse.move(point.x,point.y);await page.mouse.down();await page.mouse.move(point.x+dx,point.y+dy,{steps:5});await page.mouse.up();await settle();};
  const bounds=async id=>page.evaluate(id=>{const rect=e=>{const r=e.getBoundingClientRect();return{left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height};},element=document.querySelector(`[data-frame="${CSS.escape(id)}"]`),data=current().ui.frames.find(f=>f.id===id),members=data.nodes.map(n=>rect(document.querySelector(`[data-node="${CSS.escape(n)}"]`)));return{frame:rect(element),title:rect(element.querySelector('.group-frame-title')),members,z:scale*uiScaleFactor()};},id);
  const encloses=async id=>{const b=await bounds(id),left=Math.min(...b.members.map(n=>n.left)),top=Math.min(...b.members.map(n=>n.top)),right=Math.max(...b.members.map(n=>n.right)),bottom=Math.max(...b.members.map(n=>n.bottom));assert.ok(b.frame.left<=left-20*b.z&&b.frame.right>=right+20*b.z,'frame surrounds full member widths');assert.ok(b.frame.bottom>=bottom+20*b.z&&b.title.bottom<=top,'title and padding stay outside member bounds');return b;};
  try{
    await page.evaluate(()=>{stage='pixel';graphTrail=[];graph.functions=[];graph.declarations=[];const a=testNode('a','float',96,192,{value:.75}),b=testNode('b','add',480,264),note=testNode('note','comment',1152,600),output=testNode('output','pixel_out',1440,264);a.ui.width=260;b.ui.width=310;Object.assign(note.ui,{width:300,height:340,comment:'Frame fixture'});graph.stages.pixel={nodes:[a,b,note,output],edges:[{from:['a','out'],to:['b','a']},{from:['b','out'],to:['output','color']}]};window.frameFixture=clone(graph);});await reset();
    const original=await graphJSON(),id=await create();assert.deepEqual((await frames())[0].nodes,['a','b']);assert.ok((await frames())[0].name);assert.equal(await page.locator('[data-node]').count(),4,'frame is not a catalog node');assert.equal(await page.evaluate(()=>past.length),1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await encloses(id);
    const created=await graphJSON();await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),original);assert.equal(await page.locator('[data-frame]').count(),0);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),created);checks.push('creating a named frame wraps the selected nodes without adding catalog nodes or shader changes and is one exact Undo/Redo');

    await frame(id).locator('.group-frame-name').dblclick();const rename=frame(id).locator('[data-frame-name]');await rename.fill('Lighting controls');await rename.press('Enter');await settle();assert.equal((await frames())[0].name,'Lighting controls');assert.equal(await page.evaluate(()=>past.length),2);
    await frame(id).locator('.group-frame-name').dblclick();await rename.fill('Discard this');await rename.press('Escape');await settle();assert.equal((await frames())[0].name,'Lighting controls');assert.equal(await page.evaluate(()=>past.length),2);
    const names=await page.locator('[data-node] .node-title').evaluateAll(es=>es.map(e=>getComputedStyle(e).backgroundColor)),beforeColor=await graphJSON();await frame(id).locator('[data-frame-color]').click();await page.locator('[data-frame-color-preset="#485f8d"]').click();await settle();assert.equal((await frames())[0].color,'#485f8d');assert.deepEqual(await page.locator('[data-node] .node-title').evaluateAll(es=>es.map(e=>getComputedStyle(e).backgroundColor)),names);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    const colored=await graphJSON();await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeColor);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),colored);checks.push('double-click rename commits/cancels cleanly; changing frame color is undoable, persists independently, and never recolors member types');

    await reset();const movedId=await create();await page.evaluate(()=>{setUIAppearance('scale',125);scale=.5;transform();});await settle();const beforeMove=await positions(),beforeDrag=await graphJSON(),history=await page.evaluate(()=>past.length),point=await titlePoint(movedId);await drag(point,45,30);
    const afterMove=await positions();for(const key of ['a','b']){assert.ok(Math.abs(afterMove[key].x-beforeMove[key].x-72)<.1);assert.ok(Math.abs(afterMove[key].y-beforeMove[key].y-48)<.1);}for(const key of ['note','output'])assert.deepEqual(afterMove[key],beforeMove[key]);assert.equal(await page.evaluate(()=>past.length),history+1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await encloses(movedId);
    const moved=await graphJSON();await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeDrag);await page.locator('#redo').click();await settle();assert.equal(await graphJSON(),moved);
    for(const reason of ['Escape','blur']){const before=await graphJSON(),count=await page.evaluate(()=>past.length),p=await titlePoint(movedId);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+60,p.y+30,{steps:3});if(reason==='Escape')await page.keyboard.press('Escape');else await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();await settle();assert.equal(await graphJSON(),before);assert.equal(await page.evaluate(()=>past.length),count);await encloses(movedId);}
    checks.push('frame title drags move all members at combined UI/graph scale in one reversible layout edit; Escape and focus loss cancel without history');

    await reset();const touchId=await create();await page.evaluate(()=>{scale=1;pan={x:0,y:30};transform();});await settle();
    const touchBefore=await positions(),touchHistory=await page.evaluate(()=>past.length),touchPan=await page.evaluate(()=>({...pan})),touchPoint=await titlePoint(touchId),cdp=await page.context().newCDPSession(page);
    await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchPoint.x,y:touchPoint.y,id:1}]});
    for(let step=1;step<=4;step++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchPoint.x+48*step/4,y:touchPoint.y+24*step/4,id:1}]});
    await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await settle();
    const touchAfter=await positions();for(const key of ['a','b'])assert.deepEqual(touchAfter[key],{x:touchBefore[key].x+48,y:touchBefore[key].y+24});for(const key of ['note','output'])assert.deepEqual(touchAfter[key],touchBefore[key]);assert.equal(await page.evaluate(()=>past.length),touchHistory+1);assert.deepEqual(await page.evaluate(()=>({...pan})),touchPan);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await encloses(touchId);
    const blankBounds=await bounds(touchId),blankPoint={x:blankBounds.frame.left+10*blankBounds.z,y:blankBounds.title.bottom+10*blankBounds.z},blankBefore=await graphJSON(),blankHistory=await page.evaluate(()=>past.length),panBefore=await page.evaluate(()=>({...pan}));
    assert.equal(await page.evaluate(p=>!!document.elementFromPoint(p.x,p.y)?.closest('[data-frame],[data-node]'),blankPoint),false,'empty frame body passes hit testing to canvas');await drag(blankPoint,40,24);
    assert.deepEqual(await page.evaluate(()=>({...pan})),{x:panBefore.x+40,y:panBefore.y+24});assert.equal(await graphJSON(),blankBefore);assert.equal(await page.evaluate(()=>past.length),blankHistory);checks.push('trusted touch title dragging moves members without panning; empty frame body passes through to ordinary canvas panning without edits');

    await reset();const resizeId=await create(),oldBounds=await bounds(resizeId);await select(['b']);const title=await page.locator('[data-node="b"] .node-title').boundingBox();await drag({x:title.x+title.width*.4,y:title.y+title.height/2},84,42);const movedBounds=await encloses(resizeId);assert.ok(movedBounds.frame.right>oldBounds.frame.right,'member movement automatically grows frame');
    const handle=await page.locator('[data-node-resize="b"]').boundingBox(),resizePoint={x:handle.x+handle.width/2,y:handle.y+handle.height/2},beforeResize=await graphJSON();await page.mouse.move(resizePoint.x,resizePoint.y);await page.mouse.down();await page.mouse.move(resizePoint.x+70,resizePoint.y,{steps:4});await settle();assert.ok((await encloses(resizeId)).frame.right>movedBounds.frame.right,'member resize preview immediately grows frame');assert.equal(await graphJSON(),beforeResize,'live frame bounds do not persist resize previews');await page.mouse.up();await settle();await encloses(resizeId);
    await page.evaluate(()=>remove());await settle();assert.deepEqual((await frames())[0].nodes,['a']);assert.ok((await bounds(resizeId)).frame.width<oldBounds.frame.width);await select(['a']);await page.evaluate(()=>remove());await settle();assert.equal((await frames()).length,0);await page.locator('#undo').click();await settle();assert.deepEqual((await frames())[0].nodes,['a']);await encloses(resizeId);checks.push('frame bounds track member moves and resizes, shrink when members are deleted, survive one member, and disappear at zero with exact Undo recovery');

    await reset();const removeId=await create(),beforeRemove=await graphJSON(),membersBefore=await page.evaluate(()=>JSON.stringify(current().nodes));await frame(removeId).locator('[data-frame-remove]').click();await settle();assert.equal((await frames()).length,0);assert.equal(await page.evaluate(()=>JSON.stringify(current().nodes)),membersBefore);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeRemove);checks.push('removing the frame preserves its member nodes and connections and can be undone');

    await select(['a','b','note']);assert.equal(await page.locator('#graphframe').isEnabled(),false);const overlapBefore=await graphJSON();await page.evaluate(()=>createGroupFrame());assert.equal(await graphJSON(),overlapBefore,'cannot recreate overlapping groups');await select(['note']);assert.equal(await page.locator('#graphframe').isVisible(),false);
    await select(['a','b']);await page.evaluate(()=>{readonly=true;render();});assert.equal(await page.locator('#graphframe').isEnabled(),false);assert.equal(await frame(removeId).locator('[data-frame-remove]').isEnabled(),false);assert.equal(await frame(removeId).locator('[data-frame-color]').isEnabled(),false);assert.equal(await frame(removeId).locator('[data-frame-rename]').isEnabled(),false);const readOnly=await graphJSON();await frame(removeId).locator('.group-frame-name').dblclick();assert.equal(await frame(removeId).locator('[data-frame-name]').count(),0);await drag(await titlePoint(removeId),40,30);assert.equal(await graphJSON(),readOnly);checks.push('overlapping memberships and single-node creation are unavailable; readonly blocks frame creation, renaming, color, deletion and dragging');

    await reset();const pasteId=await create();await frame(pasteId).locator('[data-frame-color]').click();await page.locator('[data-frame-color-preset="#485f8d"]').click();
    const copy=await page.evaluate(()=>{const payload=GraphClipboard.decode(GraphClipboard.encode(graph,current(),['a','b'],shaderId));let ids;change(()=>{ids=GraphClipboard.paste(graph,current(),payload,{source:shaderId,stage,target:editorTarget,catalog,types:numericTypes(),anchor:{x:100,y:650}});});return{ids,frames:clone(current().ui.frames)};});assert.equal(copy.frames.length,2);const pasted=copy.frames.find(f=>f.id!==pasteId);assert.ok(pasted);assert.deepEqual(new Set(pasted.nodes),new Set(copy.ids));assert.equal(pasted.color,'#485f8d');assert.equal(pasted.name,copy.frames[0].name);
    const frameCount=copy.frames.length;await page.evaluate(()=>{const payload=GraphClipboard.decode(GraphClipboard.encode(graph,current(),['a'],shaderId));change(()=>GraphClipboard.paste(graph,current(),payload,{source:shaderId,stage,target:editorTarget,catalog,types:numericTypes(),anchor:{x:900,y:650}}));});assert.equal((await frames()).length,frameCount);await page.evaluate(()=>{graph=JSON.parse(JSON.stringify(graph));render();});assert.equal((await frames()).length,2);checks.push('full-member clipboard copies retain name/color with fresh frame and node IDs; partial copies omit frames and JSON persistence retains them');

    await reset();const groupedId=await create();await select(['a','b']);await page.evaluate(()=>groupSelection());await settle();const grouped=await page.evaluate(()=>{const call=current().nodes.find(n=>n.id===selected),fn=FunctionModel.find(graph,call.params.functionId);return{call:call.id,fn:fn.id,frames:clone(fn.graph.ui?.frames||[]),outer:clone(current().ui?.frames||[])};});assert.equal(grouped.outer.length,0);assert.equal(grouped.frames.length,1);assert.deepEqual(grouped.frames[0].nodes,['a','b']);
    await page.evaluate(id=>enterFunction(current().nodes.find(n=>n.id===id)),grouped.call);await settle();assert.equal(await page.locator('[data-frame]').count(),1);await encloses(grouped.frames[0].id);await page.evaluate(()=>navigateGraph(0));await settle();assert.equal(await page.locator('[data-frame]').count(),0);await page.locator('#undo').click();await settle();assert.equal((await frames())[0].id,groupedId);checks.push('complete frames move into extracted subgraphs, render only in their owning graph, and extraction Undo restores outer membership');

    await page.evaluate(()=>{graph.stages.vertex={nodes:[testNode('a','float',50,100),testNode('b','float',330,100)],edges:[],ui:{frames:[{id:'vertex_frame',name:'Vertex only',nodes:['a','b']}]}};stage='vertex';selection.clear();selected=null;render();});await settle();assert.equal(await page.locator('[data-frame]').count(),1);assert.equal(await frame('vertex_frame').count(),1);assert.equal(await frame(groupedId).count(),0);await page.evaluate(()=>{stage='pixel';render();});await settle();assert.equal(await frame(groupedId).count(),1);assert.equal(await frame('vertex_frame').count(),0);checks.push('stage-local frames remain isolated even when node IDs match another stage');

    await reset();await create();await select(['a']);
    assert.equal(await page.locator('#graphdetachframe').isVisible(),true,'single grouped node has a detach action');
    const beforeDetach=await graphJSON(),beforeDetachNodes=await page.evaluate(()=>JSON.stringify({nodes:current().nodes,edges:current().edges})),detachHistory=await page.evaluate(()=>past.length);
    await page.locator('#graphdetachframe').click();await settle();assert.deepEqual((await frames())[0].nodes,['b']);
    assert.equal(await page.evaluate(()=>JSON.stringify({nodes:current().nodes,edges:current().edges})),beforeDetachNodes,'detach preserves node values, positions, and wires');
    assert.deepEqual(await page.evaluate(()=>[...selection]),['a']);assert.equal(await page.evaluate(()=>past.length),detachHistory+1);assert.equal(await page.evaluate(()=>hasShaderChanges()),false);
    assert.equal(await page.locator('#graphdetachframe').isVisible(),false);await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),beforeDetach);
    await page.locator('#redo').click();await settle();assert.deepEqual((await frames())[0].nodes,['b']);await select(['b']);await page.locator('#graphdetachframe').click();await settle();assert.equal((await frames()).length,0);
    await page.locator('#undo').click();await settle();assert.deepEqual((await frames())[0].nodes,['b']);checks.push('single-member detach preserves nodes/wires/selection, creates one layout Undo, keeps a one-member frame, and removes an empty frame reversibly');

    await reset();await create();await select(['note','output']);await page.locator('#graphframe').click();await settle();await page.locator('[data-frame-name]').press('Enter');await settle();await select(['a','note']);
    const multiDetachBefore=await graphJSON(),multiDetachHistory=await page.evaluate(()=>past.length);
    await page.evaluate(()=>detachGroupFrameSelection());await settle();assert.deepEqual((await frames()).map(f=>f.nodes),[['b'],['output']]);assert.equal(await page.evaluate(()=>past.length),multiDetachHistory+1);
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),multiDetachBefore);
    await page.evaluate(()=>{readonly=true;render();});await settle();assert.equal(await page.locator('#graphdetachframe').isEnabled(),false);await page.evaluate(()=>detachGroupFrameSelection());assert.equal(await graphJSON(),multiDetachBefore);
    await page.evaluate(()=>{readonly=false;render();});await select([]);const emptyHistory=await page.evaluate(()=>past.length);await page.evaluate(()=>detachGroupFrameSelection());assert.equal(await page.evaluate(()=>past.length),emptyHistory);checks.push('multi-frame detach edits only selected memberships in one Undo; readonly and empty selections cannot mutate frames');

    await reset();await page.locator('#canvas').focus();await page.keyboard.press('Control+g');await settle();assert.equal((await frames()).length,1);assert.equal((await frames())[0].name,'Group 1');
    const shortcutCreated=await graphJSON();await page.locator('[data-frame-name]').press('Control+g');assert.equal(await graphJSON(),shortcutCreated,'group shortcuts do not run while naming');await page.locator('[data-frame-name]').press('Escape');await settle();
    await select(['a']);await page.locator('#canvas').focus();await page.keyboard.press('Alt+g');await settle();assert.deepEqual((await frames())[0].nodes,['b']);await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),shortcutCreated);
    await select(['a','b']);await frame((await frames())[0].id).locator('.group-frame-title').focus();await page.keyboard.press('Alt+g');await settle();assert.equal((await frames()).length,0,'detach shortcut also works from a focused frame title');
    await page.locator('#undo').click();await settle();assert.equal(await graphJSON(),shortcutCreated);
    await reset();await page.locator('#canvas').focus();await page.keyboard.press('Control+Shift+g');await settle();assert.equal(await page.evaluate(()=>current().nodes.some(n=>n.definitionUuid===FunctionModel.CALL)),true,'shift variant keeps subgraph conversion');assert.equal((await frames()).length,0);
    await reset();await page.evaluate(()=>{readonly=true;render();});await page.locator('#canvas').focus();const shortcutsReadonly=await graphJSON();for(const key of ['Control+g','Control+Shift+g','Alt+g'])await page.keyboard.press(key);assert.equal(await graphJSON(),shortcutsReadonly);checks.push('Ctrl+G creates an English-named frame, Alt+G detaches from canvas/title, Ctrl+Shift+G creates a subgraph; naming and readonly isolate shortcut edits');

    await reset();await create();await page.evaluate(()=>{setGraphFocus(true);fit();});await settle();await page.screenshot({path:path.join(folder,'group-frames.png')});fs.writeFileSync(path.join(folder,'group-frames.json'),await graphJSON());assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
  }catch(error){await h.finish(error);throw error;}
}
run().catch(error=>{console.error(error);process.exit(1);});

