const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
(async()=>{
 const[source,state,folder]=process.argv.slice(2),h=await harness(source,state,folder,{skipPreview:true}),{page,checks,errors,settle}=h;
 try{
  await page.selectOption('#language','en');
  await page.evaluate(()=>{
   nativeSourcePolling=uniformPolling=customPolling=true;uniformLive.disconnect();uniformLive.connect=()=>{};clearTimeout(autoTimer);scheduleGraphApply=()=>{};
   graph.declarations=[{id:'gain',kind:'uniform',name:'uGain',type:'float',value:.5},{id:'constant',kind:'constant',name:'cValue',type:'vec3',value:[.1,.2,.3]},{id:'spec',kind:'spec_constant',name:'sValue',type:'int',value:3,constantId:0}];
   nativeSourceSnapshot={enabled:true,revision,uniforms:[{...graph.declarations[0],sequence:'vec',components:[{value:.5,mode:'CONSTANT',writable:true}],nameWritable:true,expected:{id:'gain'}}],specConstants:[{...graph.declarations[2],sequence:'const',components:[{value:3,mode:'CONSTANT',writable:true}],nameWritable:true,expected:{id:'spec'}}],issues:[]};
   graph.stages.pixel={nodes:[testNode('output','pixel_out',450,0),testNode('gain_node','uniform',0,0,{declarationId:'gain'})],edges:[]};graphTrail=[];stage='pixel';graph.functions=[];selected=null;selection.clear();selectedInputId=null;readonly=dirty=connectionInterrupted=false;past=[];future=[];inputCollapsedGroups.clear();inputExpandedGroups.clear();sourceCardCollapsed.clear();render();workspaceLayout.reveal('uniforms');window.initial=JSON.stringify(graph);
  });
  assert.equal(await page.locator('#uniformstoggle').innerText(),'Sources');
  const layout=await page.evaluate(()=>{const a=$('#inputsearch').getBoundingClientRect(),b=$('#sourcenames').getBoundingClientRect(),p=$('.input-search-tools').getBoundingClientRect();return{searchBottom:a.bottom,nameTop:b.top,width:a.width,parent:p.width};});
  assert.ok(layout.nameTop>=layout.searchBottom);assert.ok(Math.abs(layout.width-layout.parent)<1);
  assert.deepEqual(await page.locator('#nativeuniforms > [data-input-group]').evaluateAll(es=>es.slice(0,3).map(e=>e.dataset.inputGroup)),['uniform','constant','spec_constant']);
  assert.ok(await page.locator('#nativeuniforms > [data-input-group] > .input-group-title .input-group-toggle').evaluateAll(es=>es.every(e=>e.getAttribute('aria-expanded')==='false')));
  assert.equal(await page.locator('#nativeuniforms > [data-input-group=pop_buffer]').count(),1);
  assert.equal(await page.locator('[data-input-group="tdBuiltin.buffer"] [data-input-group=pop_buffer]').count(),0);
  await page.evaluate(()=>{for(const e of document.querySelectorAll('[data-input-group]'))setInputGroupCollapsed(e.dataset.inputGroup,false);renderNativeSources();});
  checks.push('Fresh Sources categories collapse by default and POP Buffers has its own root category');
  await page.evaluate(()=>{window.keptControl=$('[data-input-source="gain"] input');});
  const note=page.locator('[data-input-source="gain"] .source-card-note');assert.ok(await note.isVisible());
  await page.locator('#sourcenotes').uncheck();assert.equal(await note.isVisible(),false);await page.locator('#sourcenotes').check();
  assert.ok(await page.evaluate(()=>keptControl===$('[data-input-source="gain"] input')));
  assert.ok(await page.evaluate(()=>{const c=$('[data-input-source="gain"]');return c.querySelector('.source-card-outputs').getBoundingClientRect().bottom<=c.querySelector('input').getBoundingClientRect().top;}));
  assert.equal(await page.evaluate(()=>JSON.stringify(graph)===initial&&past.length===0),true);
  checks.push('Sources label, full-width search, separate display row, default category order, notes and top outputs preserve graph and controls');
  await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='gain_node'));inspectorTab='parameters';inspector();workspaceLayout.reveal('parameters');});
  assert.equal(await page.locator('#inspector [data-inspect-input]').count(),0);assert.ok(await page.locator('#inspector [data-native-components]').count());
  await page.locator('.parameter-tabs button').filter({hasText:'Settings'}).click();
  await page.locator('#inspector [data-inspect-input="gain"]').click();assert.equal(await page.evaluate(()=>selectedInputId),'gain');
  checks.push('source editing opens from Settings while live values stay in Parameters');
  await page.evaluate(()=>{workspaceLayout.reveal('uniforms');selectedInputId=null;});
  const constant=page.locator('[data-source-constant="constant"]'),component=i=>constant.locator('[data-constant-component="'+i+'"]');
  await component(0).fill('0.7');await component(0).press('Enter');await component(1).fill('0.8');await component(1).press('Enter');
  assert.deepEqual(await page.evaluate(()=>graph.declarations.find(d=>d.id==='constant').value),[.7,.8,.3]);
  await page.evaluate(()=>undo());assert.equal(await component(1).inputValue(),'0.2');assert.equal(await component(0).inputValue(),'0.7');
  await page.evaluate(()=>undo(true));assert.equal(await component(1).inputValue(),'0.8');
  // Uncommitted text survives display changes and polling; component commits
  // read the current declaration, not the values captured when controls built.
  await component(2).fill('0.9');
  await page.evaluate(()=>{window.constantControl=$('[data-source-constant="constant"] [data-constant-component="2"]');renderNativeSources();});
  assert.equal(await component(2).inputValue(),'0.9');await component(2).press('Enter');
  assert.deepEqual(await page.evaluate(()=>graph.declarations.find(d=>d.id==='constant').value),[.7,.8,.9]);
  checks.push('constant components edit independently, preserve drafts, and synchronize Undo/Redo');
  const dormant=page.locator('.source-card[data-dormant="true"]').first();await dormant.locator('.source-card-toggle').click();assert.ok(await dormant.locator('.source-card-body').isVisible());
  await page.evaluate(()=>{window.beforeView=JSON.stringify(graph);window.beforeHistory=past.length;window.normalHeight=$('[data-input-source="constant"]').getBoundingClientRect().height;window.normalFont=getComputedStyle($('[data-input-source="constant"] .input-source-select')).fontSize;});
  await page.locator('#sourceminimal').check();
  assert.equal(await dormant.locator('.source-card-body').isVisible(),false);
  assert.equal(await page.locator('[data-input-source="constant"] .source-card-outputs').isVisible(),false);
  assert.ok(await component(0).isVisible());
  assert.ok(await page.evaluate(()=>constantControl===$('[data-source-constant="constant"] [data-constant-component="2"]')&&keptControl===$('[data-input-source="gain"] input')));
  assert.ok(await page.evaluate(()=>$('[data-input-source="constant"]').getBoundingClientRect().height<normalHeight));
  assert.equal(await page.evaluate(()=>getComputedStyle($('[data-input-source="constant"] .input-source-select')).fontSize===normalFont),true);
  await page.screenshot({path:path.join(folder,'sources-minimal.png')});
  await page.locator('#sourceminimal').uncheck();
  assert.ok(await dormant.locator('.source-card-body').isVisible());
  assert.ok(await page.locator('[data-input-source="constant"] .source-card-outputs').isVisible());
  assert.equal(await page.evaluate(()=>JSON.stringify(graph)===beforeView&&past.length===beforeHistory),true);
  checks.push('minimal display hides sockets, shrinks card height without shrinking text, preserves controls and restores normal display');
  const rootOrder=()=>page.locator('#nativeuniforms > [data-input-group]').evaluateAll(es=>es.map(e=>e.dataset.inputGroup));
  await page.evaluate(()=>{for(const key of ['uniform','constant','spec_constant'])setInputGroupCollapsed(key,true);renderNativeSources();});
  const from=await page.locator('#nativeuniforms > [data-input-group="constant"] > .input-group-title .input-group-toggle').boundingBox(),to=await page.locator('#nativeuniforms > [data-input-group="uniform"] > .input-group-title').boundingBox();
  await page.mouse.move(from.x+40,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+40,to.y+2,{steps:12});await page.mouse.up();
  assert.deepEqual((await rootOrder()).slice(0,3),['constant','uniform','spec_constant']);
  assert.equal(await page.locator('.source-group-move').count(),0);
  await page.locator('#inputsearch').fill('cValue');
  assert.equal(await page.locator('.source-sortable').count(),0);
  await page.locator('#inputsearch').fill('');
  assert.deepEqual((await rootOrder()).slice(0,3),['constant','uniform','spec_constant']);
  assert.equal(await page.evaluate(()=>JSON.stringify(graph)===beforeView&&past.length===beforeHistory),true);
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('grapeSourceGroupOrder')).root[0]),'constant');
  checks.push('category order persists locally through filtering without changing declarations or history');
  await page.evaluate(()=>{
   setInputGroupCollapsed('constant',false);
   for(const [id,type,value]of [['flag','bool',false],['exact','uint',4294967295],['matrix','mat2x3',[1,2,3,4,5,6]]])graph.declarations.push({id,name:'c'+id,kind:'constant',type,value});renderNativeSources();
  });
  await page.locator('[data-source-constant="flag"] select').selectOption('true');
  const exact=page.locator('[data-source-constant="exact"] input');await exact.fill('4294967294');await exact.press('Enter');
  const matrix=page.locator('[data-source-constant="matrix"] [data-constant-component="4"]');await matrix.fill('7');await matrix.press('Enter');
  assert.deepEqual(await page.evaluate(()=>graph.declarations.filter(d=>['flag','exact','matrix'].includes(d.id)).map(d=>d.value)),[true,4294967294,[1,2,3,4,7,6]]);
  await page.evaluate(()=>{readonly=true;renderNativeSources();});assert.ok(await exact.isDisabled());
  await page.evaluate(()=>{readonly=false;renderNativeSources();});
  checks.push('constant controls preserve bool, exact uint and matrix component types and obey read-only state');
  const stale=await page.evaluate(()=>{const entry=$('[data-source-constant="exact"] input'),before=JSON.stringify(graph);editorLoadGeneration++;entry.value='12';entry.dispatchEvent(new Event('change'));renderNativeSources();return JSON.stringify(graph)===before;});assert.ok(stale);
  await page.locator('#sourceminimal').check();
  assert.ok(await page.locator('[data-source-constant]').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1)));
  await page.reload();await page.waitForFunction(()=>graph&&$('#sourceminimal').checked);
  assert.equal(await page.evaluate(()=>sourceGroupOrder.root[0]),'constant');
  checks.push('old graph controls cannot edit a new graph; compact controls fit the narrow pane and display preferences reload');
  await page.screenshot({path:path.join(folder,'sources.png')});assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks}));
 }catch(e){await h.finish(e);throw e;}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
