const assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const {vectorCases}=require('../fixtures/vector_nodes.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{
 const h=await harness(source,stateFile,folder,{skipPreview:true}),{page,checks,errors}=h;
 page.setDefaultTimeout(6000);
 const isolate=()=>page.evaluate(()=>{clearTimeout(autoTimer);scheduleGraphApply=()=>{};readonly=conflicted=historyBusy=nativeMutationBusy=false;connectionInterrupted=true;nativeSourcePolling=uniformPolling=customPolling=true;uniformLive.disconnect();uniformLive.connect=()=>{};});
 const seed=g=>page.evaluate(g=>{graph=clone(g);graph.topSourceVersion=1;stage='pixel';graphTrail=[];past=[];future=[];selected='operation';selection=new Set([selected]);graph.stages.pixel.nodes.forEach((n,i)=>n.ui={x:i*260,y:25});render();scale=.6;pan={x:10,y:10};transform();},g);
 try{
  await isolate();await seed(vectorCases().find(r=>r.key==='combine'&&r.type==='vec4:false').graph);
  await page.evaluate(()=>{change(()=>{current().nodes.push(testNode('wide','vec2',0,320,{value:[.4,.5]}),testNode('other','float',0,550,{value:.8}));});connectPorts({node:'other',kind:'outputs',port:'out'},{node:'operation',kind:'inputs',port:'y'});window.oldVectorPorts=vectorPorts;vectorPorts=()=>{throw Error('Legacy vector rules reached');};});
  const before=await page.evaluate(()=>JSON.stringify(graph));
  assert.equal(await page.evaluate(()=>connectPorts({node:'wide',kind:'outputs',port:'out'},{node:'operation',kind:'inputs',port:'x'})),true);
  assert.deepEqual(await page.evaluate(()=>({groups:current().nodes.find(n=>n.id==='operation').params.groups,to:current().edges.filter(e=>e.to[0]==='operation').map(e=>e.to[1]),output:ports(current().nodes.find(n=>n.id==='operation'),'outputs').out})),{groups:{x:'vec2'},to:['x'],output:'vec4'});
  const wired=await page.evaluate(()=>JSON.stringify(graph));await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before);await page.locator('#redo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),wired);
  checks.push('Combine joins component sockets and displaces overlapping wires through the model with legacy vector rules disabled; Undo/Redo is exact');
  await page.evaluate(()=>change(()=>removeGraphEdges(graph,current(),e=>e.to[0]==='operation')));
  assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.groups),{x:'vec2'});
  const x=page.locator('[data-parameter-node="operation"][data-parameter-port="x"][data-component="0"] input, input[data-parameter-node="operation"][data-parameter-port="x"][data-component="0"]').first();await x.fill('0.7');await x.press('Enter');await x.press('Tab');
  assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.components[0]),.7);
  assert.match(await page.evaluate(()=>GrapeTopCompiler.compile(graph,typeContract.glslCode).pixel),/0\.7/);
  checks.push('Disconnect retains the grouped input and inline edits update the component source used by compilation');
  await page.evaluate(()=>{vectorPorts=oldVectorPorts;change(()=>current().nodes.push(testNode('legacy','pow',1000,500,{type:'float'})));});
  assert.equal(await page.evaluate(()=>connectPorts({node:'wide',kind:'outputs',port:'out'},{node:'operation',kind:'inputs',port:'x'})),true);
  assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.groups),{x:'vec2'});
  assert.equal(await page.evaluate(()=>GrapeTopCompiler.supports(graph)),false);
  checks.push('The same component operation works beside an unmigrated node, with explicit whole-graph Python selection');
  await seed(vectorCases().find(r=>r.key==='swizzle'&&r.type==='vec4:xy').graph);
  await page.locator('[data-node-control="component0"]').selectOption('z');
  assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.mask),'zy');
  const connectedMask=await page.evaluate(()=>JSON.stringify(graph));await page.locator('[data-node-control="add"]').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),connectedMask);
  await page.evaluate(()=>change(()=>removeGraphEdges(graph,current(),e=>e.from[0]==='operation')));
  const mask=await page.evaluate(()=>JSON.stringify(graph));await page.locator('[data-node-control="add"]').click();assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.mask.length),3);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),mask);
  checks.push('Swizzle component selectors and explicit width changes use module commands and one Undo');
  await seed(vectorCases().find(r=>r.key==='convert'&&r.type==='vec4->vec4').graph);
  assert.equal(await page.locator('[data-node-control="fromType"] option[value="vec2"]').count(),0);
  await page.evaluate(()=>change(()=>removeGraphEdges(graph,current(),e=>e.from[0]==='operation')));
  await page.locator('[data-node-selector="operation"]').selectOption('vec2');await page.locator('[data-node-control="fromType"]').selectOption('vec2');
  assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='operation').params.toType),'vec2');
  checks.push('Convert exposes module-owned input/output choices and never silently changes the output to accommodate an input choice');
  for(const key of ['swizzle','convert']){
   await seed(vectorCases().find(r=>r.key==='vector'&&r.type==='vec3').graph);
   const before=await page.evaluate(()=>JSON.stringify(graph));
   await page.evaluate(()=>openCreator(700,300,{node:'operation',kind:'outputs',port:'out',type:'vec3'}));
   await page.locator('#createsearch').fill(key);await page.locator('[data-create-entry="'+key+'"]').click();
   const created=await page.evaluate(()=>({n:clone(current().nodes.find(n=>n.id===selected)),output:ports(current().nodes.find(n=>n.id===selected),'outputs').out,wired:current().edges.some(e=>e.from[0]==='operation'&&e.to[0]===selected)}));
   assert.equal(created.wired,true);assert.equal(created.output,'vec3');
   await page.evaluate(()=>change(()=>removeGraphEdges(graph,current(),e=>e.to[0]===selected)));
   assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id===selected).params),created.n.params);
   await page.locator('#undo').click();await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before);
  }
  checks.push('Connected creation initializes Swizzle/Convert once; disconnect retains their authored choices and Undo restores both steps');
  await seed(vectorCases().find(r=>r.key==='router'&&r.type==='float').graph);
  const saved=await page.evaluate(()=>clone(graph));let sent;page.on('request',r=>{if(r.url().endsWith('/api/apply'))sent=r.postDataJSON();});
  await page.evaluate(async()=>{connectionInterrupted=false;applyNeedsReview=false;await performApplyGraph();});assert.ok(sent.frontendArtifact?.compiled.pixel);assert.deepEqual(sent.graph,saved);
  await page.reload();await page.waitForSelector('.node');await isolate();assert.deepEqual(await page.evaluate(()=>clone(graph)),saved);
  checks.push('Routing submits a frontend artifact and reloads the authored graph intact');assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
 }catch(error){await h.finish(error);throw error;}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
