/* Component colors are presentation-only and follow known component positions. */
const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs'),[source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const dark=['rgb(204, 152, 157)','rgb(155, 196, 165)','rgb(154, 175, 212)','rgb(195, 192, 203)'],light=['rgb(162, 63, 72)','rgb(55, 109, 69)','rgb(50, 100, 156)','rgb(98, 97, 109)'];
const color=loc=>loc.evaluate(e=>getComputedStyle(e).color),fixed=id=>page.locator(`#cards [data-node="${id}"] .node-fixed-values input`),paint=async values=>{await page.evaluate(values=>setUIExperiments(values),values);await settle();},choose=async id=>{await page.evaluate(id=>{document.activeElement?.blur();selected=id;selection=new Set([id]);inspectorTab='parameters';inspector();},id);await settle();};
try{
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;graphTrail=[];stage='pixel';selectedInputId=null;graph.declarations=[];graph.functions=[];const v=testNode('vector','vector',40,50,{type:'vec4',components:[.1,.2,.3,.4]});v.ui.componentsExpanded=true;const uv=testNode('uv','vector',40,340,{type:'vec2',components:[.1,.2]});uv.ui.componentNames='uv';uv.ui.componentsExpanded=true;graph.stages.pixel={nodes:[v,uv,testNode('color','color',40,560,{value:[.7,.3,1,1]}),testNode('split','vector_split',400,50,{type:'vec4'}),testNode('add','add',720,50,{type:'float'}),testNode('swizzle','swizzle',400,360,{type:'vec4',mask:'zyxw'}),testNode('combine','combine',720,400,{type:'vec4',components:[0,0,0,1],groups:{x:'vec3'}}),testNode('three','vector',720,700,{type:'vec3',components:[.1,.2,.3,0]})],edges:[{from:['vector','out'],to:['split','value']},{from:['split','x'],to:['add','a']},{from:['three','out'],to:['combine','x']}]};selected='vector';selection=new Set(['vector']);past=[];future=[];dirty=false;rememberSavedGraph(graph);setUIExperiments({rgbaComponentTint:true,vectorComponentTint:false});render();scale=.65;pan={x:10,y:10};transform();});await settle();
assert.equal(await color(fixed('color').first()),dark[0]);assert.notEqual(await color(fixed('vector').first()),dark[0]);checks.push('default RGBA-only mode retains ordinary vector text');
const before=await page.evaluate(()=>JSON.stringify({graph,past,future,dirty})),entry=fixed('vector').first();await entry.fill('');await entry.evaluate(e=>window.tintDraft=e);await paint({rgbaComponentTint:false,vectorComponentTint:true});assert.equal(await entry.evaluate(e=>e===window.tintDraft&&e===document.activeElement),true);assert.equal(await entry.inputValue(),'');assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future,dirty})),before);await entry.press('Escape');checks.push('live tint changes preserve numeric draft DOM/focus and graph/history');
for(const id of ['vector','color'])for(let i=0;i<4;i++)assert.equal(await color(fixed(id).nth(i)),dark[i]);for(let i=0;i<2;i++){assert.equal(await color(fixed('uv').nth(i)),dark[i]);assert.equal(await color(page.locator('#cards [data-node="uv"] .node-inline-component>span').nth(i)),dark[i]);}checks.push('all-vector flag independently colors XYZW, UV and RGBA values/labels by index');
await choose('vector');await page.locator('[data-parameter-expand="$value"]').click();for(let i=0;i<4;i++){assert.equal(await color(page.locator('#inspector [data-parameter-copy="compact"]').nth(i)),dark[i]);assert.equal(await color(page.locator('.parameter-component-row .parameter-value-label').nth(i)),dark[i]);assert.equal(await color(page.locator('.parameter-component-row input').nth(i)),dark[i]);}checks.push('Parameter compact/expanded controls and named components share the palette');
await choose('uv');await page.locator('[data-parameter-expand="$value"]').click();assert.deepEqual(await page.locator('.parameter-component-row .parameter-value-label').allTextContents(),['U','V']);for(let i=0;i<2;i++)assert.equal(await color(page.locator('.parameter-component-row .parameter-value-label').nth(i)),dark[i]);await page.evaluate(()=>{const box=numbers([.1,.2],'Texture',()=>{},false,'ST');box.id='component-label-fixture';document.querySelector('#inspector').append(box);});assert.deepEqual(await page.locator('#component-label-fixture .component-label').allTextContents(),['S','T']);for(let i=0;i<2;i++)assert.equal(await color(page.locator('#component-label-fixture .component-label').nth(i)),dark[i]);checks.push('UV and existing generic ST labels use index colors without a new naming mode');
const split=page.locator('#cards [data-node="split"] .output[data-vector-component="0"]'),wire=page.locator('#wires path[data-from="split:x"]');assert.equal(await color(split.locator('.port-label')),dark[0]);assert.equal(await split.locator('.port').evaluate(e=>getComputedStyle(e).backgroundColor),dark[0]);assert.equal(await wire.evaluate(e=>getComputedStyle(e).stroke),dark[0]);assert.equal(await page.locator('#cards [data-node="add"] .output').getAttribute('data-vector-component'),null);checks.push('known scalar component sockets and source wires tint without propagation through Add');
await choose('combine');const grouped=page.locator('#cards [data-node="combine"] .input').filter({has:page.locator('.port[data-port="x"]')});assert.deepEqual(await grouped.locator('.port-label span').allTextContents(),['X','Y','Z']);for(let i=0;i<3;i++){assert.equal(await color(grouped.locator('.port-label span').nth(i)),dark[i]);assert.equal(await color(page.locator('#inspector [data-input="x"] .parameter-value-label span').nth(i)),dark[i]);}assert.equal(await grouped.getAttribute('data-vector-component'),null);checks.push('grouped XYZ letters tint individually while whole vector sockets retain type colors');
await choose('swizzle');for(const [i,index]of [2,1,0,3].entries())assert.equal(await color(page.locator('[data-swizzle-component]').nth(i)),dark[index]);checks.push('Swizzle selectors follow reordered source components');
await paint({vectorComponentTint:false,rgbaComponentTint:false});assert.notEqual(await color(fixed('vector').first()),dark[0]);assert.notEqual(await color(fixed('color').first()),dark[0]);await paint({rgbaComponentTint:true});assert.equal(await color(fixed('color').first()),dark[0]);assert.notEqual(await color(fixed('vector').first()),dark[0]);checks.push('independent flags restore neutral text or RGBA-only mode');
await paint({vectorComponentTint:true,rgbaComponentTint:false});await page.evaluate(()=>setUIAppearance('theme','light'));await settle();for(let i=0;i<4;i++)assert.equal(await color(fixed('vector').nth(i)),light[i]);assert.equal(await wire.evaluate(e=>getComputedStyle(e).stroke),light[0]);await choose('vector');if(await page.locator('[data-parameter-expand="$value"]').getAttribute('aria-expanded')!=='true')await page.locator('[data-parameter-expand="$value"]').click();for(let i=0;i<4;i++)assert.equal(await color(page.locator('#inspector [data-parameter-copy="compact"]').nth(i)),light[i]);await page.screenshot({path:path.join(folder,'vector-components-light.png')});checks.push('Light mode retains the established readable palette in nodes, wires and Parameter');
await page.evaluate(()=>setUIAppearance('theme','dark'));await settle();await page.screenshot({path:path.join(folder,'vector-components-dark.png')});assert.equal(await page.evaluate(()=>JSON.stringify({graph,past,future,dirty})),before);assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
}catch(e){await h.finish(e);throw e;}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
