const assert=require('node:assert/strict');
const {harness}=require('./test_glsl_code.cjs');
const [source,state,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,state,folder,{skipPreview:true}),{page,checks,errors,settle}=h;
try{
const cases=[['color','outputs','out','multiply'],['color','outputs','out','vector_split'],['matrix','outputs','out','matrix_split'],['texture','outputs','out','texture_sample'],['dest','inputs','a','uniform'],['dest','inputs','a','constant'],['split','inputs','value','input:uc'],['dest','inputs','a','function']];
for(const [id,kind,port,key]of cases){
await page.evaluate(()=>{cancelNodePlacement();closeCreator();readonly=false;nativeSourcePolling=true;graph.functions=[];graph.declarations=[{id:'uc',kind:'uniform',name:'uColor',type:'vec4',nativeSequence:'color',value:[.1,.2,.3,1]}];stage='pixel';graphTrail=[];graph.stages.pixel={nodes:[testNode('color','color',80,80),testNode('matrix','matrix',80,300,{type:'mat4'}),testNode('texture','top_input',500,300,{inputId:graph.topInputs[0].id}),testNode('dest','add',500,80),testNode('split','vector_split',900,80,{type:'vec4'})],edges:[]};past=[];future=[];dirty=false;selected=null;selection.clear();render();setGraphFocus(true);scale=.7;pan={x:30,y:30};transform();});await settle();
if(key==='function')await page.evaluate(()=>{functionLibrary=[{id:'preview_fn',name:'Preview Pass',scope:'builtin',source:{id:'preview_fn',version:'1'},stages:['pixel'],inputs:[{id:'value',name:'Value',type:'float',default:0}],outputs:[{id:'value',name:'Value',type:'float',default:0}],graph:{nodes:[{id:'in',definitionUuid:FunctionModel.INPUT,params:{},ui:{x:0,y:0}},{id:'out',definitionUuid:FunctionModel.OUTPUT,params:{},ui:{x:200,y:0}}],edges:[{from:['in','value'],to:['out','value']}]}}];});
const before=await page.evaluate(()=>JSON.stringify(graph));
const info=await page.evaluate(({id,kind,port,key})=>{const el=$('#cards').querySelector(`[data-node="${id}"] [data-kind="${kind}"][data-port="${port}"]`);if(!el)return {error:'port missing',ports:ports(current().nodes.find(n=>n.id===id),kind)};const r=el.getBoundingClientRect();openCreator(r.left+r.width/2,r.top+r.height/2,portInfo(el),{place:true});const index=creatorMatches.findIndex(m=>key==='function'?!!m.d.source:m.d.key===key);if(index<0)return{error:'candidate missing',keys:creatorMatches.map(m=>m.d.key)};const match=creatorMatches[index];chooseCreator(index);return {label:match.d.label,active:!!nodePlacement,status:$('#status').textContent};},{id,kind,port,key});
assert.equal(info.error,undefined,JSON.stringify({key,...info}));assert.equal(info.active,true,JSON.stringify({key,...info}));assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before,key+' preview must not create sources/functions');
await page.mouse.move(1050,650);await settle();const dims=await page.locator('.node-placement-outline').evaluate(e=>({width:parseFloat(e.style.width),height:parseFloat(e.style.height)}));
await page.mouse.click(1050,650);await settle();const actual=await page.evaluate(()=>{const c=$('#cards [data-node="'+selected+'"]');return c&&{width:c.offsetWidth,height:c.offsetHeight};});assert.ok(actual,key);assert.equal(actual.width,Math.round(dims.width),key+' width');assert.equal(actual.height,Math.round(dims.height),key+' height');assert.equal(await page.evaluate(()=>past.length),1,key);await page.evaluate(()=>undo());assert.equal(await page.evaluate(()=>JSON.stringify(graph)),before,key+' Undo');checks.push(key+' preview matches committed dimensions and leaves no source/function changes before placement');
}
assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,checks}));
}catch(e){await h.finish(e);console.error(e);process.exitCode=1;}})();
