/* Ordinary Parameter presentation and editing, using the isolated editor API. */
const assert=require('node:assert/strict'),path=require('node:path');
const {harness}=require('./test_glsl_code.cjs');
const [source,stateFile,folder]=process.argv.slice(2);
(async()=>{const h=await harness(source,stateFile,folder,{touch:true}),{page,checks,errors,settle}=h;page.setDefaultTimeout(6000);
const fields=(port='$value',copy='compact')=>page.locator(`#inspector [data-parameter-port="${port}"][data-parameter-copy="${copy}"]`);
const component=(i=0,port='$value',copy='compact')=>fields(port,copy).nth(i);
const snapshot=()=>page.evaluate(()=>JSON.stringify({graph,past,future}));
const choose=async id=>{await page.evaluate(id=>{document.activeElement?.blur();selected=id;selection=new Set([id]);selectedInputId=null;inspectorTab='parameters';inspector();},id);await settle();};
const reset=async()=>{await page.evaluate(()=>{
 cancelValueLadder();document.activeElement?.blur();clearTimeout(autoTimer);connectionInterrupted=true;conflicted=true;readonly=false;historyBusy=false;nativeMutationBusy=false;graphTrail=[];graph.functions=[];stage='pixel';selectedInputId=null;
 graph.declarations=[{id:'Live',kind:'uniform',name:'uLive',type:'float',value:.25}];
 graph.stages.pixel={nodes:[testNode('vector','vector',30,40,{type:'vec4',components:[.1,.2,.3,.4]}),testNode('float','float',30,250,{value:.3}),testNode('combine','combine',330,40,{type:'vec3',components:[0,0,0,0]}),testNode('replace','replace',330,300,{type:'vec3',components:[.2,.3,.4,0]}),testNode('color','color',30,440,{value:[.55,.28,.9,1]}),testNode('uniform','uniform',330,560,{declarationId:'Live'}),testNode('add','add',650,40,{type:'vec3'})],edges:[]};
 selected='vector';selection=new Set(['vector']);inspectorTab='parameters';past=[];future=[];dirty=false;rememberSavedGraph(graph);render();scale=.7;pan={x:20,y:20};transform();
});await settle();};
const typed=async(entry,value)=>{await entry.fill(value);await entry.press('Enter');await settle();};
const dragBegin=async(entry,percent)=>{await page.locator('#canvas').focus();const r=await entry.boundingBox(),p={x:r.x+r.width/2,y:r.y+r.height/2};await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+r.width*percent/100,p.y,{steps:5});await settle();return p;};
const read=()=>page.evaluate(()=>current().nodes.find(n=>n.id==='vector').params.components);
try{
 await reset();assert.equal(await fields().count(),4);assert.equal(await page.locator('#inspector [data-vector-type]').count(),1);
 const title=await page.locator('.node-inspector-title').innerText(),before=await snapshot();
 await page.locator('[data-parameter-expand="$value"]').click();assert.equal(await fields().count(),4);assert.equal(await fields('$value','component').count(),4);assert.equal(await fields('$value','component').first().isVisible(),true);assert.equal(await snapshot(),before);
 assert.equal(await component().evaluate(e=>getComputedStyle(e).borderTopWidth),'0px');
 const geometry=await page.locator('.parameter-value-row').first().evaluate(e=>{const h=e.querySelector('.parameter-value-heading').getBoundingClientRect(),c=e.querySelector('.parameter-value-controls').getBoundingClientRect();return{gap:Math.abs((h.top+h.bottom)/2-(c.top+c.bottom)/2),width:e.clientWidth,scroll:e.scrollWidth};});assert.ok(geometry.gap<1);assert.ok(geometry.scroll<=geometry.width+1);
 checks.push('ordinary vector values share one label/type/control row; expansion retains the full vector and adds components without graph or history writes');
 await typed(component(0),'0.12345678912345');assert.deepEqual(await read(),[.12345678912345,.2,.3,.4]);assert.equal(await component(0,'$value','component').inputValue(),'0.12345678912345');assert.equal(await page.evaluate(()=>past.length),1);
 await typed(component(1,'$value','component'),'.87654321098765');assert.deepEqual(await read(),[.12345678912345,.87654321098765,.3,.4]);assert.equal(await component(1).inputValue(),'0.87654321098765');assert.equal(await page.evaluate(()=>past.length),2);
 await page.locator('#undo').click();assert.deepEqual(await read(),[.12345678912345,.2,.3,.4]);await page.locator('#redo').click();assert.deepEqual(await read(),[.12345678912345,.87654321098765,.3,.4]);checks.push('compact and named components preserve all other values and manual precision; each edit is one Undo/Redo operation');
 await component(2).fill('');const emptyBefore=await snapshot();await page.evaluate(()=>{inspector();render();});assert.equal(await component(2).inputValue(),'');assert.equal(await component(2).evaluate(e=>e===document.activeElement),true);assert.equal(await snapshot(),emptyBefore);await component(2).press('Escape');assert.equal(await component(2).inputValue(),'0.3');assert.equal(await component(2,'$value','component').inputValue(),'0.3');
 const wasExpanded=await page.locator('[data-parameter-expand="$value"]').getAttribute('aria-expanded');await component(2).fill('.654321');await page.locator('[data-parameter-expand="$value"]').click();assert.equal(await page.locator('[data-parameter-expand="$value"]').getAttribute('aria-expanded'),wasExpanded==='true'?'false':'true');assert.equal((await read())[2],.654321);assert.equal(await page.evaluate(()=>past.length),3);
 checks.push('incomplete drafts survive harmless renders; Escape restores both copies and blur commits without swallowing the component toggle click');
 await reset();await page.locator('[data-parameter-expand="$value"]').click();let unchanged=await snapshot();await dragBegin(component(0,'$value','component'),20);
 const preview=Number(await component(0).inputValue());assert.ok(Math.abs(preview-.3)<=.0011);assert.ok(Math.abs(parseFloat(await component(0).evaluate(e=>e.style.getPropertyValue('--numeric-fill')))-30)<=.11);assert.equal(await snapshot(),unchanged);await page.evaluate(()=>render());assert.equal(Number(await component(0).inputValue()),preview);await page.keyboard.press('Escape');await page.mouse.up();await settle();assert.equal(await component(0).inputValue(),'0.1');assert.equal(await snapshot(),unchanged);
 await dragBegin(component(0),20);await page.mouse.up();await settle();assert.ok(Math.abs((await read())[0]-.3)<=.0011);assert.equal(Number(await component(0,'$value','component').inputValue()),(await read())[0]);assert.equal(await page.evaluate(()=>past.length),1);
 await component(1).click({button:'right'});await page.locator('[data-numeric-preset="0.5"]').click();assert.equal((await read())[1],.5);assert.equal(await component(1,'$value','component').inputValue(),'0.5');assert.equal(await page.evaluate(()=>past.length),2);
 checks.push('shared scrub and presets preview both controls/fills, cancel locally, and commit once');
 await page.locator('#inspector [data-vector-type]').selectOption('vec2');assert.equal(await fields().count(),2);assert.equal(await page.locator('.node-inspector-title').innerText(),title.replace('Vector 4','Vector 2'));assert.equal(await page.locator('.node-inspector-title select').count(),0);assert.equal(await page.locator('#inspector [data-vector-type]').count(),1);checks.push('output type stays in the top content row while the title remains node identity');
 await choose('combine');assert.equal(await component(0,'x').inputValue(),'0');await typed(component(0,'x'),'.123456789');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='combine').params.components[0]),.123456789);
 await page.evaluate(()=>connectPorts({node:'float',kind:'outputs',port:'out'},{node:'combine',kind:'inputs',port:'x'}));assert.equal(await fields('x').count(),0);assert.equal(await page.locator('#inspector [data-input="x"] .connection-row').count(),1);await page.locator('#inspector [data-input="x"] .connection-row button').click();assert.equal(await component(0,'x').inputValue(),'0.123456789');checks.push('zero input defaults stay editable; connected inputs show the source and disconnection restores their stored fallback');
 await choose('replace');assert.equal(await fields('value').count(),0);assert.equal(await component(0,'x').inputValue(),'0.2');await typed(component(0,'x'),'.7');
 await page.evaluate(()=>{const n=current().nodes.find(n=>n.id==='vector');n.params.type='vec3';render();connectPorts({node:'vector',kind:'outputs',port:'out'},{node:'replace',kind:'inputs',port:'value'});});assert.equal(await fields('x').count(),0);await page.locator('#inspector [data-input="value"] .connection-row button').click();assert.equal(await component(0,'x').inputValue(),'0.7');checks.push('Replace keeps its unconnected component fallback and hides inherited manual values only while a main input is connected');
 await choose('color');assert.equal(await page.locator('#inspector .color-parameter input[type=color]').count(),1);await page.locator('[data-parameter-expand="$value"]').click();assert.deepEqual(await page.locator('.parameter-component-row>span').allTextContents(),['R','G','B','A']);await typed(component(3,'$value','component'),'2.123456789');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='color').params.value[3]),2.123456789);assert.equal(await page.locator('#inspector .color-range-hint').count(),1);await typed(component(0),'.1');assert.equal(await page.locator('#inspector input[type=color]').inputValue(),'#1a47e6');await typed(component(3),'1');assert.equal(await page.locator('#inspector .color-range-hint').count(),0);checks.push('Color retains its picker, RGBA component labels, and unrestricted precision; numeric commits update the color preview and range hint');
 await choose('vector');await page.locator('#inspector [role=tab]').nth(1).click();const settings=await page.locator('#inspector').innerText();assert.equal(await page.locator('#inspector [data-node-comment]').count(),0);await page.locator('#inspector [role=tab]').nth(2).click();assert.equal(await page.locator('#inspector .node-notes-page textarea').count(),1);assert.equal(await page.locator('#inspector .node-notes-page summary').count(),0);const noteHistory=await page.evaluate(()=>past.length);await page.locator('[data-node-comment]').fill('A useful note\nSecond line');await page.locator('[data-node-comment]').press('Control+Enter');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='vector').ui.comment),'A useful note\nSecond line');assert.equal(await page.evaluate(()=>past.length),noteHistory+1);await page.locator('#inspector [role=tab]').nth(1).click();assert.equal(await page.locator('#inspector').innerText(),settings);checks.push('Notes has a dedicated tab and existing multiline commit semantics; Settings content is unaffected');
 await choose('uniform');assert.equal(await page.locator('#inspector [role=tab]').count(),2);assert.equal(await page.locator('#inspector [data-inspect-input="Live"]').count(),1);assert.equal(await page.locator('#inspector [data-parameter-node]').count(),0);assert.equal(await page.locator('#inspector .node-comment-field').count(),1);const sourceBody=await page.locator('#inspector').innerText();await page.locator('#inspector [role=tab]').nth(1).click();assert.equal(await page.locator('#inspector .node-identity').innerText(),'uniform');await page.locator('#inspector [role=tab]').nth(0).click();assert.equal(await page.locator('#inspector').innerText(),sourceBody);checks.push('Uniform source-reference editing, existing source controls, Settings and notes disclosure retain their original workflow');
 await choose('vector');await component(0).fill('.999');await page.evaluate(()=>{graph=clone(graph);render();});assert.notEqual(await component(0).inputValue(),'.999');assert.equal(await page.evaluate(()=>!!parameterValueEdit),false);
 await component(0).fill('.888');await page.evaluate(()=>{readonly=true;render();});assert.equal(await component(0).isDisabled(),true);assert.notEqual(await component(0).inputValue(),'.888');await page.locator('#inspector [role=tab]').nth(2).click();assert.equal(await page.locator('[data-node-comment]').isDisabled(),true);checks.push('graph replacement and read-only transitions discard stale drafts and disable numerical/Notes edits');
 await reset();await page.evaluate(()=>{const n=testNode('typed-code','glsl_code',650,350);n.params.inputs=[{id:'flag',name:'flag',type:'bool'},{id:'count',name:'count',type:'int'},{id:'mask',name:'mask',type:'uint'}];n.inputValues={flag:false,count:3,mask:0};n.params.code='c = flag ? float(count) : float(mask);';current().nodes.push(n);render();});await choose('typed-code');await page.locator('.code-input-values>summary').click();assert.equal(await component(0,'flag').evaluate(e=>e.tagName),'SELECT');await component(0,'flag').selectOption('true');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='typed-code').inputValues.flag),true);await page.locator('.code-input-values>summary').click();assert.equal(await component(0,'count').getAttribute('step'),'1');assert.equal(await component(0,'mask').getAttribute('min'),'0');await typed(component(0,'count'),'-7');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='typed-code').inputValues.count),-7);await typed(component(0,'mask'),'-1');assert.equal(await component(0,'mask').getAttribute('aria-invalid'),'true');assert.equal(await page.evaluate(()=>current().nodes.find(n=>n.id==='typed-code').inputValues.mask),0);await component(0,'mask').press('Escape');checks.push('GLSL Code input defaults retain bool selection and int/uint validation alongside the unchanged code editor');
 for(const type of ['vec2','vec3','vec4']){await reset();await page.locator('#inspector [data-vector-type]').selectOption(type);await page.locator('[data-parameter-expand="$value"]').click();const count=Number(type.slice(-1));assert.equal(await fields().count(),count);assert.equal(await fields('$value','component').count(),count);await typed(component(count-1,'$value','component'),'.9123456789');assert.equal((await read())[count-1],.9123456789);}
 await page.setViewportSize({width:960,height:780});for(const percent of [75,125]){await page.evaluate(percent=>setUIAppearance('scale',percent),percent);await settle();const sizes=await page.locator('#inspector .parameter-value-row').evaluateAll(rows=>rows.map(row=>({width:row.clientWidth,scroll:row.scrollWidth})));assert.ok(sizes.every(r=>r.scroll<=r.width+1),JSON.stringify(sizes));assert.equal(await fields().last().isVisible(),true);}
 checks.push('vec2/3/4 compact and expanded edits work, and all value rows fit the pane at UI 75% and 125% in a 960px viewport');
 await page.setViewportSize({width:1600,height:1100});await page.evaluate(()=>setUIAppearance('scale',100));await reset();await page.locator('[data-parameter-expand="$value"]').click();await page.screenshot({path:path.join(folder,'parameter-vector.png')});await choose('replace');await page.screenshot({path:path.join(folder,'parameter-replace.png')});await page.evaluate(()=>setUIAppearance('theme','light'));await choose('vector');await page.locator('[data-parameter-expand="$value"]').click();await page.screenshot({path:path.join(folder,'parameter-light.png')});
 assert.deepEqual(errors,[]);await h.finish();console.log(JSON.stringify({passed:true,count:checks.length}));
}catch(error){await h.finish(error);throw error;}})().catch(e=>{console.error(e.stack);process.exitCode=1;});
