// Isolated fixture: node test_creator_palette.cjs SOURCE_DIR STATE_JSON REPORT_DIR [OVERLAY_DIR]
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const[source,snapshotFile,folder,overlay]=process.argv.slice(2),original=JSON.parse(fs.readFileSync(snapshotFile,'utf8'));let state=structuredClone(original);fs.mkdirSync(folder,{recursive:true});
const server=http.createServer(async(req,res)=>{const name=new URL(req.url,'http://localhost').pathname;res.setHeader('Cache-Control','no-store');if(name.startsWith('/api/')){res.setHeader('Content-Type','application/json');let raw='';for await(const c of req)raw+=c;const body=raw?JSON.parse(raw):null,operation=name.split('/').at(-1);if(operation==='state')return res.end(JSON.stringify(state));if(operation==='apply'){state.state.graph=body.graph;state.state.revision++;return res.end(JSON.stringify(state));}if(operation==='uniforms')return res.end(JSON.stringify({revision:state.state.revision,uniforms:{},textures:{}}));if(operation==='preview'){res.statusCode=204;return res.end();}res.statusCode=404;return res.end('{}');}const filename=name==='/'?'index.html':path.basename(name),candidate=overlay&&path.join(overlay,filename),file=candidate&&fs.existsSync(candidate)?candidate:path.join(source,filename);if(!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_EXECUTABLE}),checks=[],errors=[];try{const page=await browser.newPage({viewport:{width:1600,height:1040}});page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/#fixture');await page.waitForSelector('.node');await page.evaluate(()=>{window.testInitial=clone(graph);});

await page.selectOption('#language','en');
await page.evaluate(()=>{
  graph=clone(window.testInitial);stage='pixel';graphTrail=[];
  const color=instantiate(catalog.find(d=>d.key==='color'),80,380);color.id='color_check';color.params.value=[1.4,-.2,.25,.35];
  const vec=instantiate(catalog.find(d=>d.key==='vec3'),400,430);vec.id='vector_check';
  selection=new Set(['color_check']);selected='color_check';render();fit();
});
const originalGraph=await page.evaluate(()=>clone(graph)),originalColor=[1.4,-.2,.25,.35];
assert.equal(await page.locator('[data-node="color_check"] .node-color .color-ink').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(255, 0, 64, 0.35)');
assert.equal(await page.locator('#inspector input[type=color]').count(),1);assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='color_check').params.value),originalColor);checks.push('Color RGBA shows browser-only alpha swatches; display clamps do not change HDR/negative values');
await page.locator('#inspector input[type=color]').dispatchEvent('change');assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='color_check').params.value),originalColor);checks.push('unchanged color picker value leaves original extended-range RGB intact');
const pastStart=await page.evaluate(()=>past.length);
await page.locator('#inspector input[type=color]').evaluate(e=>{e.value='#336699';e.dispatchEvent(new Event('change',{bubbles:true}));});
assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='color_check').params.value),[.2,.4,.6,.35]);assert.equal(await page.evaluate(()=>past.length),pastStart+1);checks.push('choosing RGB retains exact Alpha and creates one undo step');
await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>current().nodes.find(n=>n.id==='color_check').params.value),originalColor);await page.locator('#redo').click();
await page.locator('#inspector input[type=number]').last().fill('0.7');await page.locator('#inspector input[type=number]').last().press('Enter');assert.equal(await page.locator('[data-node="color_check"] .node-color .color-ink').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(51, 102, 153, 0.7)');checks.push('numeric Alpha edits update both swatches, with Undo/Redo preserved');
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='vector_check'));inspector();});assert.equal(await page.locator('#inspector input[type=color]').count(),0);assert.equal(await page.locator('[data-node="vector_check"] .node-color').count(),0);checks.push('ordinary vectors do not gain color semantics or a picker');

await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='color_check'));inspector();});
const beforeLabel=await page.evaluate(()=>clone(graph));await page.locator('[data-node-label]').fill('Accent / 主色');await page.locator('[data-node-label]').press('Enter');
assert.equal(await page.locator('[data-node="color_check"] .node-alias').innerText(),'Accent / 主色');assert.equal(await page.locator('[data-node="color_check"] .node-function-title').innerText(),'Color RGBA');
const afterLabel=await page.evaluate(()=>clone(graph));fs.writeFileSync(path.join(folder,'label-graphs.json'),JSON.stringify({before:beforeLabel,after:afterLabel}));checks.push('custom label remains subordinate to the functional title and is stored in UI metadata');
await page.locator('#undo').click();assert.equal(await page.locator('[data-node="color_check"] .node-alias').count(),0);await page.locator('#redo').click();
await page.locator('[data-node="color_check"] .node-alias').dblclick();assert.equal(await page.locator('[data-node-label]').evaluate(e=>document.activeElement===e),true);await page.locator('[data-node-label]').fill('cancel me');await page.locator('[data-node-label]').press('Escape');assert.equal(await page.locator('[data-node-label]').inputValue(),'Accent / 主色');checks.push('label double-click focuses Parameter; Escape cancels and undo restores the label');
const history=await page.evaluate(()=>past.length);assert.equal(await page.evaluate(()=>setNodeLabel(current().nodes.find(n=>n.id===selected),'x\ny')),false);assert.equal(await page.evaluate(()=>past.length),history);checks.push('invalid multiline labels are rejected without changes');
await page.locator('[data-node-label]').fill('<b>Plain text</b>');await page.locator('[data-node-label]').press('Enter');assert.equal(await page.locator('[data-node="color_check"] .node-alias b').count(),0);assert.equal(await page.locator('[data-node="color_check"] .node-alias').innerText(),'<b>Plain text</b>');checks.push('labels are literal text, never HTML');
await page.locator('[data-node-label]').fill('Accent / 主色');await page.locator('[data-node-label]').press('Enter');
await page.evaluate(()=>duplicateSelection());assert.equal(await page.evaluate(()=>nodeLabel(current().nodes.find(n=>n.id===selected))),'Accent / 主色');
await page.evaluate(()=>groupSelection());const grouped=await page.evaluate(()=>FunctionModel.find(graph,current().nodes.find(n=>n.id===selected).params.functionId).graph.nodes.some(n=>nodeLabel(n)==='Accent / 主色'));assert.equal(grouped,true);checks.push('duplication and grouping retain node labels');

await page.evaluate(()=>{const node=instantiate(catalog.find(d=>d.key==='uniform'),530,450);node.id='uniform_check';selected=node.id;selection=new Set([node.id]);node.ui.label='Exposure';const decl=graph.declarations.find(d=>d.id===node.params.declarationId);decl.expose=false;delete decl.exposeName;render();});
await page.locator('#inspector .toggle-field input').check();assert.equal(await page.evaluate(()=>graph.declarations.find(d=>d.id===current().nodes.find(n=>n.id===selected).params.declarationId).exposeName),'Exposure');
await page.locator('[data-node-label]').fill('Different local name');await page.locator('[data-node-label]').press('Enter');assert.equal(await page.evaluate(()=>graph.declarations.find(d=>d.id===current().nodes.find(n=>n.id===selected).params.declarationId).exposeName),'Exposure');checks.push('first Expose adopts the label; later label edits preserve the public parameter name');
await page.locator('#inspector .toggle-field input').uncheck();await page.locator('#inspector .toggle-field input').check();assert.equal(await page.evaluate(()=>graph.declarations.find(d=>d.id===current().nodes.find(n=>n.id===selected).params.declarationId).exposeName),'Exposure');checks.push('toggling Expose preserves an existing public label');
await page.evaluate(()=>{selectNode(current().nodes.find(n=>n.id==='color_check'));inspector();});await page.setViewportSize({width:850,height:820});await page.waitForTimeout(100);
const rectangles=await page.locator('#inspector .color-parameter input[type=number]').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return {y:b.y,right:b.right,left:b.left};}));assert.equal(new Set(rectangles.map(r=>r.y)).size,1);const bounds=await page.locator('#inspector').boundingBox();assert.ok(rectangles.every(r=>r.left>=bounds.x&&r.right<=bounds.x+bounds.width+1));checks.push('RGBA numeric controls remain on a single row at the minimum sidebar width');
await page.setViewportSize({width:1440,height:1040});await page.evaluate(()=>fit());await page.screenshot({path:path.join(folder,'color-labels.png')});
await page.evaluate(()=>{readonly=true;inspector();});assert.equal(await page.locator('#inspector input[type=color]').isDisabled(),true);assert.equal(await page.locator('[data-node-label]').isDisabled(),true);checks.push('read-only graphs disable color and label editing');

assert.deepEqual(errors,[]);fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:true,count:checks.length,checks},null,2));console.log(JSON.stringify({passed:true,count:checks.length}));}catch(e){fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify({passed:false,checks,errors,error:e.message},null,2));console.error(e.stack);throw e;}finally{await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e.message);process.exitCode=1;});