/** TD built-in values (design-interview Q45 01, discuss-4.14 §10–11): what TD's GLSL already
 * provides and a shader only reads — one line of GLSL, one output, one type. One node type
 * (`sgrape.builtin.td_value`) picks an entry by `id`; no declaration is needed, so it may be used
 * inside subgraphs (Q46). `id` is stored in graphs and never changes; `name` is the canvas title;
 * `hint` is the English original (translations: locales, code tdValue.<id>, Q34).
 * Moved from the legacy source catalog `builtins` (checked there with TD TouchDesigner 2025.32820);
 * vUV.st and TDPos() added (Q45); vUV.st folded into vUV's UV output (Refactor.64). The 15 TOP entries usable now were compiled again in TD 2025.33230 (Refactor.41). Entries whose type the core cannot carry yet (samplers, structs,
 * arrays, matrices) wait for their rounds; a graph that uses one shows a ghost.
 * TD 內建值：TD 的 GLSL 已經提供、Shader 只讀的東西。一個節點類型依 id 選一筆；不需要宣告。
 * 由舊來源目錄搬來（舊目錄以上述 TD 版本核對）；補 vUV.st、TDPos()。 */
export interface TdValue {
  readonly id: string; readonly name: string; readonly expression: string; readonly type: string;
  readonly targets: readonly string[]; readonly stages: readonly string[]; readonly category: readonly string[];
  readonly hint: string; readonly helpUrl: string;
  /** Common identity (common_sources.json, Q61) when almost every host provides it. 共同身分。 */
  readonly common?: string;
  /** Several outputs read from one value (Refactor.64, human 2026-10-10: one UV node with U, UV, UVW); without it the
   * node has one output `out` of `type` reading `expression`. 一個值讀出幾個輸出（人類：一個 UV 節點、U／UV／UVW 三個輸出）；
   * 沒有就是一個 `out` 輸出。 */
  readonly outputs?: readonly TdValueOutput[];
}
/** One output of a TD built-in value: its port key (stored in wires), label, GLSL and type. 內建值的一個輸出。 */
export interface TdValueOutput { readonly key: string; readonly label: string; readonly expression: string; readonly type: string }
export const tdValues: readonly TdValue[] = Object.freeze([
  {"id": "uTD2DInfos", "name": "uTD2DInfos", "expression": "uTD2DInfos", "type": "TDTexInfo[TD_NUM_2D_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2d"], "hint": "Metadata for each input texture of this dimension. res.xy is reciprocal size and res.zw is size.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTD2DInputs", "name": "sTD2DInputs", "expression": "sTD2DInputs", "type": "sampler2D[TD_NUM_2D_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2d"], "hint": "Array of connected sampler2D resources, grouped by texture dimension. Select an array item before sampling.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTDMats", "name": "uTDMats", "expression": "uTDMats", "type": "TDMatrix[TD_NUM_CAMERAS]", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "matrices"], "hint": "Camera-indexed transforms between geometry, world, camera and projection spaces. Select a camera entry, then its matrix field.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "uTDCamInfos", "name": "uTDCamInfos", "expression": "uTDCamInfos", "type": "TDCameraInfo[TD_NUM_CAMERAS]", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "cameras"], "hint": "Per-camera information supplied by the render pass, including camera projection data.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "uTDLights", "name": "uTDLights", "expression": "uTDLights", "type": "TDLight[TD_NUM_LIGHTS]", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Per-light data for regular lights in the current render pass. Environment lights have a separate array.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "tdNum2dInputs", "name": "TD_NUM_2D_INPUTS", "expression": "TD_NUM_2D_INPUTS", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2d"], "hint": "Compile-time number of 2d inputs in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTD3DInputs", "name": "sTD3DInputs", "expression": "sTD3DInputs", "type": "sampler3D[TD_NUM_3D_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "3d"], "hint": "Array of connected sampler3D resources, grouped by texture dimension. Select an array item before sampling.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTD3DInfos", "name": "uTD3DInfos", "expression": "uTD3DInfos", "type": "TDTexInfo[TD_NUM_3D_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "3d"], "hint": "Metadata for each input texture of this dimension. res.xy is reciprocal size and res.zw is size.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "tdNum3dInputs", "name": "TD_NUM_3D_INPUTS", "expression": "TD_NUM_3D_INPUTS", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "3d"], "hint": "Compile-time number of 3d inputs in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTD2DArrayInputs", "name": "sTD2DArrayInputs", "expression": "sTD2DArrayInputs", "type": "sampler2DArray[TD_NUM_2D_ARRAY_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2dArray"], "hint": "Array of connected sampler2DArray resources, grouped by texture dimension. Select an array item before sampling.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTD2DArrayInfos", "name": "uTD2DArrayInfos", "expression": "uTD2DArrayInfos", "type": "TDTexInfo[TD_NUM_2D_ARRAY_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2dArray"], "hint": "Metadata for each input texture of this dimension. res.xy is reciprocal size and res.zw is size.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "tdNum2dArrayInputs", "name": "TD_NUM_2D_ARRAY_INPUTS", "expression": "TD_NUM_2D_ARRAY_INPUTS", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "2dArray"], "hint": "Compile-time number of 2d array inputs in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTDCubeInputs", "name": "sTDCubeInputs", "expression": "sTDCubeInputs", "type": "samplerCube[TD_NUM_CUBE_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "cube"], "hint": "Array of connected samplerCube resources, grouped by texture dimension. Select an array item before sampling.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTDCubeInfos", "name": "uTDCubeInfos", "expression": "uTDCubeInfos", "type": "TDTexInfo[TD_NUM_CUBE_INPUTS]", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "cube"], "hint": "Metadata for each input texture of this dimension. res.xy is reciprocal size and res.zw is size.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "tdNumCubeInputs", "name": "TD_NUM_CUBE_INPUTS", "expression": "TD_NUM_CUBE_INPUTS", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["textures", "cube"], "hint": "Compile-time number of cube inputs in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTDOutputInfo", "name": "uTDOutputInfo", "expression": "uTDOutputInfo", "type": "TDTexInfo", "targets": ["top"], "stages": ["pixel"], "category": ["tdBuiltin", "render"], "hint": "Output texture metadata. res.xy contains reciprocal dimensions; res.zw contains width and height.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTDOutputInfoResZw", "name": "uTDOutputInfo.res.zw", "expression": "uTDOutputInfo.res.zw", "type": "vec2", "targets": ["top"], "stages": ["pixel"], "category": ["common", "output"], "hint": "Output width and height in pixels.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms", "common": "resolution"},
  {"id": "uTDOutputInfoResXy", "name": "uTDOutputInfo.res.xy", "expression": "uTDOutputInfo.res.xy", "type": "vec2", "targets": ["top"], "stages": ["pixel"], "category": ["common", "output"], "hint": "Reciprocal output width and height.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  // One UV node, three outputs (Refactor.64, human 2026-10-10; was vUV vec3 and vUV.st vec2 as two entries): U for 1D lookups such
  // as sTDSineLookup, UV for 2D, UVW for 3D, Cube and 2D Array. 一個 UV 節點、三個輸出（原本 vUV 與 vUV.st 兩筆）：U 給 1D、UV 給 2D、
  // UVW 給 3D／Cube／2D Array。
  {"id": "vUV", "name": "vUV", "expression": "vUV", "type": "vec3", "targets": ["top"], "stages": ["pixel"], "category": ["common", "coordinates"], "hint": "Texture coordinates of this pixel, from 0 to 1: U for 1D, UV for 2D, UVW for 3D, Cube and 2D Array textures.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP", "common": "uv", "outputs": [{"key": "u", "label": "U", "expression": "vUV.s", "type": "float"}, {"key": "uv", "label": "UV", "expression": "vUV.st", "type": "vec2"}, {"key": "uvw", "label": "UVW", "expression": "vUV.stp", "type": "vec3"}]},
  {"id": "uTDPass", "name": "uTDPass", "expression": "uTDPass", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["tdBuiltin", "render"], "hint": "Zero-based GLSL TOP pass index for multipass rendering.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "uTDCurrentDepth", "name": "uTDCurrentDepth", "expression": "uTDCurrentDepth", "type": "int", "targets": ["top"], "stages": ["pixel"], "category": ["tdBuiltin", "render"], "hint": "Current output depth index when producing a layered or 3D TOP texture.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTDNoiseMap", "name": "sTDNoiseMap", "expression": "sTDNoiseMap", "type": "sampler2D", "targets": ["top"], "stages": ["pixel"], "category": ["tdBuiltin", "resources"], "hint": "TD-provided noise lookup texture; connect it to a compatible texture sampling input.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "sTDSineLookup", "name": "sTDSineLookup", "expression": "sTDSineLookup", "type": "sampler1D", "targets": ["top"], "stages": ["pixel"], "category": ["tdBuiltin", "resources"], "hint": "TD-provided one-dimensional sine lookup texture. TDSineLookup provides a direct lookup function.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_TOP#Built-in_Uniforms"},
  {"id": "glFragCoord", "name": "gl_FragCoord", "expression": "gl_FragCoord", "type": "vec4", "targets": ["top", "mat"], "stages": ["pixel"], "category": ["common", "coordinates"], "hint": "The current fragment position in window coordinates.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf", "common": "fragCoord"},
  {"id": "glFrontFacing", "name": "gl_FrontFacing", "expression": "gl_FrontFacing", "type": "bool", "targets": ["top", "mat"], "stages": ["pixel"], "category": ["common", "shaderInfo"], "hint": "Whether this fragment belongs to a front-facing primitive.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf"},
  {"id": "glSampleID", "name": "gl_SampleID", "expression": "gl_SampleID", "type": "int", "targets": ["top", "mat"], "stages": ["pixel"], "category": ["common", "shaderInfo"], "hint": "Index of the current multisample sample.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf"},
  {"id": "glSamplePosition", "name": "gl_SamplePosition", "expression": "gl_SamplePosition", "type": "vec2", "targets": ["top", "mat"], "stages": ["pixel"], "category": ["common", "shaderInfo"], "hint": "The current sample position within its pixel.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf"},
  {"id": "glHelperInvocation", "name": "gl_HelperInvocation", "expression": "gl_HelperInvocation", "type": "bool", "targets": ["top", "mat"], "stages": ["pixel"], "category": ["common", "shaderInfo"], "hint": "Whether this is a helper invocation used for derivatives.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf"},
  {"id": "tdNormal", "name": "TDNormal", "expression": "TDNormal()", "type": "vec3", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Normal of the current vertex before TD geometry deformation. Use TDDeformNorm for a deformed world-space normal.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Working_with_Geometry_Attributes"},
  {"id": "tdPointColor", "name": "TDPointColor", "expression": "TDPointColor()", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Color attribute of the current point, including alpha.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Working_with_Geometry_Attributes"},
  {"id": "tduvUnwrapCoord", "name": "TDUVUnwrapCoord", "expression": "TDUVUnwrapCoord()", "type": "vec3", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Coordinates used for the current UV-unwrapping render configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Common_Functions"},
  {"id": "tdInstanceID", "name": "TDInstanceID", "expression": "TDInstanceID()", "type": "int", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Instance index supplied by TD for the geometry being rendered.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdCameraIndex", "name": "TDCameraIndex", "expression": "TDCameraIndex()", "type": "int", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "cameras"], "hint": "Camera index within the current render pass. Pass it flat to Pixel when indexing camera-specific data there.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Common_Functions"},
  {"id": "tdTrueCameraIndex", "name": "TDTrueCameraIndex", "expression": "TDTrueCameraIndex()", "type": "int", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "cameras"], "hint": "Camera index in the full camera list, as distinguished from the current pass index.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Common_Functions"},
  {"id": "tdTexCoord", "name": "TDTexCoord", "expression": "TDTexCoord({layer})", "type": "vec3", "targets": ["mat"], "stages": ["vertex"], "category": ["common", "coordinates"], "hint": "Texture coordinates from the selected UV layer.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Working_with_Geometry_Attributes"},
  {"id": "tdBoneMat", "name": "TDBoneMat", "expression": "TDBoneMat({boneIndex})", "type": "mat4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Bone transform matrix for the selected bone index.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Common_Functions"},
  {"id": "tdInstanceMat", "name": "TDInstanceMat", "expression": "TDInstanceMat({instanceIndex})", "type": "mat4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Four-by-four transform matrix for the selected geometry instance.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceMat3", "name": "TDInstanceMat3", "expression": "TDInstanceMat3({instanceIndex})", "type": "mat3", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Three-by-three transform matrix for the selected geometry instance.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceTextureIndex", "name": "TDInstanceTextureIndex", "expression": "TDInstanceTextureIndex({instanceIndex})", "type": "uint", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "instances"], "hint": "Texture index associated with the selected geometry instance.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceCustomAttrib0", "name": "TDInstanceCustomAttrib0", "expression": "TDInstanceCustomAttrib0({instanceIndex})", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Custom instance attribute slot 0 as four components.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceCustomAttrib1", "name": "TDInstanceCustomAttrib1", "expression": "TDInstanceCustomAttrib1({instanceIndex})", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Custom instance attribute slot 1 as four components.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceCustomAttrib2", "name": "TDInstanceCustomAttrib2", "expression": "TDInstanceCustomAttrib2({instanceIndex})", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Custom instance attribute slot 2 as four components.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdInstanceCustomAttrib3", "name": "TDInstanceCustomAttrib3", "expression": "TDInstanceCustomAttrib3({instanceIndex})", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "instances"], "hint": "Custom instance attribute slot 3 as four components.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Instancing"},
  {"id": "tdPointCoord", "name": "TDPointCoord", "expression": "TDPointCoord()", "type": "vec2", "targets": ["mat"], "stages": ["pixel"], "category": ["common", "coordinates"], "hint": "Coordinates within the point being rendered.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#Common_Functions"},
  {"id": "uTDGeneral", "name": "uTDGeneral", "expression": "uTDGeneral", "type": "TDGeneral", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "render"], "hint": "General render state, including combined ambient-light color and viewport information.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "uTDGeneralAmbientColor", "name": "uTDGeneral.ambientColor", "expression": "uTDGeneral.ambientColor", "type": "vec4", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Combined ambient-light color from the ambient lights used by this render pass.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "viewportOrigin", "name": "Viewport Origin", "expression": "uTDGeneral.viewport.xy", "type": "vec2", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["common", "output"], "hint": "Origin of the current viewport.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "viewportResolution", "name": "Viewport Resolution", "expression": "(1.0 / uTDGeneral.viewport.zw)", "type": "vec2", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["common", "output"], "hint": "Width and height of the current viewport.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "uTDEnvLights", "name": "uTDEnvLights", "expression": "uTDEnvLights", "type": "TDEnvLight[TD_NUM_ENV_LIGHTS]", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Environment-light settings for the current render pass.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "tdNumLights", "name": "TD_NUM_LIGHTS", "expression": "TD_NUM_LIGHTS", "type": "int", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Compile-time number of regular lights in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_defines"},
  {"id": "tdNumEnvLights", "name": "TD_NUM_ENV_LIGHTS", "expression": "TD_NUM_ENV_LIGHTS", "type": "int", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Compile-time number of environment lights in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_defines"},
  {"id": "tdNumCameras", "name": "TD_NUM_CAMERAS", "expression": "TD_NUM_CAMERAS", "type": "int", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "cameras"], "hint": "Compile-time number of cameras in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_defines"},
  {"id": "tdNumColorBuffers", "name": "TD_NUM_COLOR_BUFFERS", "expression": "TD_NUM_COLOR_BUFFERS", "type": "int", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "render"], "hint": "Compile-time number of color buffers in this shader configuration.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_defines"},
  {"id": "uTDEnvLightBuffersShCoeffs", "name": "uTDEnvLightBuffers.shCoeffs", "expression": "uTDEnvLightBuffers[{lightIndex}].shCoeffs", "type": "vec3[9]", "targets": ["mat"], "stages": ["vertex", "pixel"], "category": ["tdBuiltin", "lights"], "hint": "Nine RGB spherical-harmonic coefficients for the selected environment light.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT#TouchDesigner_specific_Uniforms"},
  {"id": "glVertexIndex", "name": "gl_VertexIndex", "expression": "gl_VertexIndex", "type": "int", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Index of the current vertex. This is an identity, not an attribute lookup for another vertex.", "helpUrl": "https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf"},
  {"id": "tdScreenSpaceCoord", "name": "TDScreenSpaceCoord", "expression": "TDScreenSpaceCoord().st", "type": "vec2", "targets": ["mat"], "stages": ["pixel"], "category": ["tdBuiltin", "geometry"], "hint": "Screen-space texture coordinates used by native MAT screen-space map sampling. Returns the st components.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT"},
  {"id": "tdInstanceIndex", "name": "TDInstanceIndex", "expression": "TDInstanceIndex()", "type": "int", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Current instance index used by native MAT. Pass through a flat Vertex Output to use indexed TDInstanceColor in Pixel Stage.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT"},
  {"id": "tdColor", "name": "TDColor", "expression": "TDColor()", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Geometry color used by native Phong/PBR before current-instance color is applied. This is the native TDColor accessor, distinct from TDPointColor.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_MAT"},
  {"id": "tdPos", "name": "TDPos", "expression": "TDPos()", "type": "vec4", "targets": ["mat"], "stages": ["vertex"], "category": ["tdBuiltin", "geometry"], "hint": "Position of this vertex in SOP space.", "helpUrl": "https://derivative.ca/UserGuide/Write_a_GLSL_Material"},
].map(entry => Object.freeze(entry)));
