/* Collapse uses real editor history; rendering and network effects are stubbed. */
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const payload=JSON.parse(fs.readFileSync(0,'utf8')),dir=path.resolve(__dirname,'../../src/editor');
const elements=new Map(),element=key=>{if(!elements.has(key))elements.set(key,{value:'',textContent:'',title:'',hidden:false,disabled:false,focus(){},replaceChildren(){},setAttribute(){},addEventListener(){},classList:{add(){},remove(){},toggle(){}}});return elements.get(key);};
const context=vm.createContext({assert,payload,console,TextEncoder,crypto:globalThis.crypto,location:{pathname:'/',hash:''},history:{replaceState(){}},window:{addEventListener(){}},document:{addEventListener(){},querySelector:element,querySelectorAll:()=>[]},sessionStorage:{getItem(){return '';},setItem(){}},setTimeout(){return 1;},clearTimeout(){}});
for(const file of ['functions_model.js','functions_ui.js','graph_ui.js','inspector.js'])vm.runInContext(fs.readFileSync(path.join(dir,file),'utf8'),context);
const app=fs.readFileSync(path.join(dir,'app.js'),'utf8');vm.runInContext(app.slice(0,app.indexOf("$('#canvas').addEventListener('dragover'")),context);
vm.runInContext(`(async()=>{
render=()=>{};wires=()=>{};renderGraphEditActions=()=>{};renderHistoryActions=()=>{};inspector=()=>{};renderNavigation=()=>{};renderNativeSourceValues=()=>{};refreshUniforms=()=>{};refreshNativeSources=async()=>{};
catalog=payload.catalog;setTypeContract(payload.contract);editorTarget='top';graph=clone(payload.graph);stage='pixel';graphTrail=[];past=[];future=[];readonly=false;
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b)),n=id=>current().nodes.find(n=>n.id===id),checks=[],pairs=[];
rememberSavedGraph(graph);const baseline=clone(graph),semantic=graphContent(graph);
assert.equal(setNodesCollapsed(['value'],true),true);assert.equal(n('value').ui.collapsed,true);assert.equal(n('value').ui.width,460);
assert.equal(past.length,1);equal(current().edges,baseline.stages.pixel.edges);assert.equal(graphContent(graph),semantic);assert.equal(hasShaderChanges(),false);assert.equal(dirty,true);
const compact=clone(graph);pairs.push({before:baseline,after:compact});
assert.equal(setNodesCollapsed(['value'],true),false);assert.equal(past.length,1);
await undo();equal(graph,baseline);assert.equal(future.length,1);await undo(true);equal(graph,compact);
checks.push('one layout-only history entry, no-op suppression, exact Undo/Redo and retained expanded width');
selection=new Set(['value','result']);equal(nodeCollapseSelection().map(n=>n.id),['value','result']);
let count=past.length;assert.equal(setNodesCollapsed(nodeCollapseSelection().map(n=>n.id),true),true);assert.equal(past.length,count+1);assert.equal(n('result').ui.collapsed,true);
count=past.length;assert.equal(setNodesCollapsed(['value','result'],false),true);assert.equal(past.length,count+1);assert.ok(current().nodes.every(n=>n.ui.collapsed===false));
assert.equal(n('value').ui.width,460);assert.equal(graphContent(graph),semantic);await undo();assert.ok(current().nodes.every(n=>n.ui.collapsed));
checks.push('mixed batches collapse and expand all selected nodes, including protected outputs, in one step');
const inert=JSON.stringify({graph,past,future});readonly=true;assert.equal(setNodesCollapsed(['value'],false),false);assert.equal(JSON.stringify({graph,past,future}),inert);readonly=false;
assert.equal(setNodesCollapsed(['missing'],true),false);assert.equal(JSON.stringify({graph,past,future}),inert);
checks.push('read-only and nonexistent targets do not change graph or history');
const encoded=GraphClipboard.encode(graph,current(),['value'],'fixture'),decoded=GraphClipboard.decode(encoded);
const ids=GraphClipboard.paste(graph,current(),decoded,{source:'fixture',stage:'pixel',target:'top',catalog,types:interfaceTypes(),anchor:{x:600,y:200}});
const copied=n(ids[0]);assert.equal(copied.ui.collapsed,true);assert.equal(copied.ui.width,460);assert.equal(copied.ui.componentsExpanded,true);
const exported=JSON.parse(JSON.stringify(graph));assert.equal(exported.stages.pixel.nodes.find(item=>item.id===ids[0]).ui.collapsed,true);
checks.push('selection copy/paste and exported JSON retain collapse, width and independent component expansion');
graph=clone(payload.graph);past=[];future=[];const imported=FunctionModel.importLibrary(graph,payload.function);graphTrail=[imported.id];
const inner=current().nodes.find(item=>item.definitionUuid!==FunctionModel.INPUT&&item.definitionUuid!==FunctionModel.OUTPUT)||current().nodes[0];
inner.ui={...(inner.ui||{}),width:350};rememberSavedGraph(graph);const source=clone(graph),sourceContent=graphContent(graph),sourceId=imported.id;
assert.equal(setNodesCollapsed([inner.id],true),true);assert.equal(currentFunction().scope,imported.scope);assert.equal(currentFunction().id,sourceId);assert.equal(graphContent(graph),sourceContent);
pairs.push({before:source,after:clone(graph)});
const map=FunctionModel.localize(graph,sourceId),localized=FunctionModel.find(graph,map.get(sourceId));
assert.equal(localized.scope,'local');const retained=localized.graph.nodes.find(item=>item.id===inner.id);assert.equal(retained.ui.collapsed,true);assert.equal(retained.ui.width,350);
checks.push('collapse does not localize source Subgraphs, and later localization preserves their view state');
console.log(JSON.stringify({passed:true,checks,pairs}));
})()`,context).catch(error=>{console.error(error);process.exitCode=1;});
