const assert=require('node:assert/strict'),m=require('../../src/editor/functions_model.js');
const call=(id,fn)=>({id,definitionUuid:m.CALL,params:{functionId:fn}});
const fresh=()=>({stages:{pixel:{nodes:[],edges:[]}},functions:[]});
const child={id:'child',scope:'personal',source:{id:'personal.child',version:'v1'},graph:{nodes:[],edges:[]}};
const root={id:'root',scope:'personal',source:{id:'personal.root',version:'v1'},graph:{nodes:[call('nested','child')],edges:[]},dependencies:[child]};
const graph=fresh();graph.functions.push({id:'child',scope:'local',graph:{nodes:[],edges:[]}});
const f=m.importLibrary(graph,root),nested=f.graph.nodes[0].params.functionId;
assert.notEqual(nested,'child');assert.equal(graph.functions.length,3);assert.equal(m.importLibrary(graph,root),f);
assert.equal(graph.functions.length,3);assert.ok(!('dependencies' in f));
graph.stages.pixel.nodes.push(call('a',f.id),call('b',f.id));
const before=structuredClone(graph),rootId=f.id,map=m.localize(graph,nested);
assert.equal(map.size,2);assert.equal(graph.stages.pixel.nodes[0].params.functionId,map.get(rootId));
assert.equal(graph.stages.pixel.nodes[1].params.functionId,map.get(rootId));
assert.deepEqual(m.find(graph,'root'),before.functions.find(f=>f.id==='root'));
assert.deepEqual(m.find(graph,nested),before.functions.find(f=>f.id===nested));
assert.deepEqual(root.dependencies[0],child);
const another=fresh();m.importLibrary(another,root);assert.equal(another.functions.length,2);
const broken=fresh(),bad=structuredClone(root);bad.dependencies=[];
assert.throws(()=>m.importLibrary(broken,bad),/Missing nested/);assert.equal(broken.functions.length,0);
const crowded=fresh();for(let i=0;i<63;i++)crowded.functions.push({id:'f'+i,scope:'local'});
assert.throws(()=>m.importLibrary(crowded,root),/64/);assert.equal(crowded.functions.length,63);
console.log('Personal model: nested import, collision remap, reuse, isolation, atomic failure, capacity and copy-on-write passed');
