const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto').webcrypto;
const code=fs.readFileSync('src/editor/functions_model.js','utf8');
const context={crypto,TextEncoder,console};vm.createContext(context);
vm.runInContext(code+'\nglobalThis.models={GraphTypeDefinitions,GraphClipboard,FunctionModel};',context);
const {GraphClipboard:clipboard,FunctionModel:fn,GraphTypeDefinitions:defs}=context.models;
const shape={id:'sample',name:'Sample',provider:'generated',fields:[{id:'position',name:'position',type:'vec2'}]};
const graph=()=>({declarations:[],functions:[],stages:{pixel:{nodes:[],edges:[]}}});
const source=graph();source.typeDefinitions=[shape];
source.stages.pixel.nodes.push({id:'array',definitionUuid:'sgrape.builtin.array',params:{elementType:'struct:sample',length:4},ui:{x:0,y:0}});
const packet=clipboard.decode(clipboard.encode(source,source.stages.pixel,['array'],'one'));
const destination=graph(),options={source:'two',stage:'pixel',target:'top',types:['float','vec2'],catalog:[{key:'array',definitionUuid:'sgrape.builtin.array',stages:['pixel']}],anchor:{x:10,y:10}};
clipboard.paste(destination,destination.stages.pixel,packet,options);
assert.equal(JSON.stringify(destination.typeDefinitions),JSON.stringify([shape]));
assert.equal(destination.stages.pixel.nodes[0].params.elementType,'struct:sample');
const conflict=graph();conflict.typeDefinitions=[{...shape,fields:[{id:'position',name:'position',type:'vec3'}]}];
const before=JSON.stringify(conflict);
assert.throws(()=>clipboard.paste(conflict,conflict.stages.pixel,packet,options));
assert.equal(JSON.stringify(conflict),before);
assert.equal(defs.valid('struct:sample[4]',['float'],[shape]),true);
assert.equal(defs.valid('float[0]',['float'],[]),false);
const personal={id:'p',name:'Pass',scope:'personal',source:{id:'p',version:'1'},inputs:[{id:'sample',type:'struct:sample'}],outputs:[],graph:{nodes:[],edges:[]},typeDefinitions:[shape]};
const imported=graph();fn.importLibrary(imported,personal);
assert.equal(JSON.stringify(imported.typeDefinitions),JSON.stringify([shape]));
const plain=graph();plain.typeDefinitions=[shape];plain.stages.pixel.nodes.push({id:'plain',definitionUuid:'scalar',params:{type:'float',value:0},ui:{x:0,y:0}});
const plainPacket=clipboard.decode(clipboard.encode(plain,plain.stages.pixel,['plain'],'one'));
assert.equal(plainPacket.typeDefinitions,undefined);
clipboard.paste(conflict,conflict.stages.pixel,plainPacket,{...options,catalog:[{key:'scalar',definitionUuid:'scalar',stages:['pixel']}]});
assert.equal(conflict.stages.pixel.nodes.length,1);
const dependency={id:'outer',name:'Outer',fields:[{id:'child',name:'child',type:'struct:sample[2]'}]};
assert.deepEqual(Array.from(defs.reachable([shape,dependency],{type:'struct:outer'}),d=>d.id),['sample','outer']);
console.log('Composite exchange: clipboard, conflicting identities, bounds and personal definitions passed');
