const assert=require('node:assert/strict');
const m=require('../../src/editor/functions_model.js');
const source={id:'library_tint',name:'Tint',scope:'library',source:{id:'tint',version:'v1'},inputs:[],outputs:[],graph:{nodes:[],edges:[]}};
const call=(id,fn)=>({id,definitionUuid:m.CALL,params:{functionId:fn}});
const graph=()=>({stages:{pixel:{nodes:[],edges:[]},vertex:{nodes:[],edges:[]}},functions:[]});
const a=graph(),b=graph();const f=m.importLibrary(a,source);m.importLibrary(b,source);
assert.equal(m.importLibrary(a,source),f);
a.stages.pixel.nodes.push(call('a',f.id),call('b',f.id));
const map=m.localize(a,f.id),id=map.get(source.id);
assert.ok(id);assert.equal(a.stages.pixel.nodes[0].params.functionId,id);assert.equal(a.stages.pixel.nodes[1].params.functionId,id);
assert.deepEqual(m.find(a,source.id),source);assert.deepEqual(b.functions[0],source);
assert.equal(m.importLibrary(a,source).id,source.id);
const separate=m.independent(a,a.stages.pixel.nodes[0]);assert.notEqual(separate.id,id);assert.equal(a.stages.pixel.nodes[1].params.functionId,id);
const nested=graph();const child=m.importLibrary(nested,source);
const parent={...structuredClone(source),id:'parent',source:{id:'parent',version:'v1'},graph:{nodes:[call('inner',child.id)],edges:[]}};
m.importLibrary(nested,parent);nested.stages.pixel.nodes.push(call('outer',parent.id));
const nestedMap=m.localize(nested,child.id);
assert.equal(nestedMap.size,2);
assert.deepEqual(m.find(nested,parent.id),parent);
assert.equal(m.find(nested,nestedMap.get(parent.id)).graph.nodes[0].params.functionId,nestedMap.get(source.id));
assert.equal(nested.stages.pixel.nodes[0].params.functionId,nestedMap.get(parent.id));
console.log('Function model: reuse, Shader isolation, copy-on-write, independent calls and nested source preservation passed');

// Expression-sized interfaces retain provenance through copy-on-write identities.
const lengths=m.GraphArrayLengths,sized=graph(),token=lengths.token('fn_sized',['sum','out']);
const sizedFn={...structuredClone(source),id:'sized',outputs:[{id:'array',type:'float['+token+']'}]};
m.importLibrary(sized,sizedFn);sized.stages.pixel.nodes.push(call('use','sized'));
const sizedMap=m.localize(sized,'sized'),localized=m.find(sized,sizedMap.get('sized'));
assert.equal(localized.outputs[0].type,'float['+lengths.token('fn_'+localized.id,['sum','out'])+']');
const sizedCopy=m.independent(sized,sized.stages.pixel.nodes[0]);
assert.equal(sizedCopy.outputs[0].type,'float['+lengths.token('fn_'+sizedCopy.id,['sum','out'])+']');
